update/composer.lock
- Upgrading doctrine/instantiator (1.3.1 => 1.4.0)
- Upgrading illuminate/bus (v8.13.0 => v8.14.0)
- Upgrading illuminate/cache (v8.13.0 => v8.14.0)
- Upgrading illuminate/collections (v8.13.0 => v8.14.0)
- Upgrading illuminate/config (v8.13.0 => v8.14.0)
- Upgrading illuminate/console (v8.13.0 => v8.14.0)
- Upgrading illuminate/container (v8.13.0 => v8.14.0)
- Upgrading illuminate/contracts (v8.13.0 => v8.14.0)
- Upgrading illuminate/events (v8.13.0 => v8.14.0)
- Upgrading illuminate/filesystem (v8.13.0 => v8.14.0)
- Upgrading illuminate/macroable (v8.13.0 => v8.14.0)
- Upgrading illuminate/pipeline (v8.13.0 => v8.14.0)
- Upgrading illuminate/support (v8.13.0 => v8.14.0)
- Upgrading illuminate/testing (v8.13.0 => v8.14.0)
- Upgrading phpunit/phpunit (9.4.2 => 9.4.3)
=> composer update 2020-11-11

update/composer.lock
- Upgrading laravel-zero/foundation (v8.13.0 => v8.14.0)
- Upgrading php-http/message (1.9.1 => 1.10.0)
- Upgrading voku/portable-ascii (1.5.4 => 1.5.6)
=> composer update 2020-11-12

update/composer.lock
- Upgrading myclabs/deep-copy (1.10.1 => 1.10.2)
=> composer update 2020-11-14

update/composer.lock
- Upgrading illuminate/bus (v8.14.0 => v8.15.0)
- Upgrading illuminate/cache (v8.14.0 => v8.15.0)
- Upgrading illuminate/collections (v8.14.0 => v8.15.0)
- Upgrading illuminate/config (v8.14.0 => v8.15.0)
- Upgrading illuminate/console (v8.14.0 => v8.15.0)
- Upgrading illuminate/container (v8.14.0 => v8.15.0)
- Upgrading illuminate/contracts (v8.14.0 => v8.15.0)
- Upgrading illuminate/events (v8.14.0 => v8.15.0)
- Upgrading illuminate/filesystem (v8.14.0 => v8.15.0)
- Upgrading illuminate/macroable (v8.14.0 => v8.15.0)
- Upgrading illuminate/pipeline (v8.14.0 => v8.15.0)
- Upgrading illuminate/support (v8.14.0 => v8.15.0)
- Upgrading illuminate/testing (v8.14.0 => v8.15.0)
- Upgrading laravel-zero/foundation (v8.14.0 => v8.15.0)
=> composer update 2020-11-18

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.0.2 => v3.1.0)
- Upgrading illuminate/bus (v8.15.0 => v8.16.0)
- Upgrading illuminate/cache (v8.15.0 => v8.16.0)
- Upgrading illuminate/collections (v8.15.0 => v8.16.0)
- Upgrading illuminate/config (v8.15.0 => v8.16.0)
- Upgrading illuminate/console (v8.15.0 => v8.16.0)
- Upgrading illuminate/container (v8.15.0 => v8.16.0)
- Upgrading illuminate/contracts (v8.15.0 => v8.16.0)
- Upgrading illuminate/events (v8.15.0 => v8.16.0)
- Upgrading illuminate/filesystem (v8.15.0 => v8.16.0)
- Upgrading illuminate/pipeline (v8.15.0 => v8.16.0)
- Upgrading illuminate/support (v8.15.0 => v8.16.0)
- Upgrading illuminate/testing (v8.15.0 => v8.16.0)
=> composer update 2020-11-25

update/composer.lock
- Upgrading graham-campbell/github (v9.5.0 => v9.6.0)
- Upgrading knplabs/github-api (v2.16.0 => v2.17.0)
- Upgrading php-http/discovery (1.12.0 => 1.13.0)
- Upgrading phpunit/php-code-coverage (9.2.3 => 9.2.4)
=> composer update 2020-11-28

update/composer.lock
- Upgrading nesbot/carbon (2.41.5 => 2.42.0)
- Upgrading phpunit/php-code-coverage (9.2.4 => 9.2.5)
- Upgrading sebastian/lines-of-code (1.0.2 => 1.0.3)
=> composer update 2020-11-29

update/composer.lock
- Upgrading laravel-zero/foundation (v8.15.0 => v8.17.1)
=> composer update 2020-12-03

update/composer.lock
- Upgrading illuminate/bus (v8.17.0 => v8.17.2)
- Upgrading illuminate/cache (v8.17.0 => v8.17.2)
- Upgrading illuminate/collections (v8.17.0 => v8.17.2)
- Upgrading illuminate/config (v8.17.0 => v8.17.2)
- Upgrading illuminate/console (v8.17.0 => v8.17.2)
- Upgrading illuminate/container (v8.17.0 => v8.17.2)
- Upgrading illuminate/contracts (v8.17.0 => v8.17.2)
- Upgrading illuminate/events (v8.17.0 => v8.17.2)
- Upgrading illuminate/filesystem (v8.17.0 => v8.17.2)
- Upgrading illuminate/macroable (v8.17.0 => v8.17.2)
- Upgrading illuminate/pipeline (v8.17.0 => v8.17.2)
- Upgrading illuminate/support (v8.17.0 => v8.17.2)
- Upgrading illuminate/testing (v8.17.0 => v8.17.2)
- Upgrading nikic/php-parser (v4.10.2 => v4.10.3)
=> composer update 2020-12-04

update/composer.lock
- Upgrading phpunit/phpunit (9.4.4 => 9.5.0)
=> composer update 2020-12-06

update/composer.lock
- Upgrading illuminate/bus (v8.17.2 => v8.18.1)
- Upgrading illuminate/cache (v8.17.2 => v8.18.1)
- Upgrading illuminate/collections (v8.17.2 => v8.18.1)
- Upgrading illuminate/config (v8.17.2 => v8.18.1)
- Upgrading illuminate/console (v8.17.2 => v8.18.1)
- Upgrading illuminate/container (v8.17.2 => v8.18.1)
- Upgrading illuminate/contracts (v8.17.2 => v8.18.1)
- Upgrading illuminate/events (v8.17.2 => v8.18.1)
- Upgrading illuminate/filesystem (v8.17.2 => v8.18.1)
- Upgrading illuminate/macroable (v8.17.2 => v8.18.1)
- Upgrading illuminate/pipeline (v8.17.2 => v8.18.1)
- Upgrading illuminate/support (v8.17.2 => v8.18.1)
- Upgrading illuminate/testing (v8.17.2 => v8.18.1)
- Upgrading laravel-zero/framework (v8.2.0 => v8.3.0)
=> composer update 2020-12-09

update/composer.lock
- Upgrading laravel-zero/foundation (v8.17.1 => v8.18.1)
=> composer update 2020-12-10

update/composer.lock
- Upgrading graham-campbell/github (v9.6.0 => v9.7.1)
- Upgrading knplabs/github-api (v2.17.0 => v2.18.0)
=> composer update 2020-12-13

update/composer.lock
- Upgrading nunomaduro/laravel-console-summary (v1.7.0 => v1.7.1)
=> composer update 2020-12-15

update/composer.lock
- Upgrading illuminate/bus (v8.18.1 => v8.19.0)
- Upgrading illuminate/cache (v8.18.1 => v8.19.0)
- Upgrading illuminate/collections (v8.18.1 => v8.19.0)
- Upgrading illuminate/config (v8.18.1 => v8.19.0)
- Upgrading illuminate/console (v8.18.1 => v8.19.0)
- Upgrading illuminate/container (v8.18.1 => v8.19.0)
- Upgrading illuminate/contracts (v8.18.1 => v8.19.0)
- Upgrading illuminate/events (v8.18.1 => v8.19.0)
- Upgrading illuminate/filesystem (v8.18.1 => v8.19.0)
- Upgrading illuminate/macroable (v8.18.1 => v8.19.0)
- Upgrading illuminate/pipeline (v8.18.1 => v8.19.0)
- Upgrading illuminate/support (v8.18.1 => v8.19.0)
- Upgrading illuminate/testing (v8.18.1 => v8.19.0)
=> composer update 2020-12-16

update/composer.lock
- Upgrading laravel-zero/foundation (v8.18.1 => v8.19.0)
=> composer update 2020-12-17

update/composer.lock
- Upgrading symfony/cache (v5.2.0 => v5.2.1)
- Upgrading symfony/console (v5.2.0 => v5.2.1)
- Upgrading symfony/error-handler (v5.2.0 => v5.2.1)
- Upgrading symfony/finder (v5.2.0 => v5.2.1)
- Upgrading symfony/options-resolver (v5.2.0 => v5.2.1)
- Upgrading symfony/process (v5.2.0 => v5.2.1)
- Upgrading symfony/string (v5.2.0 => v5.2.1)
- Upgrading symfony/translation (v5.2.0 => v5.2.1)
- Upgrading symfony/var-dumper (v5.2.0 => v5.2.1)
- Upgrading symfony/var-exporter (v5.2.0 => v5.2.1)
=> composer update 2020-12-19

update/composer.lock
- Upgrading nesbot/carbon (2.42.0 => 2.43.0)
- Upgrading phpspec/prophecy (1.12.1 => 1.12.2)
=> composer update 2020-12-20

update/composer.lock
- Upgrading illuminate/bus (v8.19.0 => v8.20.1)
- Upgrading illuminate/cache (v8.19.0 => v8.20.1)
- Upgrading illuminate/collections (v8.19.0 => v8.20.1)
- Upgrading illuminate/config (v8.19.0 => v8.20.1)
- Upgrading illuminate/console (v8.19.0 => v8.20.1)
- Upgrading illuminate/container (v8.19.0 => v8.20.1)
- Upgrading illuminate/contracts (v8.19.0 => v8.20.1)
- Upgrading illuminate/events (v8.19.0 => v8.20.1)
- Upgrading illuminate/filesystem (v8.19.0 => v8.20.1)
- Upgrading illuminate/macroable (v8.19.0 => v8.20.1)
- Upgrading illuminate/pipeline (v8.19.0 => v8.20.1)
- Upgrading illuminate/support (v8.19.0 => v8.20.1)
- Upgrading illuminate/testing (v8.19.0 => v8.20.1)
=> composer update 2020-12-23

update/composer.lock
- Upgrading laravel-zero/foundation (v8.19.0 => v8.20.1)
=> composer update 2020-12-24

update/composer.lock
- Upgrading laravel-zero/framework (v8.4.0 => v8.5.0)
=> composer update 2021-01-04

update/composer.lock
- Upgrading illuminate/bus (v8.20.1 => v8.21.0)
- Upgrading illuminate/cache (v8.20.1 => v8.21.0)
- Upgrading illuminate/collections (v8.20.1 => v8.21.0)
- Upgrading illuminate/config (v8.20.1 => v8.21.0)
- Upgrading illuminate/console (v8.20.1 => v8.21.0)
- Upgrading illuminate/container (v8.20.1 => v8.21.0)
- Upgrading illuminate/contracts (v8.20.1 => v8.21.0)
- Upgrading illuminate/events (v8.20.1 => v8.21.0)
- Upgrading illuminate/filesystem (v8.20.1 => v8.21.0)
- Upgrading illuminate/macroable (v8.20.1 => v8.21.0)
- Upgrading illuminate/pipeline (v8.20.1 => v8.21.0)
- Upgrading illuminate/support (v8.20.1 => v8.21.0)
- Upgrading illuminate/testing (v8.20.1 => v8.21.0)
=> composer update 2021-01-06

update/composer.lock
- Upgrading laravel-zero/foundation (v8.20.1 => v8.21.0)
- Upgrading symfony/polyfill-ctype (v1.20.0 => v1.22.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.20.0 => v1.22.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.20.0 => v1.22.0)
- Upgrading symfony/polyfill-mbstring (v1.20.0 => v1.22.0)
- Upgrading symfony/polyfill-php73 (v1.20.0 => v1.22.0)
- Upgrading symfony/polyfill-php80 (v1.20.0 => v1.22.0)
=> composer update 2021-01-08

update/composer.lock
- Upgrading graham-campbell/github (v10.0.0 => v10.0.1)
=> composer update 2021-01-09

update/composer.lock
- Upgrading illuminate/bus (v8.21.0 => v8.22.0)
- Upgrading illuminate/cache (v8.21.0 => v8.22.0)
- Upgrading illuminate/collections (v8.21.0 => v8.22.0)
- Upgrading illuminate/config (v8.21.0 => v8.22.0)
- Upgrading illuminate/console (v8.21.0 => v8.22.0)
- Upgrading illuminate/container (v8.21.0 => v8.22.0)
- Upgrading illuminate/contracts (v8.21.0 => v8.22.0)
- Upgrading illuminate/events (v8.21.0 => v8.22.0)
- Upgrading illuminate/filesystem (v8.21.0 => v8.22.0)
- Upgrading illuminate/macroable (v8.21.0 => v8.22.0)
- Upgrading illuminate/pipeline (v8.21.0 => v8.22.0)
- Upgrading illuminate/support (v8.21.0 => v8.22.0)
- Upgrading illuminate/testing (v8.21.0 => v8.22.0)
=> composer update 2021-01-13

update/composer.lock
- Upgrading illuminate/bus (v8.22.0 => v8.22.1)
- Upgrading illuminate/cache (v8.22.0 => v8.22.1)
- Upgrading illuminate/collections (v8.22.0 => v8.22.1)
- Upgrading illuminate/config (v8.22.0 => v8.22.1)
- Upgrading illuminate/console (v8.22.0 => v8.22.1)
- Upgrading illuminate/container (v8.22.0 => v8.22.1)
- Upgrading illuminate/contracts (v8.22.0 => v8.22.1)
- Upgrading illuminate/events (v8.22.0 => v8.22.1)
- Upgrading illuminate/filesystem (v8.22.0 => v8.22.1)
- Upgrading illuminate/macroable (v8.22.0 => v8.22.1)
- Upgrading illuminate/pipeline (v8.22.0 => v8.22.1)
- Upgrading illuminate/support (v8.22.0 => v8.22.1)
- Upgrading illuminate/testing (v8.22.0 => v8.22.1)
- Upgrading laravel-zero/foundation (v8.21.0 => v8.22.0)
- Upgrading nunomaduro/collision (v5.1.0 => v5.2.0)
=> composer update 2021-01-14

update/composer.lock
- Upgrading graham-campbell/github (v10.0.1 => v10.0.2)
=> composer update 2021-01-15

update/composer.lock
- Upgrading phpunit/phpunit (9.5.0 => 9.5.1)
=> composer update 2021-01-18

update/composer.lock
- Upgrading league/mime-type-detection (1.5.1 => 1.7.0)
=> composer update 2021-01-19

update/composer.lock
- Upgrading illuminate/bus (v8.22.1 => v8.23.1)
- Upgrading illuminate/cache (v8.22.1 => v8.23.1)
- Upgrading illuminate/collections (v8.22.1 => v8.23.1)
- Upgrading illuminate/config (v8.22.1 => v8.23.1)
- Upgrading illuminate/console (v8.22.1 => v8.23.1)
- Upgrading illuminate/container (v8.22.1 => v8.23.1)
- Upgrading illuminate/contracts (v8.22.1 => v8.23.1)
- Upgrading illuminate/events (v8.22.1 => v8.23.1)
- Upgrading illuminate/filesystem (v8.22.1 => v8.23.1)
- Upgrading illuminate/macroable (v8.22.1 => v8.23.1)
- Upgrading illuminate/pipeline (v8.22.1 => v8.23.1)
- Upgrading illuminate/support (v8.22.1 => v8.23.1)
- Upgrading illuminate/testing (v8.22.1 => v8.23.1)
=> composer update 2021-01-20

update/composer.lock
- Upgrading brick/math (0.9.1 => 0.9.2)
- Upgrading laravel-zero/foundation (v8.22.0 => v8.23.1)
- Upgrading laravel-zero/framework (v8.5.0 => v8.6.0)
- Upgrading ramsey/collection (1.1.1 => 1.1.2)
- Upgrading vlucas/phpdotenv (v5.2.0 => v5.3.0)
=> composer update 2021-01-21

update/composer.lock
- Upgrading filp/whoops (2.9.1 => 2.9.2)
=> composer update 2021-01-25

update/composer.lock
- Upgrading nunomaduro/collision (v5.2.0 => v5.3.0)
=> composer update 2021-01-26

update/composer.lock
- Upgrading illuminate/bus (v8.24.0 => v8.25.0)
- Upgrading illuminate/cache (v8.24.0 => v8.25.0)
- Upgrading illuminate/collections (v8.24.0 => v8.25.0)
- Upgrading illuminate/config (v8.24.0 => v8.25.0)
- Upgrading illuminate/console (v8.24.0 => v8.25.0)
- Upgrading illuminate/container (v8.24.0 => v8.25.0)
- Upgrading illuminate/contracts (v8.24.0 => v8.25.0)
- Upgrading illuminate/events (v8.24.0 => v8.25.0)
- Upgrading illuminate/filesystem (v8.24.0 => v8.25.0)
- Upgrading illuminate/macroable (v8.24.0 => v8.25.0)
- Upgrading illuminate/pipeline (v8.24.0 => v8.25.0)
- Upgrading illuminate/support (v8.24.0 => v8.25.0)
- Upgrading illuminate/testing (v8.24.0 => v8.25.0)
=> composer update 2021-01-27

update/composer.lock
- Upgrading nesbot/carbon (2.43.0 => 2.44.0)
- Upgrading symfony/cache (v5.2.1 => v5.2.2)
- Upgrading symfony/console (v5.2.1 => v5.2.2)
- Upgrading symfony/error-handler (v5.2.1 => v5.2.2)
- Upgrading symfony/finder (v5.2.1 => v5.2.2)
- Upgrading symfony/options-resolver (v5.2.1 => v5.2.2)
- Upgrading symfony/process (v5.2.1 => v5.2.2)
- Upgrading symfony/string (v5.2.1 => v5.2.2)
- Upgrading symfony/translation (v5.2.1 => v5.2.2)
- Upgrading symfony/var-dumper (v5.2.1 => v5.2.2)
- Upgrading symfony/var-exporter (v5.2.1 => v5.2.2)
=> composer update 2021-01-29

update/composer.lock
- Upgrading php-http/message (1.10.0 => 1.11.0)
=> composer update 2021-02-02

update/composer.lock
- Upgrading illuminate/bus (v8.25.0 => v8.26.1)
- Upgrading illuminate/cache (v8.25.0 => v8.26.1)
- Upgrading illuminate/collections (v8.25.0 => v8.26.1)
- Upgrading illuminate/config (v8.25.0 => v8.26.1)
- Upgrading illuminate/console (v8.25.0 => v8.26.1)
- Upgrading illuminate/container (v8.25.0 => v8.26.1)
- Upgrading illuminate/contracts (v8.25.0 => v8.26.1)
- Upgrading illuminate/events (v8.25.0 => v8.26.1)
- Upgrading illuminate/filesystem (v8.25.0 => v8.26.1)
- Upgrading illuminate/macroable (v8.25.0 => v8.26.1)
- Upgrading illuminate/pipeline (v8.25.0 => v8.26.1)
- Upgrading illuminate/support (v8.25.0 => v8.26.1)
- Upgrading illuminate/testing (v8.25.0 => v8.26.1)
- Upgrading phpunit/phpunit (9.5.1 => 9.5.2)
=> composer update 2021-02-03

update/composer.lock
- Upgrading symfony/cache (v5.2.2 => v5.2.3)
- Upgrading symfony/console (v5.2.2 => v5.2.3)
- Upgrading symfony/error-handler (v5.2.2 => v5.2.3)
- Upgrading symfony/finder (v5.2.2 => v5.2.3)
- Upgrading symfony/options-resolver (v5.2.2 => v5.2.3)
- Upgrading symfony/process (v5.2.2 => v5.2.3)
- Upgrading symfony/string (v5.2.2 => v5.2.3)
- Upgrading symfony/translation (v5.2.2 => v5.2.3)
- Upgrading symfony/var-dumper (v5.2.2 => v5.2.3)
- Upgrading symfony/var-exporter (v5.2.2 => v5.2.3)
=> composer update 2021-02-04

update/composer.lock
- Upgrading illuminate/bus (v8.26.1 => v8.27.0)
- Upgrading illuminate/cache (v8.26.1 => v8.27.0)
- Upgrading illuminate/collections (v8.26.1 => v8.27.0)
- Upgrading illuminate/config (v8.26.1 => v8.27.0)
- Upgrading illuminate/console (v8.26.1 => v8.27.0)
- Upgrading illuminate/container (v8.26.1 => v8.27.0)
- Upgrading illuminate/contracts (v8.26.1 => v8.27.0)
- Upgrading illuminate/events (v8.26.1 => v8.27.0)
- Upgrading illuminate/filesystem (v8.26.1 => v8.27.0)
- Upgrading illuminate/macroable (v8.26.1 => v8.27.0)
- Upgrading illuminate/pipeline (v8.26.1 => v8.27.0)
- Upgrading illuminate/support (v8.26.1 => v8.27.0)
- Upgrading illuminate/testing (v8.26.1 => v8.27.0)
- Upgrading nesbot/carbon (2.44.0 => 2.45.0)
=> composer update 2021-02-10

update/composer.lock
- Upgrading laravel-zero/foundation (v8.23.1 => v8.27.0)
=> composer update 2021-02-11

update/composer.lock
- Upgrading nesbot/carbon (2.45.0 => 2.45.1)
=> composer update 2021-02-12

update/composer.lock
- Upgrading czproject/git-php (v3.18.1 => v3.18.2)
=> composer update 2021-02-16

update/composer.lock
- Upgrading illuminate/bus (v8.27.0 => v8.28.1)
- Upgrading illuminate/cache (v8.27.0 => v8.28.1)
- Upgrading illuminate/collections (v8.27.0 => v8.28.1)
- Upgrading illuminate/config (v8.27.0 => v8.28.1)
- Upgrading illuminate/console (v8.27.0 => v8.28.1)
- Upgrading illuminate/container (v8.27.0 => v8.28.1)
- Upgrading illuminate/contracts (v8.27.0 => v8.28.1)
- Upgrading illuminate/events (v8.27.0 => v8.28.1)
- Upgrading illuminate/filesystem (v8.27.0 => v8.28.1)
- Upgrading illuminate/macroable (v8.27.0 => v8.28.1)
- Upgrading illuminate/pipeline (v8.27.0 => v8.28.1)
- Upgrading illuminate/support (v8.27.0 => v8.28.1)
- Upgrading illuminate/testing (v8.27.0 => v8.28.1)
- Upgrading symfony/polyfill-ctype (v1.22.0 => v1.22.1)
- Upgrading symfony/polyfill-intl-grapheme (v1.22.0 => …
=> composer update 2021-02-17

update/composer.lock
- Upgrading laravel-zero/foundation (v8.27.0 => v8.28.1)
=> composer update 2021-02-19

update/composer.lock
- Upgrading laravel-zero/foundation (v8.29.0 => v8.29.1)
=> composer update 2021-02-26

update/composer.lock
- Upgrading psr/container (1.0.0 => 1.1.1)
=> composer update 2021-03-06

update/composer.lock
- Upgrading guzzlehttp/promises (1.4.0 => 1.4.1)
- Upgrading jolicode/jolinotif (v2.2.0 => v2.3.0)
=> composer update 2021-03-08

update/composer.lock
- Upgrading nesbot/carbon (2.45.1 => 2.46.0)
=> composer update 2021-03-09

update/composer.lock
- Upgrading laravel-zero/foundation (v8.29.1 => v8.32.1)
- Upgrading symfony/console (v5.2.4 => v5.2.5)
- Upgrading symfony/translation (v5.2.4 => v5.2.5)
- Upgrading symfony/var-dumper (v5.2.4 => v5.2.5)
=> composer update 2021-03-11

update/composer.lock
- Upgrading phpspec/prophecy (1.12.2 => 1.13.0)
- Upgrading phpunit/phpunit (9.5.2 => 9.5.3)
=> composer update 2021-03-18

update/composer.lock
- Upgrading filp/whoops (2.10.0 => 2.11.0)
=> composer update 2021-03-20

update/composer.lock
- Upgrading guzzlehttp/psr7 (1.7.0 => 1.8.1)
=> composer update 2021-03-22

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.5 => 9.2.6)
=> composer update 2021-03-29

update/composer.lock
- Upgrading symfony/cache (v5.2.4 => v5.2.6)
- Upgrading symfony/console (v5.2.5 => v5.2.6)
- Upgrading symfony/error-handler (v5.2.4 => v5.2.6)
- Upgrading symfony/string (v5.2.4 => v5.2.6)
- Upgrading symfony/translation (v5.2.5 => v5.2.6)
- Upgrading symfony/var-dumper (v5.2.5 => v5.2.6)
=> composer update 2021-03-30

update/composer.lock
- Upgrading nunomaduro/collision (v5.3.0 => v5.4.0)
=> composer update 2021-04-10

update/composer.lock
- Upgrading php-http/cache-plugin (1.7.1 => 1.7.2)
=> composer update 2021-04-15

update/composer.lock
- Upgrading laravel-zero/foundation (v8.35.1 => v8.37.0)
- Upgrading laravel-zero/framework (v8.6.0 => v8.7.0)
=> composer update 2021-04-16

update/composer.lock
- Upgrading symfony/cache-contracts (v2.2.0 => v2.4.0)
- Upgrading symfony/deprecation-contracts (v2.2.0 => v2.4.0)
- Upgrading symfony/service-contracts (v2.2.0 => v2.4.0)
- Upgrading symfony/translation-contracts (v2.3.0 => v2.4.0)
=> composer update 2021-04-20

update/composer.lock
- Upgrading laravel-zero/foundation (v8.37.0 => v8.38.0)
=> composer update 2021-04-22

update/composer.lock
- Upgrading filp/whoops (2.12.0 => 2.12.1)
=> composer update 2021-04-26

update/composer.lock
- Upgrading guzzlehttp/psr7 (1.8.1 => 1.8.2)
=> composer update 2021-04-27

update/composer.lock
- Upgrading illuminate/bus (v8.39.0 => v8.40.0)
- Upgrading illuminate/cache (v8.39.0 => v8.40.0)
- Upgrading illuminate/collections (v8.39.0 => v8.40.0)
- Upgrading illuminate/config (v8.39.0 => v8.40.0)
- Upgrading illuminate/console (v8.39.0 => v8.40.0)
- Upgrading illuminate/container (v8.39.0 => v8.40.0)
- Upgrading illuminate/contracts (v8.39.0 => v8.40.0)
- Upgrading illuminate/events (v8.39.0 => v8.40.0)
- Upgrading illuminate/filesystem (v8.39.0 => v8.40.0)
- Upgrading illuminate/macroable (v8.38.0 => v8.40.0)
- Upgrading illuminate/pipeline (v8.39.0 => v8.40.0)
- Upgrading illuminate/support (v8.39.0 => v8.40.0)
- Upgrading illuminate/testing (v8.39.0 => v8.40.0)
- Upgrading laravel-zero/foundation (v8.38.0 => v8.39.0)
=> composer update 2021-04-29

update/composer.lock
- Upgrading symfony/cache (v5.2.6 => v5.2.7)
- Upgrading symfony/console (v5.2.6 => v5.2.7)
- Upgrading symfony/error-handler (v5.2.6 => v5.2.7)
- Upgrading symfony/process (v5.2.4 => v5.2.7)
- Upgrading symfony/translation (v5.2.6 => v5.2.7)
- Upgrading symfony/var-dumper (v5.2.6 => v5.2.7)
- Upgrading symfony/var-exporter (v5.2.4 => v5.2.7)
=> composer update 2021-05-02

update/composer.lock
- Upgrading graham-campbell/github (v10.0.2 => v10.2.0)
- Upgrading knplabs/github-api (v3.0.0 => v3.2.0)
- Upgrading nesbot/carbon (2.46.0 => 2.47.0)
=> composer update 2021-05-03

update/composer.lock
- Upgrading nikic/php-parser (v4.10.4 => v4.10.5)
- Upgrading psr/log (1.1.3 => 1.1.4)
=> composer update 2021-05-04

update/composer.lock
- Upgrading illuminate/bus (v8.40.0 => v8.41.0)
- Upgrading illuminate/cache (v8.40.0 => v8.41.0)
- Upgrading illuminate/collections (v8.40.0 => v8.41.0)
- Upgrading illuminate/config (v8.40.0 => v8.41.0)
- Upgrading illuminate/console (v8.40.0 => v8.41.0)
- Upgrading illuminate/container (v8.40.0 => v8.41.0)
- Upgrading illuminate/contracts (v8.40.0 => v8.41.0)
- Upgrading illuminate/events (v8.40.0 => v8.41.0)
- Upgrading illuminate/filesystem (v8.40.0 => v8.41.0)
- Upgrading illuminate/macroable (v8.40.0 => v8.41.0)
- Upgrading illuminate/pipeline (v8.40.0 => v8.41.0)
- Upgrading illuminate/support (v8.40.0 => v8.41.0)
- Upgrading illuminate/testing (v8.40.0 => v8.41.0)
=> composer update 2021-05-12

update/composer.lock
- Upgrading laravel-zero/foundation (v8.39.0 => v8.41.0)
- Upgrading nesbot/carbon (2.47.0 => 2.48.0)
- Upgrading symfony/cache (v5.2.7 => v5.2.8)
- Upgrading symfony/console (v5.2.7 => v5.2.8)
- Upgrading symfony/error-handler (v5.2.7 => v5.2.8)
- Upgrading symfony/finder (v5.2.4 => v5.2.8)
- Upgrading symfony/string (v5.2.6 => v5.2.8)
- Upgrading symfony/translation (v5.2.7 => v5.2.8)
- Upgrading symfony/var-dumper (v5.2.7 => v5.2.8)
- Upgrading symfony/var-exporter (v5.2.7 => v5.2.8)
=> composer update 2021-05-13

update/composer.lock
- Upgrading illuminate/bus (v8.42.0 => v8.42.1)
- Upgrading illuminate/cache (v8.42.0 => v8.42.1)
- Upgrading illuminate/collections (v8.42.0 => v8.42.1)
- Upgrading illuminate/config (v8.42.0 => v8.42.1)
- Upgrading illuminate/console (v8.42.0 => v8.42.1)
- Upgrading illuminate/container (v8.42.0 => v8.42.1)
- Upgrading illuminate/contracts (v8.42.0 => v8.42.1)
- Upgrading illuminate/events (v8.42.0 => v8.42.1)
- Upgrading illuminate/filesystem (v8.42.0 => v8.42.1)
- Upgrading illuminate/macroable (v8.42.0 => v8.42.1)
- Upgrading illuminate/pipeline (v8.42.0 => v8.42.1)
- Upgrading illuminate/support (v8.42.0 => v8.42.1)
- Upgrading illuminate/testing (v8.42.0 => v8.42.1)
- Upgrading symfony/cache (v5.2.8 => v5.2.9)
- Upgrading symfony/finder (v5.2.8 => v5.2.9)
- Upgrading …
=> composer update 2021-05-20

update/composer.lock
- Upgrading laravel-zero/foundation (v8.41.0 => v8.42.1)
- Upgrading php-http/multipart-stream-builder (1.1.2 => 1.2.0)
=> composer update 2021-05-22

update/composer.lock
- Upgrading graham-campbell/github (v10.2.0 => v10.3.0)
- Upgrading knplabs/github-api (v3.2.0 => v3.3.0)
=> composer update 2021-05-24

update/composer.lock
- Upgrading php-http/message (1.11.0 => 1.11.1)
=> composer update 2021-05-25

update/composer.lock
- Upgrading illuminate/bus (v8.42.1 => v8.43.0)
- Upgrading illuminate/cache (v8.42.1 => v8.43.0)
- Upgrading illuminate/collections (v8.42.1 => v8.43.0)
- Upgrading illuminate/config (v8.42.1 => v8.43.0)
- Upgrading illuminate/console (v8.42.1 => v8.43.0)
- Upgrading illuminate/container (v8.42.1 => v8.43.0)
- Upgrading illuminate/contracts (v8.42.1 => v8.43.0)
- Upgrading illuminate/events (v8.42.1 => v8.43.0)
- Upgrading illuminate/filesystem (v8.42.1 => v8.43.0)
- Upgrading illuminate/macroable (v8.42.1 => v8.43.0)
- Upgrading illuminate/pipeline (v8.42.1 => v8.43.0)
- Upgrading illuminate/support (v8.42.1 => v8.43.0)
- Upgrading illuminate/testing (v8.42.1 => v8.43.0)
=> composer update 2021-05-26

update/composer.lock
- Upgrading nesbot/carbon (2.48.0 => 2.48.1)
=> composer update 2021-05-27

update/composer.lock
- Upgrading illuminate/bus (v8.43.0 => v8.44.0)
- Upgrading illuminate/cache (v8.43.0 => v8.44.0)
- Upgrading illuminate/collections (v8.43.0 => v8.44.0)
- Upgrading illuminate/config (v8.43.0 => v8.44.0)
- Upgrading illuminate/console (v8.43.0 => v8.44.0)
- Upgrading illuminate/container (v8.43.0 => v8.44.0)
- Upgrading illuminate/contracts (v8.43.0 => v8.44.0)
- Upgrading illuminate/events (v8.43.0 => v8.44.0)
- Upgrading illuminate/filesystem (v8.43.0 => v8.44.0)
- Upgrading illuminate/macroable (v8.43.0 => v8.44.0)
- Upgrading illuminate/pipeline (v8.43.0 => v8.44.0)
- Upgrading illuminate/support (v8.43.0 => v8.44.0)
- Upgrading illuminate/testing (v8.43.0 => v8.44.0)
- Upgrading laravel-zero/framework (v8.7.0 => v8.8.0)
- Upgrading symfony/polyfill-ctype (v1.22.1 => v1.23.0)
- …
=> composer update 2021-05-28

update/composer.lock
- Upgrading symfony/cache (v5.2.9 => v5.3.0)
- Upgrading symfony/console (v5.2.8 => v5.3.0)
- Upgrading symfony/error-handler (v5.2.8 => v5.3.0)
- Upgrading symfony/finder (v5.2.9 => v5.3.0)
- Upgrading symfony/options-resolver (v5.2.4 => v5.3.0)
- Upgrading symfony/process (v5.2.7 => v5.3.0)
- Upgrading symfony/string (v5.2.8 => v5.3.0)
- Upgrading symfony/translation (v5.2.9 => v5.3.0)
- Upgrading symfony/var-dumper (v5.2.8 => v5.3.0)
- Upgrading symfony/var-exporter (v5.2.8 => v5.3.0)
=> composer update 2021-06-01

update/composer.lock
- Upgrading php-http/discovery (1.13.0 => 1.14.0)
=> composer update 2021-06-02

update/composer.lock
- Upgrading illuminate/bus (v8.44.0 => v8.45.1)
- Upgrading illuminate/cache (v8.44.0 => v8.45.1)
- Upgrading illuminate/collections (v8.44.0 => v8.45.1)
- Upgrading illuminate/config (v8.44.0 => v8.45.1)
- Upgrading illuminate/console (v8.44.0 => v8.45.1)
- Upgrading illuminate/container (v8.44.0 => v8.45.1)
- Upgrading illuminate/contracts (v8.44.0 => v8.45.1)
- Upgrading illuminate/events (v8.44.0 => v8.45.1)
- Upgrading illuminate/filesystem (v8.44.0 => v8.45.1)
- Upgrading illuminate/macroable (v8.44.0 => v8.45.1)
- Upgrading illuminate/pipeline (v8.44.0 => v8.45.1)
- Upgrading illuminate/support (v8.44.0 => v8.45.1)
- Upgrading illuminate/testing (v8.44.0 => v8.45.1)
- Upgrading laravel-zero/framework (v8.8.0 => v8.9.0)
=> composer update 2021-06-04

update/composer.lock
- Upgrading filp/whoops (2.12.1 => 2.13.0)
- Upgrading phpunit/phpunit (9.5.4 => 9.5.5)
- Upgrading sebastian/type (2.3.1 => 2.3.2)
=> composer update 2021-06-05

update/composer.lock
- Upgrading nesbot/carbon (2.48.1 => 2.49.0)
=> composer update 2021-06-10

update/composer.lock
- Upgrading sebastian/global-state (5.0.2 => 5.0.3)
=> composer update 2021-06-12

update/composer.lock
- Upgrading czproject/git-php (v4.0.1 => v4.0.2)
- Upgrading illuminate/bus (v8.46.0 => v8.47.0)
- Upgrading illuminate/cache (v8.46.0 => v8.47.0)
- Upgrading illuminate/collections (v8.46.0 => v8.47.0)
- Upgrading illuminate/config (v8.46.0 => v8.47.0)
- Upgrading illuminate/console (v8.46.0 => v8.47.0)
- Upgrading illuminate/container (v8.46.0 => v8.47.0)
- Upgrading illuminate/contracts (v8.46.0 => v8.47.0)
- Upgrading illuminate/events (v8.46.0 => v8.47.0)
- Upgrading illuminate/filesystem (v8.46.0 => v8.47.0)
- Upgrading illuminate/macroable (v8.46.0 => v8.47.0)
- Upgrading illuminate/pipeline (v8.46.0 => v8.47.0)
- Upgrading illuminate/support (v8.46.0 => v8.47.0)
- Upgrading illuminate/testing (v8.46.0 => v8.47.0)
- Upgrading sebastian/type (2.3.2 => 2.3.4)
=> composer update 2021-06-16

update/composer.lock
- Upgrading symfony/console (v5.3.0 => v5.3.2)
- Upgrading symfony/process (v5.3.0 => v5.3.2)
- Upgrading symfony/string (v5.3.0 => v5.3.2)
- Upgrading symfony/translation (v5.3.0 => v5.3.2)
- Upgrading symfony/var-dumper (v5.3.0 => v5.3.2)
- Upgrading symfony/var-exporter (v5.3.0 => v5.3.2)
=> composer update 2021-06-18

update/composer.lock
=> composer update 2021-06-20

update/composer.lock
- Upgrading illuminate/bus (v8.47.0 => v8.48.0)
- Upgrading illuminate/cache (v8.47.0 => v8.48.0)
- Upgrading illuminate/collections (v8.47.0 => v8.48.0)
- Upgrading illuminate/config (v8.47.0 => v8.48.0)
- Upgrading illuminate/console (v8.47.0 => v8.48.0)
- Upgrading illuminate/container (v8.47.0 => v8.48.0)
- Upgrading illuminate/contracts (v8.47.0 => v8.48.0)
- Upgrading illuminate/events (v8.47.0 => v8.48.0)
- Upgrading illuminate/filesystem (v8.47.0 => v8.48.0)
- Upgrading illuminate/macroable (v8.47.0 => v8.48.0)
- Upgrading illuminate/pipeline (v8.47.0 => v8.48.0)
- Upgrading illuminate/support (v8.47.0 => v8.48.0)
- Upgrading illuminate/testing (v8.47.0 => v8.48.0)
- Upgrading nunomaduro/collision (v5.4.0 => v5.5.0)
=> composer update 2021-06-23

update/composer.lock
- Upgrading illuminate/bus (v8.48.0 => v8.48.1)
- Upgrading illuminate/cache (v8.48.0 => v8.48.1)
- Upgrading illuminate/collections (v8.48.0 => v8.48.1)
- Upgrading illuminate/config (v8.48.0 => v8.48.1)
- Upgrading illuminate/console (v8.48.0 => v8.48.1)
- Upgrading illuminate/container (v8.48.0 => v8.48.1)
- Upgrading illuminate/contracts (v8.48.0 => v8.48.1)
- Upgrading illuminate/events (v8.48.0 => v8.48.1)
- Upgrading illuminate/filesystem (v8.48.0 => v8.48.1)
- Upgrading illuminate/macroable (v8.48.0 => v8.48.1)
- Upgrading illuminate/pipeline (v8.48.0 => v8.48.1)
- Upgrading illuminate/support (v8.48.0 => v8.48.1)
- Upgrading illuminate/testing (v8.48.0 => v8.48.1)
- Upgrading laravel-zero/foundation (v8.42.1 => v8.48.1)
- Upgrading league/flysystem (1.1.3 => 1.1.4)
=> Composer update with 15 changes 2021-06-24

update/composer.lock
- Upgrading illuminate/bus (v8.48.1 => v8.48.2)
- Upgrading illuminate/cache (v8.48.1 => v8.48.2)
- Upgrading illuminate/collections (v8.48.1 => v8.48.2)
- Upgrading illuminate/config (v8.48.1 => v8.48.2)
- Upgrading illuminate/console (v8.48.1 => v8.48.2)
- Upgrading illuminate/container (v8.48.1 => v8.48.2)
- Upgrading illuminate/contracts (v8.48.1 => v8.48.2)
- Upgrading illuminate/events (v8.48.1 => v8.48.2)
- Upgrading illuminate/filesystem (v8.48.1 => v8.48.2)
- Upgrading illuminate/macroable (v8.48.1 => v8.48.2)
- Upgrading illuminate/pipeline (v8.48.1 => v8.48.2)
- Upgrading illuminate/support (v8.48.1 => v8.48.2)
- Upgrading illuminate/testing (v8.48.1 => v8.48.2)
=> Composer update with 13 changes 2021-06-26

update/composer.lock
- Upgrading illuminate/bus (v8.48.2 => v8.49.0)
- Upgrading illuminate/cache (v8.48.2 => v8.49.0)
- Upgrading illuminate/collections (v8.48.2 => v8.49.0)
- Upgrading illuminate/config (v8.48.2 => v8.49.0)
- Upgrading illuminate/console (v8.48.2 => v8.49.0)
- Upgrading illuminate/container (v8.48.2 => v8.49.0)
- Upgrading illuminate/contracts (v8.48.2 => v8.49.0)
- Upgrading illuminate/events (v8.48.2 => v8.49.0)
- Upgrading illuminate/filesystem (v8.48.2 => v8.49.0)
- Upgrading illuminate/macroable (v8.48.2 => v8.49.0)
- Upgrading illuminate/pipeline (v8.48.2 => v8.49.0)
- Upgrading illuminate/support (v8.48.2 => v8.49.0)
- Upgrading illuminate/testing (v8.48.2 => v8.49.0)
- Upgrading nesbot/carbon (2.49.0 => 2.50.0)
=> Composer update with 14 changes 2021-06-30

update/composer.lock
- Upgrading symfony/cache (v5.3.0 => v5.3.3)
- Upgrading symfony/error-handler (v5.3.0 => v5.3.3)
- Upgrading symfony/string (v5.3.2 => v5.3.3)
- Upgrading symfony/translation (v5.3.2 => v5.3.3)
- Upgrading symfony/var-dumper (v5.3.2 => v5.3.3)
- Upgrading symfony/var-exporter (v5.3.2 => v5.3.3)
=> Composer update with 6 changes 2021-07-01

update/composer.lock
- Upgrading illuminate/bus (v8.49.0 => v8.49.1)
- Upgrading illuminate/cache (v8.49.0 => v8.49.1)
- Upgrading illuminate/collections (v8.49.0 => v8.49.1)
- Upgrading illuminate/config (v8.49.0 => v8.49.1)
- Upgrading illuminate/console (v8.49.0 => v8.49.1)
- Upgrading illuminate/container (v8.49.0 => v8.49.1)
- Upgrading illuminate/contracts (v8.49.0 => v8.49.1)
- Upgrading illuminate/events (v8.49.0 => v8.49.1)
- Upgrading illuminate/filesystem (v8.49.0 => v8.49.1)
- Upgrading illuminate/macroable (v8.49.0 => v8.49.1)
- Upgrading illuminate/pipeline (v8.49.0 => v8.49.1)
- Upgrading illuminate/support (v8.49.0 => v8.49.1)
- Upgrading illuminate/testing (v8.49.0 => v8.49.1)
=> Composer update with 13 changes 2021-07-03

update/composer.lock
- Upgrading nikic/php-parser (v4.10.5 => v4.11.0)
=> Composer update with 1 changes 2021-07-04

update/composer.lock
- Upgrading php-http/client-common (2.3.0 => 2.4.0)
=> Composer update with 1 changes 2021-07-06

update/composer.lock
- Upgrading illuminate/bus (v8.49.1 => v8.49.2)
- Upgrading illuminate/cache (v8.49.1 => v8.49.2)
- Upgrading illuminate/collections (v8.49.1 => v8.49.2)
- Upgrading illuminate/config (v8.49.1 => v8.49.2)
- Upgrading illuminate/console (v8.49.1 => v8.49.2)
- Upgrading illuminate/container (v8.49.1 => v8.49.2)
- Upgrading illuminate/contracts (v8.49.1 => v8.49.2)
- Upgrading illuminate/events (v8.49.1 => v8.49.2)
- Upgrading illuminate/filesystem (v8.49.1 => v8.49.2)
- Upgrading illuminate/macroable (v8.49.1 => v8.49.2)
- Upgrading illuminate/pipeline (v8.49.1 => v8.49.2)
- Upgrading illuminate/support (v8.49.1 => v8.49.2)
- Upgrading illuminate/testing (v8.49.1 => v8.49.2)
=> Composer update with 13 changes 2021-07-07

update/composer.lock
- Upgrading laravel-zero/foundation (v8.48.1 => v8.49.2)
=> Composer update with 1 changes 2021-07-08

update/composer.lock
- Upgrading guzzlehttp/psr7 (1.8.2 => 2.0.0)
- Upgrading http-interop/http-factory-guzzle (1.0.0 => 1.1.0)
- Upgrading phpunit/phpunit (9.5.6 => 9.5.7)
=> Composer update with 3 changes 2021-07-20

update/composer.lock
- Upgrading http-interop/http-factory-guzzle (1.1.0 => 1.2.0)
- Upgrading nikic/php-parser (v4.11.0 => v4.12.0)
=> Composer update with 2 changes 2021-07-22

update/composer.lock
=> Composer update with 1 changes 2021-07-23

update/composer.lock
- Upgrading nunomaduro/collision (v5.5.0 => v5.6.0)
- Upgrading symfony/cache (v5.3.3 => v5.3.4)
- Upgrading symfony/console (v5.3.2 => v5.3.4)
- Upgrading symfony/error-handler (v5.3.3 => v5.3.4)
- Upgrading symfony/finder (v5.3.0 => v5.3.4)
- Upgrading symfony/options-resolver (v5.3.0 => v5.3.4)
- Upgrading symfony/process (v5.3.2 => v5.3.4)
- Upgrading symfony/translation (v5.3.3 => v5.3.4)
- Upgrading symfony/var-dumper (v5.3.3 => v5.3.4)
- Upgrading symfony/var-exporter (v5.3.3 => v5.3.4)
=> Composer update with 10 changes 2021-07-27

update/composer.lock
- Upgrading illuminate/bus (v8.51.0 => v8.52.0)
- Upgrading illuminate/cache (v8.51.0 => v8.52.0)
- Upgrading illuminate/collections (v8.51.0 => v8.52.0)
- Upgrading illuminate/config (v8.51.0 => v8.52.0)
- Upgrading illuminate/console (v8.51.0 => v8.52.0)
- Upgrading illuminate/container (v8.51.0 => v8.52.0)
- Upgrading illuminate/contracts (v8.51.0 => v8.52.0)
- Upgrading illuminate/events (v8.51.0 => v8.52.0)
- Upgrading illuminate/filesystem (v8.51.0 => v8.52.0)
- Upgrading illuminate/macroable (v8.51.0 => v8.52.0)
- Upgrading illuminate/pipeline (v8.51.0 => v8.52.0)
- Upgrading illuminate/support (v8.51.0 => v8.52.0)
- Upgrading illuminate/testing (v8.51.0 => v8.52.0)
=> Composer update with 13 changes 2021-07-28

update/composer.lock
- Upgrading nesbot/carbon (2.50.0 => 2.51.1)
- Upgrading theseer/tokenizer (1.2.0 => 1.2.1)
=> Composer update with 2 changes 2021-07-29

update/composer.lock
- Upgrading ramsey/collection (1.1.3 => 1.1.4)
- Upgrading symfony/console (v5.3.4 => v5.3.6)
- Upgrading symfony/polyfill-intl-grapheme (v1.23.0 => v1.23.1)
- Upgrading symfony/polyfill-mbstring (v1.23.0 => v1.23.1)
- Upgrading symfony/polyfill-php80 (v1.23.0 => v1.23.1)
- Upgrading symfony/var-dumper (v5.3.4 => v5.3.6)
=> Composer update with 6 changes 2021-07-30

update/composer.lock
- Upgrading phpunit/phpunit (9.5.7 => 9.5.8)
=> Composer update with 1 changes 2021-08-01

update/composer.lock
- Upgrading illuminate/bus (v8.52.0 => v8.53.0)
- Upgrading illuminate/cache (v8.52.0 => v8.53.0)
- Upgrading illuminate/collections (v8.52.0 => v8.53.0)
- Upgrading illuminate/config (v8.52.0 => v8.53.0)
- Upgrading illuminate/console (v8.52.0 => v8.53.0)
- Upgrading illuminate/container (v8.52.0 => v8.53.0)
- Upgrading illuminate/contracts (v8.52.0 => v8.53.0)
- Upgrading illuminate/events (v8.52.0 => v8.53.0)
- Upgrading illuminate/filesystem (v8.52.0 => v8.53.0)
- Upgrading illuminate/macroable (v8.52.0 => v8.53.0)
- Upgrading illuminate/pipeline (v8.52.0 => v8.53.0)
- Upgrading illuminate/support (v8.52.0 => v8.53.0)
- Upgrading illuminate/testing (v8.52.0 => v8.53.0)
- Upgrading php-http/message (1.11.1 => 1.11.2)
=> Composer update with 14 changes 2021-08-04

update/composer.lock
- Upgrading illuminate/bus (v8.53.0 => v8.53.1)
- Upgrading illuminate/cache (v8.53.0 => v8.53.1)
- Upgrading illuminate/collections (v8.53.0 => v8.53.1)
- Upgrading illuminate/config (v8.53.0 => v8.53.1)
- Upgrading illuminate/console (v8.53.0 => v8.53.1)
- Upgrading illuminate/container (v8.53.0 => v8.53.1)
- Upgrading illuminate/contracts (v8.53.0 => v8.53.1)
- Upgrading illuminate/events (v8.53.0 => v8.53.1)
- Upgrading illuminate/filesystem (v8.53.0 => v8.53.1)
- Upgrading illuminate/macroable (v8.53.0 => v8.53.1)
- Upgrading illuminate/pipeline (v8.53.0 => v8.53.1)
- Upgrading illuminate/support (v8.53.0 => v8.53.1)
- Upgrading illuminate/testing (v8.53.0 => v8.53.1)
- Upgrading ramsey/collection (1.1.4 => 1.2.1)
- Locking symfony/polyfill-php81 (v1.23.0)
=> Composer update with 15 changes 2021-08-06

update/composer.lock
- Upgrading ramsey/uuid (4.1.1 => 4.2.0)
=> Composer update with 1 changes 2021-08-07

update/composer.lock
- Upgrading illuminate/bus (v8.53.1 => v8.54.0)
- Upgrading illuminate/cache (v8.53.1 => v8.54.0)
- Upgrading illuminate/collections (v8.53.1 => v8.54.0)
- Upgrading illuminate/config (v8.53.1 => v8.54.0)
- Upgrading illuminate/console (v8.53.1 => v8.54.0)
- Upgrading illuminate/container (v8.53.1 => v8.54.0)
- Upgrading illuminate/contracts (v8.53.1 => v8.54.0)
- Upgrading illuminate/events (v8.53.1 => v8.54.0)
- Upgrading illuminate/filesystem (v8.53.1 => v8.54.0)
- Upgrading illuminate/macroable (v8.53.1 => v8.54.0)
- Upgrading illuminate/pipeline (v8.53.1 => v8.54.0)
- Upgrading illuminate/support (v8.53.1 => v8.54.0)
- Upgrading illuminate/testing (v8.53.1 => v8.54.0)
- Upgrading ramsey/uuid (4.2.0 => 4.2.1)
=> Composer update with 14 changes 2021-08-11

update/composer.lock
- Upgrading nunomaduro/collision (v5.6.0 => v5.7.0)
=> Composer update with 1 changes 2021-08-13

update/composer.lock
- Upgrading nunomaduro/collision (v5.7.0 => v5.8.0)
=> Composer update with 1 changes 2021-08-14

update/composer.lock
- Upgrading brick/math (0.9.2 => 0.9.3)
=> Composer update with 1 changes 2021-08-16

update/composer.lock
- Upgrading illuminate/bus (v8.54.0 => v8.55.0)
- Upgrading illuminate/cache (v8.54.0 => v8.55.0)
- Upgrading illuminate/collections (v8.54.0 => v8.55.0)
- Upgrading illuminate/config (v8.54.0 => v8.55.0)
- Upgrading illuminate/console (v8.54.0 => v8.55.0)
- Upgrading illuminate/container (v8.54.0 => v8.55.0)
- Upgrading illuminate/contracts (v8.54.0 => v8.55.0)
- Upgrading illuminate/events (v8.54.0 => v8.55.0)
- Upgrading illuminate/filesystem (v8.54.0 => v8.55.0)
- Upgrading illuminate/macroable (v8.54.0 => v8.55.0)
- Upgrading illuminate/pipeline (v8.54.0 => v8.55.0)
- Upgrading illuminate/support (v8.54.0 => v8.55.0)
- Upgrading illuminate/testing (v8.54.0 => v8.55.0)
- Upgrading league/flysystem (1.1.4 => 1.1.5)
=> Composer update with 14 changes 2021-08-18

update/composer.lock
- Upgrading laravel-zero/foundation (v8.49.2 => v8.55.0)
- Upgrading nesbot/carbon (2.51.1 => 2.52.0)
=> Composer update with 2 changes 2021-08-21

update/composer.lock
- Upgrading illuminate/bus (v8.55.0 => v8.56.0)
- Upgrading illuminate/cache (v8.55.0 => v8.56.0)
- Upgrading illuminate/collections (v8.55.0 => v8.56.0)
- Upgrading illuminate/config (v8.55.0 => v8.56.0)
- Upgrading illuminate/console (v8.55.0 => v8.56.0)
- Upgrading illuminate/container (v8.55.0 => v8.56.0)
- Upgrading illuminate/contracts (v8.55.0 => v8.56.0)
- Upgrading illuminate/events (v8.55.0 => v8.56.0)
- Upgrading illuminate/filesystem (v8.55.0 => v8.56.0)
- Upgrading illuminate/macroable (v8.55.0 => v8.56.0)
- Upgrading illuminate/pipeline (v8.55.0 => v8.56.0)
- Upgrading illuminate/support (v8.55.0 => v8.56.0)
- Upgrading illuminate/testing (v8.55.0 => v8.56.0)
=> Composer update with 13 changes 2021-08-25

update/composer.lock
- Upgrading graham-campbell/result-type (v1.0.1 => v1.0.2)
- Upgrading phpoption/phpoption (1.7.5 => 1.8.0)
=> Composer update with 2 changes 2021-08-29

update/composer.lock
- Upgrading filp/whoops (2.14.0 => 2.14.1)
- Upgrading php-http/message (1.11.2 => 1.12.0)
=> Composer update with 2 changes 2021-08-30

update/composer.lock
- Upgrading symfony/cache (v5.3.4 => v5.3.7)
- Upgrading symfony/console (v5.3.6 => v5.3.7)
- Upgrading symfony/error-handler (v5.3.4 => v5.3.7)
- Upgrading symfony/finder (v5.3.4 => v5.3.7)
- Upgrading symfony/options-resolver (v5.3.4 => v5.3.7)
- Upgrading symfony/process (v5.3.4 => v5.3.7)
- Upgrading symfony/string (v5.3.3 => v5.3.7)
- Upgrading symfony/translation (v5.3.4 => v5.3.7)
- Upgrading symfony/var-dumper (v5.3.6 => v5.3.7)
- Upgrading symfony/var-exporter (v5.3.4 => v5.3.7)
=> Composer update with 10 changes 2021-08-31

update/app/Commands/UpdateCommand.php, update/app/Providers/AppServiceProvider.php, update/composer.lock
- Upgrading illuminate/bus (v8.58.0 => v8.61.0)
- Upgrading illuminate/cache (v8.58.0 => v8.61.0)
- Upgrading illuminate/collections (v8.58.0 => v8.61.0)
- Upgrading illuminate/config (v8.58.0 => v8.61.0)
- Upgrading illuminate/console (v8.58.0 => v8.61.0)
- Upgrading illuminate/container (v8.58.0 => v8.61.0)
- Upgrading illuminate/contracts (v8.58.0 => v8.61.0)
- Upgrading illuminate/events (v8.58.0 => v8.61.0)
- Upgrading illuminate/filesystem (v8.58.0 => v8.61.0)
- Upgrading illuminate/macroable (v8.58.0 => v8.61.0)
- Upgrading illuminate/pipeline (v8.58.0 => v8.61.0)
- Upgrading illuminate/support (v8.58.0 => v8.61.0)
- Upgrading illuminate/testing (v8.58.0 => v8.61.0)
- Upgrading mockery/mockery (1.4.3 => 1.4.4)
- Upgrading nesbot/carbon (2.52.0 => 2.53.1)
- Upgrading …
=> Composer update with 19 changes 2021-09-19

update/composer.lock
- Upgrading filp/whoops (2.14.1 => 2.14.3)
=> Composer update with 1 changes 2021-09-20

update/composer.lock
- Upgrading nikic/php-parser (v4.12.0 => v4.13.0)
- Upgrading nunomaduro/collision (v5.9.0 => v5.10.0)
=> Composer update with 2 changes 2021-09-21

update/composer.lock
- Upgrading laravel-zero/foundation (v8.55.0 => v8.61.0)
=> Composer update with 1 changes 2021-09-22

update/composer.lock
- Upgrading ramsey/uuid (4.2.1 => 4.2.2)
=> Composer update with 1 changes 2021-09-25

update/composer.lock
- Upgrading league/mime-type-detection (1.7.0 => 1.8.0)
- Upgrading phpunit/phpunit (9.5.9 => 9.5.10)
=> Composer update with 2 changes 2021-09-26

update/composer.lock
- Upgrading ramsey/uuid (4.2.2 => 4.2.3)
=> Composer update with 1 changes 2021-09-27

update/composer.lock
- Upgrading illuminate/bus (v8.61.0 => v8.62.0)
- Upgrading illuminate/cache (v8.61.0 => v8.62.0)
- Upgrading illuminate/collections (v8.61.0 => v8.62.0)
- Upgrading illuminate/config (v8.61.0 => v8.62.0)
- Upgrading illuminate/console (v8.61.0 => v8.62.0)
- Upgrading illuminate/container (v8.61.0 => v8.62.0)
- Upgrading illuminate/contracts (v8.61.0 => v8.62.0)
- Upgrading illuminate/events (v8.61.0 => v8.62.0)
- Upgrading illuminate/filesystem (v8.61.0 => v8.62.0)
- Upgrading illuminate/macroable (v8.61.0 => v8.62.0)
- Upgrading illuminate/pipeline (v8.61.0 => v8.62.0)
- Upgrading illuminate/support (v8.61.0 => v8.62.0)
- Upgrading illuminate/testing (v8.61.0 => v8.62.0)
- Upgrading symfony/cache (v5.3.7 => v5.3.8)
- Upgrading symfony/translation (v5.3.7 => v5.3.9)
- Upgrading …
=> Composer update with 17 changes 2021-09-29

update/composer.lock
- Upgrading laravel-zero/foundation (v8.61.0 => v8.62.0)
=> Composer update with 1 changes 2021-10-02

update/composer.lock
- Upgrading phpdocumentor/type-resolver (1.5.0 => 1.5.1)
- Upgrading vlucas/phpdotenv (v5.3.0 => v5.3.1)
=> Composer update with 2 changes 2021-10-03

update/composer.lock
- Upgrading filp/whoops (2.14.3 => 2.14.4)
=> Composer update with 1 changes 2021-10-04

update/composer.lock
- Upgrading illuminate/bus (v8.62.0 => v8.63.0)
- Upgrading illuminate/collections (v8.62.0 => v8.63.0)
- Upgrading illuminate/config (v8.62.0 => v8.63.0)
- Upgrading illuminate/console (v8.62.0 => v8.63.0)
- Upgrading illuminate/container (v8.62.0 => v8.63.0)
- Upgrading illuminate/contracts (v8.62.0 => v8.63.0)
- Upgrading illuminate/events (v8.62.0 => v8.63.0)
- Upgrading illuminate/filesystem (v8.62.0 => v8.63.0)
- Upgrading illuminate/pipeline (v8.62.0 => v8.63.0)
- Upgrading illuminate/support (v8.62.0 => v8.63.0)
- Upgrading illuminate/testing (v8.62.0 => v8.63.0)
=> Composer update with 11 changes 2021-10-06

update/composer.lock
- Upgrading symfony/cache (v5.3.8 => v5.3.10)
- Upgrading symfony/console (v5.3.7 => v5.3.10)
- Upgrading symfony/string (v5.3.7 => v5.3.10)
- Upgrading symfony/translation (v5.3.9 => v5.3.10)
- Upgrading symfony/var-dumper (v5.3.8 => v5.3.10)
=> Composer update with 5 changes 2021-10-30

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.7 => 9.2.8)
=> Composer update with 1 changes 2021-10-31

update/composer.lock
- Upgrading nesbot/carbon (2.53.1 => 2.54.0)
- Upgrading nikic/php-parser (v4.13.0 => v4.13.1)
- Upgrading php-http/cache-plugin (1.7.2 => 1.7.3)
=> Composer update with 3 changes 2021-11-04

update/composer.lock
- Upgrading psr/container (1.1.1 => 1.1.2)
=> Composer update with 1 changes 2021-11-06

update/composer.lock
- Upgrading illuminate/bus (v8.69.0 => v8.70.2)
- Upgrading illuminate/cache (v8.69.0 => v8.70.2)
- Upgrading illuminate/collections (v8.69.0 => v8.70.2)
- Upgrading illuminate/config (v8.69.0 => v8.70.2)
- Upgrading illuminate/console (v8.69.0 => v8.70.2)
- Upgrading illuminate/container (v8.69.0 => v8.70.2)
- Upgrading illuminate/contracts (v8.69.0 => v8.70.2)
- Upgrading illuminate/events (v8.69.0 => v8.70.2)
- Upgrading illuminate/filesystem (v8.69.0 => v8.70.2)
- Upgrading illuminate/macroable (v8.69.0 => v8.70.2)
- Upgrading illuminate/pipeline (v8.69.0 => v8.70.2)
- Upgrading illuminate/support (v8.69.0 => v8.70.2)
- Upgrading illuminate/testing (v8.69.0 => v8.70.2)
- Upgrading vlucas/phpdotenv (v5.3.1 => v5.4.0)
=> Composer update with 14 changes 2021-11-10

update/composer.lock
- Upgrading sebastian/exporter (4.0.3 => 4.0.4)
=> Composer update with 1 changes 2021-11-12

update/composer.lock
- Upgrading illuminate/bus (v8.70.2 => v8.71.0)
- Upgrading illuminate/cache (v8.70.2 => v8.71.0)
- Upgrading illuminate/collections (v8.70.2 => v8.71.0)
- Upgrading illuminate/config (v8.70.2 => v8.71.0)
- Upgrading illuminate/console (v8.70.2 => v8.71.0)
- Upgrading illuminate/container (v8.70.2 => v8.71.0)
- Upgrading illuminate/contracts (v8.70.2 => v8.71.0)
- Upgrading illuminate/events (v8.70.2 => v8.71.0)
- Upgrading illuminate/filesystem (v8.70.2 => v8.71.0)
- Upgrading illuminate/macroable (v8.70.2 => v8.71.0)
- Upgrading illuminate/pipeline (v8.70.2 => v8.71.0)
- Upgrading illuminate/support (v8.70.2 => v8.71.0)
- Upgrading illuminate/testing (v8.70.2 => v8.71.0)
- Upgrading laravel-zero/foundation (v8.62.0 => v8.70.2)
=> Composer update with 14 changes 2021-11-17

update/composer.lock
- Upgrading illuminate/bus (v8.71.0 => v8.72.0)
- Upgrading illuminate/cache (v8.71.0 => v8.72.0)
- Upgrading illuminate/collections (v8.71.0 => v8.72.0)
- Upgrading illuminate/config (v8.71.0 => v8.72.0)
- Upgrading illuminate/console (v8.71.0 => v8.72.0)
- Upgrading illuminate/container (v8.71.0 => v8.72.0)
- Upgrading illuminate/contracts (v8.71.0 => v8.72.0)
- Upgrading illuminate/events (v8.71.0 => v8.72.0)
- Upgrading illuminate/filesystem (v8.71.0 => v8.72.0)
- Upgrading illuminate/macroable (v8.71.0 => v8.72.0)
- Upgrading illuminate/pipeline (v8.71.0 => v8.72.0)
- Upgrading illuminate/support (v8.71.0 => v8.72.0)
- Upgrading illuminate/testing (v8.71.0 => v8.72.0)
=> Composer update with 13 changes 2021-11-18

update/composer.lock
- Upgrading illuminate/bus (v8.72.0 => v8.73.0)
- Upgrading illuminate/cache (v8.72.0 => v8.73.0)
- Upgrading illuminate/collections (v8.72.0 => v8.73.0)
- Upgrading illuminate/config (v8.72.0 => v8.73.0)
- Upgrading illuminate/console (v8.72.0 => v8.73.0)
- Upgrading illuminate/container (v8.72.0 => v8.73.0)
- Upgrading illuminate/contracts (v8.72.0 => v8.73.0)
- Upgrading illuminate/events (v8.72.0 => v8.73.0)
- Upgrading illuminate/filesystem (v8.72.0 => v8.73.0)
- Upgrading illuminate/macroable (v8.72.0 => v8.73.0)
- Upgrading illuminate/pipeline (v8.72.0 => v8.73.0)
- Upgrading illuminate/support (v8.72.0 => v8.73.0)
- Upgrading illuminate/testing (v8.72.0 => v8.73.0)
- Upgrading laravel-zero/foundation (v8.70.2 => v8.73.0)
- Upgrading phpunit/php-code-coverage (9.2.8 => 9.2.9)
=> Composer update with 15 changes 2021-11-20

update/composer.lock
- Upgrading graham-campbell/bounded-cache (v1.1.2 => v1.1.3)
- Upgrading graham-campbell/github (v10.3.0 => v10.3.1)
- Upgrading graham-campbell/manager (v4.6.0 => v4.6.1)
- Upgrading graham-campbell/result-type (v1.0.3 => v1.0.4)
- Upgrading league/flysystem (1.1.5 => 1.1.6)
- Upgrading league/mime-type-detection (1.8.0 => 1.9.0)
=> Composer update with 6 changes 2021-11-22

update/composer.lock
- Upgrading symfony/cache (v5.3.10 => v5.3.11)
- Upgrading symfony/cache-contracts (v2.4.0 => v2.5.0)
- Upgrading symfony/console (v5.3.10 => v5.3.11)
- Upgrading symfony/deprecation-contracts (v2.4.0 => v2.5.0)
- Upgrading symfony/error-handler (v5.3.7 => v5.3.11)
- Upgrading symfony/process (v5.3.7 => v5.3.11)
- Upgrading symfony/service-contracts (v2.4.0 => v2.5.0)
- Upgrading symfony/translation (v5.3.10 => v5.3.11)
- Upgrading symfony/translation-contracts (v2.4.0 => v2.5.0)
- Upgrading symfony/var-dumper (v5.3.10 => v5.3.11)
- Upgrading symfony/var-exporter (v5.3.8 => v5.3.11)
=> Composer update with 11 changes 2021-11-23

update/composer.lock
- Upgrading illuminate/bus (v8.73.1 => v8.73.2)
- Upgrading illuminate/cache (v8.73.1 => v8.73.2)
- Upgrading illuminate/collections (v8.73.1 => v8.73.2)
- Upgrading illuminate/config (v8.73.1 => v8.73.2)
- Upgrading illuminate/console (v8.73.1 => v8.73.2)
- Upgrading illuminate/container (v8.73.1 => v8.73.2)
- Upgrading illuminate/contracts (v8.73.1 => v8.73.2)
- Upgrading illuminate/events (v8.73.1 => v8.73.2)
- Upgrading illuminate/filesystem (v8.73.1 => v8.73.2)
- Upgrading illuminate/macroable (v8.73.1 => v8.73.2)
- Upgrading illuminate/pipeline (v8.73.1 => v8.73.2)
- Upgrading illuminate/support (v8.73.1 => v8.73.2)
- Upgrading illuminate/testing (v8.73.1 => v8.73.2)
=> Composer update with 13 changes 2021-11-24

update/composer.lock
- Upgrading symfony/cache (v5.3.11 => v5.3.12)
- Upgrading symfony/process (v5.3.11 => v5.3.12)
=> Composer update with 2 changes 2021-11-25

update/composer.lock
- Upgrading league/flysystem (1.1.6 => 1.1.7)
=> Composer update with 1 changes 2021-11-26

update/composer.lock
- Upgrading php-http/client-common (2.4.0 => 2.5.0)
=> Composer update with 1 changes 2021-11-27

update/composer.lock
- Upgrading league/flysystem (1.1.7 => 1.1.8)
=> Composer update with 1 changes 2021-11-29

update/composer.lock
- Upgrading illuminate/bus (v8.73.2 => v8.74.0)
- Upgrading illuminate/cache (v8.73.2 => v8.74.0)
- Upgrading illuminate/collections (v8.73.2 => v8.74.0)
- Upgrading illuminate/config (v8.73.2 => v8.74.0)
- Upgrading illuminate/console (v8.73.2 => v8.74.0)
- Upgrading illuminate/container (v8.73.2 => v8.74.0)
- Upgrading illuminate/contracts (v8.73.2 => v8.74.0)
- Upgrading illuminate/events (v8.73.2 => v8.74.0)
- Upgrading illuminate/filesystem (v8.73.2 => v8.74.0)
- Upgrading illuminate/macroable (v8.73.2 => v8.74.0)
- Upgrading illuminate/pipeline (v8.73.2 => v8.74.0)
- Upgrading illuminate/support (v8.73.2 => v8.74.0)
- Upgrading illuminate/testing (v8.73.2 => v8.74.0)
- Upgrading nikic/php-parser (v4.13.1 => v4.13.2)
- Upgrading php-http/cache-plugin (1.7.3 => 1.7.4)
- Upgrading …
=> Composer update with 16 changes 2021-12-01

update/composer.lock
- Upgrading phpunit/php-file-iterator (3.0.5 => 3.0.6)
=> Composer update with 1 changes 2021-12-03

update/composer.lock
- Upgrading nesbot/carbon (2.54.0 => 2.55.2)
- Upgrading symfony/translation (v5.4.0 => v6.0.0)
- Upgrading symfony/translation-contracts (v2.5.0 => v3.0.0)
=> Composer update with 3 changes 2021-12-04

update/composer.lock
- Upgrading phpoption/phpoption (1.8.0 => 1.8.1)
=> Composer update with 1 changes 2021-12-05

update/composer.lock
- Upgrading laravel-zero/foundation (v8.73.0 => v8.74.0)
- Upgrading phpunit/php-code-coverage (9.2.9 => 9.2.10)
=> Composer update with 2 changes 2021-12-06

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.4.0 => 7.4.1)
=> Composer update with 1 changes 2021-12-07

update/composer.lock
- Upgrading illuminate/bus (v8.74.0 => v8.75.0)
- Upgrading illuminate/cache (v8.74.0 => v8.75.0)
- Upgrading illuminate/collections (v8.74.0 => v8.75.0)
- Upgrading illuminate/config (v8.74.0 => v8.75.0)
- Upgrading illuminate/console (v8.74.0 => v8.75.0)
- Upgrading illuminate/container (v8.74.0 => v8.75.0)
- Upgrading illuminate/contracts (v8.74.0 => v8.75.0)
- Upgrading illuminate/events (v8.74.0 => v8.75.0)
- Upgrading illuminate/filesystem (v8.74.0 => v8.75.0)
- Upgrading illuminate/macroable (v8.74.0 => v8.75.0)
- Upgrading illuminate/pipeline (v8.74.0 => v8.75.0)
- Upgrading illuminate/support (v8.74.0 => v8.75.0)
- Upgrading illuminate/testing (v8.74.0 => v8.75.0)
=> Composer update with 13 changes 2021-12-08

update/composer.lock
- Upgrading phpspec/prophecy (1.14.0 => v1.15.0)
=> Composer update with 1 changes 2021-12-09

update/composer.lock
- Upgrading league/flysystem (1.1.8 => 1.1.9)
- Upgrading symfony/console (v5.4.0 => v5.4.1)
- Upgrading symfony/error-handler (v5.4.0 => v5.4.1)
- Upgrading symfony/string (v6.0.0 => v6.0.1)
- Upgrading symfony/translation (v6.0.0 => v6.0.1)
- Upgrading symfony/var-dumper (v5.4.0 => v5.4.1)
=> Composer update with 6 changes 2021-12-10

update/composer.lock
- Upgrading jolicode/jolinotif (v2.3.0 => v2.4.0)
- Upgrading vlucas/phpdotenv (v5.4.0 => v5.4.1)
=> Composer update with 2 changes 2021-12-13

update/composer.lock
- Upgrading illuminate/bus (v8.75.0 => v8.76.1)
- Upgrading illuminate/cache (v8.75.0 => v8.76.1)
- Upgrading illuminate/collections (v8.75.0 => v8.76.1)
- Upgrading illuminate/config (v8.75.0 => v8.76.1)
- Upgrading illuminate/console (v8.75.0 => v8.76.1)
- Upgrading illuminate/container (v8.75.0 => v8.76.1)
- Upgrading illuminate/contracts (v8.75.0 => v8.76.1)
- Upgrading illuminate/events (v8.75.0 => v8.76.1)
- Upgrading illuminate/filesystem (v8.75.0 => v8.76.1)
- Upgrading illuminate/macroable (v8.75.0 => v8.76.1)
- Upgrading illuminate/pipeline (v8.75.0 => v8.76.1)
- Upgrading illuminate/support (v8.75.0 => v8.76.1)
- Upgrading illuminate/testing (v8.75.0 => v8.76.1)
=> Composer update with 13 changes 2021-12-15

update/composer.lock
- Upgrading illuminate/bus (v8.76.1 => v8.76.2)
- Upgrading illuminate/cache (v8.76.1 => v8.76.2)
- Upgrading illuminate/collections (v8.76.1 => v8.76.2)
- Upgrading illuminate/config (v8.76.1 => v8.76.2)
- Upgrading illuminate/console (v8.76.1 => v8.76.2)
- Upgrading illuminate/container (v8.76.1 => v8.76.2)
- Upgrading illuminate/contracts (v8.76.1 => v8.76.2)
- Upgrading illuminate/events (v8.76.1 => v8.76.2)
- Upgrading illuminate/filesystem (v8.76.1 => v8.76.2)
- Upgrading illuminate/macroable (v8.76.1 => v8.76.2)
- Upgrading illuminate/pipeline (v8.76.1 => v8.76.2)
- Upgrading illuminate/support (v8.76.1 => v8.76.2)
- Upgrading illuminate/testing (v8.76.1 => v8.76.2)
=> Composer update with 13 changes 2021-12-16

update/composer.lock
- Upgrading laravel-zero/foundation (v8.74.0 => v8.76.1)
=> Composer update with 1 changes 2021-12-21

update/composer.lock
- Upgrading phpunit/phpunit (9.5.10 => 9.5.11)
=> Composer update with 1 changes 2021-12-26

update/composer.lock
- Upgrading symfony/cache (v5.4.0 => v5.4.2)
- Upgrading symfony/console (v5.4.1 => v5.4.2)
- Upgrading symfony/error-handler (v5.4.1 => v5.4.2)
- Upgrading symfony/finder (v5.4.0 => v5.4.2)
- Upgrading symfony/process (v5.4.0 => v5.4.2)
- Upgrading symfony/string (v6.0.1 => v6.0.2)
- Upgrading symfony/translation (v6.0.1 => v6.0.2)
- Upgrading symfony/var-dumper (v5.4.1 => v5.4.2)
=> Composer update with 8 changes 2021-12-30

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.1.0 => v3.2.1)
- Upgrading illuminate/bus (v8.77.1 => v8.78.0)
- Upgrading illuminate/cache (v8.77.1 => v8.78.0)
- Upgrading illuminate/collections (v8.77.1 => v8.78.0)
- Upgrading illuminate/config (v8.77.1 => v8.78.0)
- Upgrading illuminate/console (v8.77.1 => v8.78.0)
- Upgrading illuminate/container (v8.77.1 => v8.78.0)
- Upgrading illuminate/contracts (v8.77.1 => v8.78.0)
- Upgrading illuminate/events (v8.77.1 => v8.78.0)
- Upgrading illuminate/filesystem (v8.77.1 => v8.78.0)
- Upgrading illuminate/macroable (v8.77.1 => v8.78.0)
- Upgrading illuminate/pipeline (v8.77.1 => v8.78.0)
- Upgrading illuminate/support (v8.77.1 => v8.78.0)
- Upgrading illuminate/testing (v8.77.1 => v8.78.0)
- Upgrading phpdocumentor/type-resolver (1.5.1 => 1.6.0)
=> Composer update with 15 changes 2022-01-05

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.2.1 => v3.2.2)
=> Composer update with 1 changes 2022-01-05

update/composer.lock
- Upgrading illuminate/bus (v8.78.0 => v8.78.1)
- Upgrading illuminate/cache (v8.78.0 => v8.78.1)
- Upgrading illuminate/collections (v8.78.0 => v8.78.1)
- Upgrading illuminate/config (v8.78.0 => v8.78.1)
- Upgrading illuminate/console (v8.78.0 => v8.78.1)
- Upgrading illuminate/container (v8.78.0 => v8.78.1)
- Upgrading illuminate/contracts (v8.78.0 => v8.78.1)
- Upgrading illuminate/events (v8.78.0 => v8.78.1)
- Upgrading illuminate/filesystem (v8.78.0 => v8.78.1)
- Upgrading illuminate/macroable (v8.78.0 => v8.78.1)
- Upgrading illuminate/pipeline (v8.78.0 => v8.78.1)
- Upgrading illuminate/support (v8.78.0 => v8.78.1)
- Upgrading illuminate/testing (v8.78.0 => v8.78.1)
- Upgrading laravel-zero/foundation (v8.76.1 => v8.78.0)
- Upgrading symfony/polyfill-ctype (v1.23.0 => v1.24.0)
- …
=> Composer update with 21 changes 2022-01-06

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.2.2 => v3.2.3)
- Upgrading filp/whoops (2.14.4 => 2.14.5)
=> Composer update with 2 changes 2022-01-07

update/composer.lock
- Upgrading nunomaduro/collision (v5.10.0 => v5.11.0)
=> Composer update with 1 changes 2022-01-11

update/composer.lock
- Upgrading illuminate/bus (v8.78.1 => v8.79.0)
- Upgrading illuminate/cache (v8.78.1 => v8.79.0)
- Upgrading illuminate/collections (v8.78.1 => v8.79.0)
- Upgrading illuminate/config (v8.78.1 => v8.79.0)
- Upgrading illuminate/console (v8.78.1 => v8.79.0)
- Upgrading illuminate/container (v8.78.1 => v8.79.0)
- Upgrading illuminate/contracts (v8.78.1 => v8.79.0)
- Upgrading illuminate/events (v8.78.1 => v8.79.0)
- Upgrading illuminate/filesystem (v8.78.1 => v8.79.0)
- Upgrading illuminate/macroable (v8.78.1 => v8.79.0)
- Upgrading illuminate/pipeline (v8.78.1 => v8.79.0)
- Upgrading illuminate/support (v8.78.1 => v8.79.0)
- Upgrading illuminate/testing (v8.78.1 => v8.79.0)
=> Composer update with 13 changes 2022-01-13

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.2.3 => v3.2.4)
=> Composer update with 1 changes 2022-01-13

update/composer.lock
- Upgrading nunomaduro/laravel-console-summary (v1.7.1 => v1.8.0)
- Upgrading nunomaduro/laravel-console-task (v1.6.1 => v1.7.0)
- Upgrading nunomaduro/laravel-desktop-notifier (v2.5.1 => v2.6.0)
=> Composer update with 3 changes 2022-01-14

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.2.4 => v3.3.0)
=> Composer update with 1 changes 2022-01-15

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.3.0 => v3.3.1)
- Upgrading illuminate/bus (v8.79.0 => v8.80.0)
- Upgrading illuminate/cache (v8.79.0 => v8.80.0)
- Upgrading illuminate/collections (v8.79.0 => v8.80.0)
- Upgrading illuminate/config (v8.79.0 => v8.80.0)
- Upgrading illuminate/console (v8.79.0 => v8.80.0)
- Upgrading illuminate/container (v8.79.0 => v8.80.0)
- Upgrading illuminate/contracts (v8.79.0 => v8.80.0)
- Upgrading illuminate/events (v8.79.0 => v8.80.0)
- Upgrading illuminate/filesystem (v8.79.0 => v8.80.0)
- Upgrading illuminate/macroable (v8.79.0 => v8.80.0)
- Upgrading illuminate/pipeline (v8.79.0 => v8.80.0)
- Upgrading illuminate/support (v8.79.0 => v8.80.0)
- Upgrading illuminate/testing (v8.79.0 => v8.80.0)
- Upgrading php-http/cache-plugin (1.7.4 => 1.7.5)
=> Composer update with 15 changes 2022-01-19

update/composer.lock
- Upgrading mockery/mockery (1.4.4 => 1.5.0)
=> Composer update with 1 changes 2022-01-21

update/composer.lock
- Upgrading phpunit/phpunit (9.5.11 => 9.5.12)
=> Composer update with 1 changes 2022-01-22

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.1.0 => v3.3.1)
- Upgrading filp/whoops (2.14.4 => 2.14.5)
- Upgrading illuminate/bus (v8.76.2 => v8.80.0)
- Upgrading illuminate/cache (v8.76.2 => v8.80.0)
- Upgrading illuminate/collections (v8.76.2 => v8.80.0)
- Upgrading illuminate/config (v8.76.2 => v8.80.0)
- Upgrading illuminate/console (v8.76.2 => v8.80.0)
- Upgrading illuminate/container (v8.76.2 => v8.80.0)
- Upgrading illuminate/contracts (v8.76.2 => v8.80.0)
- Upgrading illuminate/events (v8.76.2 => v8.80.0)
- Upgrading illuminate/filesystem (v8.76.2 => v8.80.0)
- Upgrading illuminate/macroable (v8.76.2 => v8.80.0)
- Upgrading illuminate/pipeline (v8.76.2 => v8.80.0)
- Upgrading illuminate/support (v8.76.2 => v8.80.0)
- Upgrading illuminate/testing (v8.76.2 => v8.80.0)
- Upgrading …
=> Composer update with 39 changes 2022-01-22

update/app/Commands/UpdateCommand.php, update/app/Providers/AppServiceProvider.php, update/composer.lock
- Upgrading brick/math (0.9.2 => 0.9.3)
- Upgrading doctrine/inflector (2.0.3 => 2.0.4)
- Upgrading dragonmantank/cron-expression (v3.1.0 => v3.3.1)
- Upgrading filp/whoops (2.13.0 => 2.14.5)
- Upgrading graham-campbell/bounded-cache (v1.1.0 => v1.1.3)
- Upgrading graham-campbell/github (v10.3.0 => v10.3.1)
- Upgrading graham-campbell/manager (v4.6.0 => v4.6.1)
- Upgrading graham-campbell/result-type (v1.0.1 => v1.0.4)
- Upgrading guzzlehttp/guzzle (7.3.0 => 7.4.1)
- Upgrading guzzlehttp/promises (1.4.1 => 1.5.1)
- Upgrading guzzlehttp/psr7 (1.8.2 => 2.1.0)
- Upgrading http-interop/http-factory-guzzle (1.0.0 => 1.2.0)
- Upgrading illuminate/bus (v8.48.1 => v8.80.0)
- Upgrading illuminate/cache (v8.48.1 => v8.80.0)
- Upgrading illuminate/collections (v8.48.1 => v8.80.0)
- Upgrading …
=> Composer update with 76 changes 2022-01-22

update/composer.lock
- Upgrading graham-campbell/github (v10.3.1 => v10.5.0)
- Upgrading graham-campbell/manager (v4.6.1 => v4.7.0)
- Upgrading knplabs/github-api (v3.3.0 => v3.5.0)
- Upgrading psr/cache (1.0.1 => 3.0.0)
- Upgrading symfony/cache (v5.4.2 => v6.0.2)
- Upgrading symfony/cache-contracts (v2.5.0 => v3.0.0)
- Upgrading symfony/deprecation-contracts (v2.5.0 => v3.0.0)
- Downgrading symfony/service-contracts (v2.5.0 => v2.4.1)
=> Composer update with 8 changes 2022-01-24

update/composer.lock
- Upgrading nesbot/carbon (2.55.2 => 2.56.0)
- Upgrading phpunit/phpunit (9.5.12 => 9.5.13)
- Upgrading voku/portable-ascii (1.5.6 => 1.6.1)
=> Composer update with 3 changes 2022-01-25

update/composer.lock
- Upgrading laravel-zero/foundation (v8.78.0 => v8.81.0)
=> Composer update with 1 changes 2022-01-27

update/composer.lock
- Upgrading symfony/cache (v6.0.2 => v6.0.3)
- Upgrading symfony/console (v5.4.2 => v5.4.3)
- Upgrading symfony/error-handler (v5.4.2 => v5.4.3)
- Upgrading symfony/finder (v5.4.2 => v5.4.3)
- Upgrading symfony/options-resolver (v6.0.0 => v6.0.3)
- Upgrading symfony/process (v5.4.2 => v5.4.3)
- Upgrading symfony/string (v6.0.2 => v6.0.3)
- Upgrading symfony/translation (v6.0.2 => v6.0.3)
- Upgrading symfony/var-dumper (v5.4.2 => v5.4.3)
- Upgrading symfony/var-exporter (v6.0.0 => v6.0.3)
=> Composer update with 10 changes 2022-01-29

update/composer.lock
- Upgrading phar-io/version (3.1.0 => 3.1.1)
=> Composer update with 1 changes 2022-02-08

update/composer.lock
- Upgrading sebastian/global-state (5.0.3 => 5.0.4)
=> Composer update with 1 changes 2022-02-11

update/composer.lock
- Upgrading php-http/message (1.12.0 => 1.13.0)
=> Composer update with 1 changes 2022-02-12

update/composer.lock
- Upgrading sebastian/global-state (5.0.4 => 5.0.5)
=> Composer update with 1 changes 2022-02-15

update/composer.lock
- Upgrading illuminate/bus (v8.83.0 => v8.83.1)
- Upgrading illuminate/cache (v8.83.0 => v8.83.1)
- Upgrading illuminate/collections (v8.83.0 => v8.83.1)
- Upgrading illuminate/config (v8.83.0 => v8.83.1)
- Upgrading illuminate/console (v8.83.0 => v8.83.1)
- Upgrading illuminate/container (v8.83.0 => v8.83.1)
- Upgrading illuminate/contracts (v8.83.0 => v8.83.1)
- Upgrading illuminate/events (v8.83.0 => v8.83.1)
- Upgrading illuminate/filesystem (v8.83.0 => v8.83.1)
- Upgrading illuminate/macroable (v8.83.0 => v8.83.1)
- Upgrading illuminate/pipeline (v8.83.0 => v8.83.1)
- Upgrading illuminate/support (v8.83.0 => v8.83.1)
- Upgrading illuminate/testing (v8.83.0 => v8.83.1)
=> Composer update with 13 changes 2022-02-16

update/composer.lock
- Upgrading laravel-zero/framework (v8.9.1 => v8.10.0)
- Upgrading nesbot/carbon (2.56.0 => 2.57.0)
=> Composer update with 2 changes 2022-02-18

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.10 => 9.2.11)
- Upgrading phpunit/phpunit (9.5.13 => 9.5.14)
=> Composer update with 2 changes 2022-02-19

update/composer.lock
- Upgrading knplabs/github-api (v3.5.0 => v3.5.1)
=> Composer update with 1 changes 2022-02-20

update/composer.lock
- Upgrading phar-io/version (3.1.1 => 3.2.1)
=> Composer update with 1 changes 2022-02-21

update/composer.lock
- Upgrading clue/stream-filter (v1.5.0 => v1.6.0)
- Upgrading php-http/httplug (2.2.0 => 2.3.0)
=> Composer update with 2 changes 2022-02-22

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.11 => 9.2.13)
- Upgrading phpunit/phpunit (9.5.14 => 9.5.16)
=> Composer update with 2 changes 2022-02-24

update/composer.lock
- Upgrading league/flysystem (3.0.9 => 3.0.10)
=> Composer update with 1 changes 2022-02-26

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.13 => 9.2.14)
- Upgrading symfony/cache (v6.0.3 => v6.0.5)
- Upgrading symfony/console (v6.0.3 => v6.0.5)
- Upgrading symfony/process (v6.0.3 => v6.0.5)
- Upgrading symfony/translation (v6.0.3 => v6.0.5)
- Upgrading symfony/var-dumper (v6.0.3 => v6.0.5)
=> Composer update with 6 changes 2022-03-01

update/composer.lock
- Upgrading doctrine/instantiator (1.4.0 => 1.4.1)
- Upgrading illuminate/bus (v9.3.0 => v9.3.1)
- Upgrading illuminate/cache (v9.3.0 => v9.3.1)
- Upgrading illuminate/collections (v9.3.0 => v9.3.1)
- Upgrading illuminate/conditionable (v9.3.0 => v9.3.1)
- Upgrading illuminate/config (v9.2.0 => v9.3.1)
- Upgrading illuminate/console (v9.3.0 => v9.3.1)
- Upgrading illuminate/container (v9.3.0 => v9.3.1)
- Upgrading illuminate/contracts (v9.3.0 => v9.3.1)
- Upgrading illuminate/events (v9.3.0 => v9.3.1)
- Upgrading illuminate/filesystem (v9.3.0 => v9.3.1)
- Upgrading illuminate/pipeline (v9.3.0 => v9.3.1)
- Upgrading illuminate/support (v9.3.0 => v9.3.1)
- Upgrading illuminate/testing (v9.3.0 => v9.3.1)
- Upgrading laravel-zero/foundation (v9.2.0 => v9.3.0)
- Upgrading myclabs/deep-copy …
=> Composer update with 16 changes 2022-03-04

update/composer.lock
- Upgrading league/flysystem (3.0.10 => 3.0.11)
- Upgrading symfony/polyfill-ctype (v1.24.0 => v1.25.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.24.0 => v1.25.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.24.0 => v1.25.0)
- Upgrading symfony/polyfill-mbstring (v1.24.0 => v1.25.0)
- Upgrading symfony/polyfill-php80 (v1.24.0 => v1.25.0)
- Upgrading symfony/polyfill-php81 (v1.24.0 => v1.25.0)
=> Composer update with 7 changes 2022-03-05

update/composer.lock
- Upgrading phpunit/phpunit (9.5.16 => 9.5.17)
- Upgrading symfony/cache (v6.0.5 => v6.0.6)
- Upgrading symfony/translation (v6.0.5 => v6.0.6)
- Upgrading symfony/var-dumper (v6.0.5 => v6.0.6)
- Upgrading symfony/var-exporter (v6.0.3 => v6.0.6)
=> Composer update with 5 changes 2022-03-06

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.14 => 9.2.15)
=> Composer update with 1 changes 2022-03-08

update/composer.lock
- Upgrading illuminate/bus (v9.3.1 => v9.4.1)
- Upgrading illuminate/cache (v9.3.1 => v9.4.1)
- Upgrading illuminate/collections (v9.3.1 => v9.4.1)
- Upgrading illuminate/conditionable (v9.3.1 => v9.4.1)
- Upgrading illuminate/config (v9.3.1 => v9.4.1)
- Upgrading illuminate/console (v9.3.1 => v9.4.1)
- Upgrading illuminate/container (v9.3.1 => v9.4.1)
- Upgrading illuminate/contracts (v9.3.1 => v9.4.1)
- Upgrading illuminate/events (v9.3.1 => v9.4.1)
- Upgrading illuminate/filesystem (v9.3.1 => v9.4.1)
- Upgrading illuminate/macroable (v9.3.0 => v9.4.1)
- Upgrading illuminate/pipeline (v9.3.1 => v9.4.1)
- Upgrading illuminate/support (v9.3.1 => v9.4.1)
- Upgrading illuminate/testing (v9.3.1 => v9.4.1)
- Upgrading phpunit/phpunit (9.5.17 => 9.5.18)
- Upgrading voku/portable-ascii (2.0.0 …
=> Composer update with 16 changes 2022-03-09

update/composer.lock
- Upgrading laravel-zero/foundation (v9.3.0 => v9.4.1)
=> Composer update with 1 changes 2022-03-10

update/composer.lock
- Upgrading league/flysystem (3.0.11 => 3.0.12)
=> Composer update with 1 changes 2022-03-13

update/composer.lock
- Upgrading illuminate/bus (v9.4.1 => v9.5.1)
- Upgrading illuminate/cache (v9.4.1 => v9.5.1)
- Upgrading illuminate/collections (v9.4.1 => v9.5.1)
- Upgrading illuminate/conditionable (v9.4.1 => v9.5.1)
- Upgrading illuminate/config (v9.4.1 => v9.5.1)
- Upgrading illuminate/console (v9.4.1 => v9.5.1)
- Upgrading illuminate/container (v9.4.1 => v9.5.1)
- Upgrading illuminate/contracts (v9.4.1 => v9.5.1)
- Upgrading illuminate/events (v9.4.1 => v9.5.1)
- Upgrading illuminate/filesystem (v9.4.1 => v9.5.1)
- Upgrading illuminate/macroable (v9.4.1 => v9.5.1)
- Upgrading illuminate/pipeline (v9.4.1 => v9.5.1)
- Upgrading illuminate/support (v9.4.1 => v9.5.1)
- Upgrading illuminate/testing (v9.4.1 => v9.5.1)
- Upgrading laravel-zero/foundation (v9.4.1 => v9.5.1)
- Upgrading phpunit/phpunit …
=> Composer update with 17 changes 2022-03-16

update/composer.lock
- Upgrading nunomaduro/termwind (v1.6.0 => v1.6.1)
=> Composer update with 1 changes 2022-03-18

update/composer.lock
- Upgrading nunomaduro/termwind (v1.6.1 => v1.6.2)
=> Composer update with 1 changes 2022-03-19

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.4.1 => 7.4.2)
- Upgrading guzzlehttp/psr7 (2.1.0 => 2.2.1)
=> Composer update with 2 changes 2022-03-22

update/composer.lock
- Upgrading ramsey/uuid (4.2.3 => 4.3.0)
=> Composer update with 1 changes 2022-03-27

update/composer.lock
- Upgrading ramsey/uuid (4.3.0 => 4.3.1)
=> Composer update with 1 changes 2022-03-28

update/composer.lock
- Upgrading nunomaduro/termwind (v1.6.2 => v1.7.0)
=> Composer update with 1 changes 2022-03-31

update/composer.lock
- Upgrading phpunit/phpunit (9.5.19 => 9.5.20)
=> Composer update with 1 changes 2022-04-02

update/composer.lock
- Upgrading league/flysystem (3.0.12 => 3.0.13)
- Upgrading symfony/console (v6.0.5 => v6.0.7)
- Upgrading symfony/error-handler (v6.0.3 => v6.0.7)
- Upgrading symfony/process (v6.0.5 => v6.0.7)
- Upgrading symfony/translation (v6.0.6 => v6.0.7)
- Upgrading symfony/var-exporter (v6.0.6 => v6.0.7)
=> Composer update with 6 changes 2022-04-03

update/composer.lock
- Upgrading sebastian/environment (5.1.3 => 5.1.4)
=> Composer update with 1 changes 2022-04-04

update/composer.lock
- Upgrading league/flysystem (3.0.13 => 3.0.14)
=> Composer update with 1 changes 2022-04-07

update/composer.lock
- Upgrading league/flysystem (3.0.14 => 3.0.15)
=> Composer update with 1 changes 2022-04-09

update/composer.lock
- Upgrading league/flysystem (3.0.15 => 3.0.16)
- Upgrading league/mime-type-detection (1.9.0 => 1.10.0)
=> Composer update with 2 changes 2022-04-12

update/composer.lock
- Upgrading illuminate/bus (v9.7.0 => v9.8.1)
- Upgrading illuminate/cache (v9.7.0 => v9.8.1)
- Upgrading illuminate/collections (v9.7.0 => v9.8.1)
- Upgrading illuminate/conditionable (v9.7.0 => v9.8.1)
- Upgrading illuminate/config (v9.7.0 => v9.8.1)
- Upgrading illuminate/console (v9.7.0 => v9.8.1)
- Upgrading illuminate/container (v9.7.0 => v9.8.1)
- Upgrading illuminate/contracts (v9.7.0 => v9.8.1)
- Upgrading illuminate/events (v9.7.0 => v9.8.1)
- Upgrading illuminate/filesystem (v9.7.0 => v9.8.1)
- Upgrading illuminate/macroable (v9.7.0 => v9.8.1)
- Upgrading illuminate/pipeline (v9.7.0 => v9.8.1)
- Upgrading illuminate/support (v9.7.0 => v9.8.1)
- Upgrading illuminate/testing (v9.7.0 => v9.8.1)
=> Composer update with 14 changes 2022-04-13

update/composer.lock
- Upgrading league/flysystem (3.0.16 => 3.0.17)
=> Composer update with 1 changes 2022-04-15

update/composer.lock
- Upgrading league/mime-type-detection (1.10.0 => 1.11.0)
=> Composer update with 1 changes 2022-04-18

update/composer.lock
- Upgrading illuminate/bus (v9.8.1 => v9.9.0)
- Upgrading illuminate/cache (v9.8.1 => v9.9.0)
- Upgrading illuminate/collections (v9.8.1 => v9.9.0)
- Upgrading illuminate/conditionable (v9.8.1 => v9.9.0)
- Upgrading illuminate/config (v9.8.1 => v9.9.0)
- Upgrading illuminate/console (v9.8.1 => v9.9.0)
- Upgrading illuminate/container (v9.8.1 => v9.9.0)
- Upgrading illuminate/contracts (v9.8.1 => v9.9.0)
- Upgrading illuminate/events (v9.8.1 => v9.9.0)
- Upgrading illuminate/filesystem (v9.8.1 => v9.9.0)
- Upgrading illuminate/macroable (v9.8.1 => v9.9.0)
- Upgrading illuminate/pipeline (v9.8.1 => v9.9.0)
- Upgrading illuminate/support (v9.8.1 => v9.9.0)
- Upgrading illuminate/testing (v9.8.1 => v9.9.0)
=> Composer update with 14 changes 2022-04-20

update/composer.lock
- Upgrading czproject/git-php (v4.0.2 => v4.0.3)
=> Composer update with 1 changes 2022-04-22

update/composer.lock
- Upgrading nunomaduro/termwind (v1.7.0 => v1.8.0)
=> Composer update with 1 changes 2022-04-23

update/composer.lock
- Upgrading league/flysystem (3.0.17 => 3.0.18)
=> Composer update with 1 changes 2022-04-26

update/composer.lock
- Upgrading illuminate/bus (v9.10.0 => v9.10.1)
- Upgrading illuminate/cache (v9.10.0 => v9.10.1)
- Upgrading illuminate/collections (v9.10.0 => v9.10.1)
- Upgrading illuminate/conditionable (v9.10.0 => v9.10.1)
- Upgrading illuminate/config (v9.10.0 => v9.10.1)
- Upgrading illuminate/console (v9.10.0 => v9.10.1)
- Upgrading illuminate/container (v9.10.0 => v9.10.1)
- Upgrading illuminate/contracts (v9.10.0 => v9.10.1)
- Upgrading illuminate/events (v9.10.0 => v9.10.1)
- Upgrading illuminate/filesystem (v9.10.0 => v9.10.1)
- Upgrading illuminate/macroable (v9.10.0 => v9.10.1)
- Upgrading illuminate/pipeline (v9.10.0 => v9.10.1)
- Upgrading illuminate/support (v9.10.0 => v9.10.1)
- Upgrading illuminate/testing (v9.10.0 => v9.10.1)
=> Composer update with 14 changes 2022-04-29

update/composer.lock
- Upgrading nunomaduro/termwind (v1.8.0 => v1.9.0)
=> Composer update with 1 changes 2022-05-03

update/composer.lock
- Upgrading laravel-zero/foundation (v9.10.0 => v9.13.0)
=> Composer update with 1 changes 2022-05-19

update/composer.lock
- Upgrading symfony/cache (v6.0.8 => v6.1.0)
- Upgrading symfony/cache-contracts (v3.0.1 => v3.1.0)
- Upgrading symfony/console (v6.0.8 => v6.1.0)
- Upgrading symfony/deprecation-contracts (v3.0.1 => v3.1.0)
- Upgrading symfony/error-handler (v6.0.8 => v6.1.0)
- Upgrading symfony/finder (v6.0.8 => v6.1.0)
- Upgrading symfony/options-resolver (v6.0.3 => v6.1.0)
- Upgrading symfony/process (v6.0.8 => v6.1.0)
- Upgrading symfony/service-contracts (v3.0.1 => v3.1.0)
- Upgrading symfony/string (v6.0.8 => v6.1.0)
- Upgrading symfony/translation (v6.0.8 => v6.1.0)
- Upgrading symfony/translation-contracts (v3.0.1 => v3.1.0)
- Upgrading symfony/var-dumper (v6.0.8 => v6.1.0)
- Upgrading symfony/var-exporter (v6.0.8 => v6.1.0)
=> Composer update with 14 changes 2022-05-28

update/composer.lock
- Upgrading graham-campbell/bounded-cache (v1.1.3 => v2.0.0)
- Upgrading graham-campbell/github (v10.5.0 => v10.6.0)
- Upgrading knplabs/github-api (v3.5.1 => v3.6.0)
- Upgrading psr/simple-cache (1.0.1 => 3.0.0)
=> Composer update with 4 changes 2022-05-31

update/composer.lock
- Upgrading illuminate/bus (v9.14.1 => v9.15.0)
- Upgrading illuminate/cache (v9.14.1 => v9.15.0)
- Upgrading illuminate/collections (v9.14.1 => v9.15.0)
- Upgrading illuminate/conditionable (v9.14.1 => v9.15.0)
- Upgrading illuminate/config (v9.14.1 => v9.15.0)
- Upgrading illuminate/console (v9.14.1 => v9.15.0)
- Upgrading illuminate/container (v9.14.1 => v9.15.0)
- Upgrading illuminate/contracts (v9.14.1 => v9.15.0)
- Upgrading illuminate/events (v9.14.1 => v9.15.0)
- Upgrading illuminate/filesystem (v9.14.1 => v9.15.0)
- Upgrading illuminate/macroable (v9.14.1 => v9.15.0)
- Upgrading illuminate/pipeline (v9.14.1 => v9.15.0)
- Upgrading illuminate/support (v9.14.1 => v9.15.0)
- Upgrading illuminate/testing (v9.14.1 => v9.15.0)
- Upgrading nikic/php-parser (v4.13.2 => v4.14.0)
=> Composer update with 15 changes 2022-06-01

update/composer.lock
- Upgrading webmozart/assert (1.10.0 => 1.11.0)
=> Composer update with 1 changes 2022-06-04

update/composer.lock
- Upgrading guzzlehttp/psr7 (2.2.1 => 2.2.2)
=> Composer update with 1 changes 2022-06-09

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.4.3 => 7.4.4)
- Upgrading guzzlehttp/psr7 (2.2.2 => 2.3.0)
- Upgrading symfony/cache (v6.1.0 => v6.1.1)
- Upgrading symfony/console (v6.1.0 => v6.1.1)
- Upgrading symfony/var-exporter (v6.1.0 => v6.1.1)
=> Composer update with 5 changes 2022-06-10

update/composer.lock
- Upgrading league/flysystem (3.0.20 => 3.0.21)
=> Composer update with 1 changes 2022-06-13

update/composer.lock
- Upgrading laravel-zero/foundation (v9.13.0 => v9.17.0)
=> Composer update with 1 changes 2022-06-17

update/composer.lock
- Upgrading nunomaduro/termwind (v1.10.1 => v1.11.1)
=> Composer update with 1 changes 2022-06-18

update/composer.lock
- Upgrading phpunit/phpunit (9.5.20 => 9.5.21)
=> Composer update with 1 changes 2022-06-20

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.4.4 => 7.4.5)
- Upgrading guzzlehttp/psr7 (2.3.0 => 2.4.0)
- Upgrading laravel-zero/foundation (v9.17.0 => v9.17.1)
=> Composer update with 3 changes 2022-06-21

update/composer.lock
- Upgrading symfony/cache (v6.1.1 => v6.1.2)
- Upgrading symfony/console (v6.1.1 => v6.1.2)
- Upgrading symfony/string (v6.1.0 => v6.1.2)
=> Composer update with 3 changes 2022-06-27

update/composer.lock
- Upgrading nunomaduro/collision (v6.2.0 => v6.2.1)
- Upgrading nunomaduro/termwind (v1.11.1 => v1.12.0)
=> Composer update with 2 changes 2022-06-28

update/composer.lock
- Upgrading league/flysystem (3.0.21 => 3.1.0)
- Upgrading nesbot/carbon (2.58.0 => 2.59.1)
=> Composer update with 2 changes 2022-06-30

update/composer.lock
- Upgrading nunomaduro/termwind (v1.12.0 => v1.13.0)
=> Composer update with 1 changes 2022-07-02

update/composer.lock
- Upgrading php-http/discovery (1.14.2 => 1.14.3)
=> Composer update with 1 changes 2022-07-12

update/composer.lock
- Upgrading illuminate/bus (v9.19.0 => v9.20.0)
- Upgrading illuminate/cache (v9.19.0 => v9.20.0)
- Upgrading illuminate/collections (v9.19.0 => v9.20.0)
- Upgrading illuminate/conditionable (v9.19.0 => v9.20.0)
- Upgrading illuminate/config (v9.19.0 => v9.20.0)
- Upgrading illuminate/console (v9.19.0 => v9.20.0)
- Upgrading illuminate/container (v9.19.0 => v9.20.0)
- Upgrading illuminate/contracts (v9.19.0 => v9.20.0)
- Upgrading illuminate/events (v9.19.0 => v9.20.0)
- Upgrading illuminate/filesystem (v9.19.0 => v9.20.0)
- Upgrading illuminate/macroable (v9.19.0 => v9.20.0)
- Upgrading illuminate/pipeline (v9.19.0 => v9.20.0)
- Upgrading illuminate/support (v9.19.0 => v9.20.0)
- Upgrading illuminate/testing (v9.19.0 => v9.20.0)
=> Composer update with 14 changes 2022-07-14

update/composer.lock
- Upgrading league/flysystem (3.1.0 => 3.1.1)
=> Composer update with 1 changes 2022-07-19

update/composer.lock
- Upgrading illuminate/bus (v9.20.0 => v9.21.0)
- Upgrading illuminate/cache (v9.20.0 => v9.21.0)
- Upgrading illuminate/collections (v9.20.0 => v9.21.0)
- Upgrading illuminate/conditionable (v9.20.0 => v9.21.0)
- Upgrading illuminate/config (v9.20.0 => v9.21.0)
- Upgrading illuminate/console (v9.20.0 => v9.21.0)
- Upgrading illuminate/container (v9.20.0 => v9.21.0)
- Upgrading illuminate/contracts (v9.20.0 => v9.21.0)
- Upgrading illuminate/events (v9.20.0 => v9.21.0)
- Upgrading illuminate/filesystem (v9.20.0 => v9.21.0)
- Upgrading illuminate/macroable (v9.20.0 => v9.21.0)
- Upgrading illuminate/pipeline (v9.20.0 => v9.21.0)
- Upgrading illuminate/support (v9.20.0 => v9.21.0)
- Upgrading illuminate/testing (v9.20.0 => v9.21.0)
- Locking illuminate/view (v9.21.0)
- Upgrading …
=> Composer update with 17 changes 2022-07-20

update/composer.lock
- Upgrading illuminate/bus (v9.21.0 => v9.21.3)
- Upgrading illuminate/cache (v9.21.0 => v9.21.3)
- Upgrading illuminate/collections (v9.21.0 => v9.21.3)
- Upgrading illuminate/conditionable (v9.21.0 => v9.21.3)
- Upgrading illuminate/config (v9.21.0 => v9.21.3)
- Upgrading illuminate/console (v9.21.0 => v9.21.3)
- Upgrading illuminate/container (v9.21.0 => v9.21.3)
- Upgrading illuminate/contracts (v9.21.0 => v9.21.3)
- Upgrading illuminate/events (v9.21.0 => v9.21.3)
- Upgrading illuminate/filesystem (v9.21.0 => v9.21.3)
- Upgrading illuminate/macroable (v9.21.0 => v9.21.3)
- Upgrading illuminate/pipeline (v9.21.0 => v9.21.3)
- Upgrading illuminate/support (v9.21.0 => v9.21.3)
- Upgrading illuminate/testing (v9.21.0 => v9.21.3)
- Upgrading illuminate/view (v9.21.0 => v9.21.3)
=> Composer update with 15 changes 2022-07-21

update/composer.lock
- Upgrading illuminate/bus (v9.21.3 => v9.21.5)
- Upgrading illuminate/cache (v9.21.3 => v9.21.5)
- Upgrading illuminate/collections (v9.21.3 => v9.21.5)
- Upgrading illuminate/conditionable (v9.21.3 => v9.21.5)
- Upgrading illuminate/config (v9.21.3 => v9.21.5)
- Upgrading illuminate/console (v9.21.3 => v9.21.5)
- Upgrading illuminate/container (v9.21.3 => v9.21.5)
- Upgrading illuminate/contracts (v9.21.3 => v9.21.5)
- Upgrading illuminate/events (v9.21.3 => v9.21.5)
- Upgrading illuminate/filesystem (v9.21.3 => v9.21.5)
- Upgrading illuminate/macroable (v9.21.3 => v9.21.5)
- Upgrading illuminate/pipeline (v9.21.3 => v9.21.5)
- Upgrading illuminate/support (v9.21.3 => v9.21.5)
- Upgrading illuminate/testing (v9.21.3 => v9.21.5)
- Upgrading illuminate/view (v9.21.3 => v9.21.5)
=> Composer update with 15 changes 2022-07-22

update/composer.lock
- Upgrading illuminate/bus (v9.21.5 => v9.21.6)
- Upgrading illuminate/cache (v9.21.5 => v9.21.6)
- Upgrading illuminate/collections (v9.21.5 => v9.21.6)
- Upgrading illuminate/conditionable (v9.21.5 => v9.21.6)
- Upgrading illuminate/config (v9.21.5 => v9.21.6)
- Upgrading illuminate/console (v9.21.5 => v9.21.6)
- Upgrading illuminate/container (v9.21.5 => v9.21.6)
- Upgrading illuminate/contracts (v9.21.5 => v9.21.6)
- Upgrading illuminate/events (v9.21.5 => v9.21.6)
- Upgrading illuminate/filesystem (v9.21.5 => v9.21.6)
- Upgrading illuminate/macroable (v9.21.5 => v9.21.6)
- Upgrading illuminate/pipeline (v9.21.5 => v9.21.6)
- Upgrading illuminate/support (v9.21.5 => v9.21.6)
- Upgrading illuminate/testing (v9.21.5 => v9.21.6)
- Upgrading illuminate/view (v9.21.5 => v9.21.6)
=> Composer update with 15 changes 2022-07-23

update/composer.lock
- Upgrading illuminate/bus (v9.21.6 => v9.22.1)
- Upgrading illuminate/cache (v9.21.6 => v9.22.1)
- Upgrading illuminate/collections (v9.21.6 => v9.22.1)
- Upgrading illuminate/conditionable (v9.21.6 => v9.22.1)
- Upgrading illuminate/config (v9.21.6 => v9.22.1)
- Upgrading illuminate/console (v9.21.6 => v9.22.1)
- Upgrading illuminate/container (v9.21.6 => v9.22.1)
- Upgrading illuminate/contracts (v9.21.6 => v9.22.1)
- Upgrading illuminate/events (v9.21.6 => v9.22.1)
- Upgrading illuminate/filesystem (v9.21.6 => v9.22.1)
- Upgrading illuminate/macroable (v9.21.6 => v9.22.1)
- Upgrading illuminate/pipeline (v9.21.6 => v9.22.1)
- Upgrading illuminate/support (v9.21.6 => v9.22.1)
- Upgrading illuminate/testing (v9.21.6 => v9.22.1)
- Upgrading illuminate/view (v9.21.6 => v9.22.1)
- …
=> Composer update with 16 changes 2022-07-27

update/composer.lock
- Upgrading nesbot/carbon (2.59.1 => 2.60.0)
=> Composer update with 1 changes 2022-07-28

update/composer.lock
- Upgrading symfony/cache (v6.1.2 => v6.1.3)
- Upgrading symfony/console (v6.1.2 => v6.1.3)
- Upgrading symfony/error-handler (v6.1.0 => v6.1.3)
- Upgrading symfony/finder (v6.1.0 => v6.1.3)
- Upgrading symfony/process (v6.1.0 => v6.1.3)
- Upgrading symfony/string (v6.1.2 => v6.1.3)
- Upgrading symfony/translation (v6.1.0 => v6.1.3)
- Upgrading symfony/var-dumper (v6.1.0 => v6.1.3)
- Upgrading symfony/var-exporter (v6.1.1 => v6.1.3)
=> Composer update with 9 changes 2022-07-30

update/composer.lock
- Upgrading graham-campbell/result-type (v1.0.4 => v1.1.0)
- Upgrading phpoption/phpoption (1.8.1 => 1.9.0)
=> Composer update with 2 changes 2022-07-31

update/composer.lock
- Upgrading graham-campbell/bounded-cache (v2.0.0 => v2.1.0)
=> Composer update with 1 changes 2022-07-31

update/composer.lock
- Upgrading nunomaduro/termwind (v1.13.0 => v1.14.0)
=> Composer update with 1 changes 2022-08-02

update/composer.lock
- Upgrading illuminate/bus (v9.22.1 => v9.23.0)
- Upgrading illuminate/cache (v9.22.1 => v9.23.0)
- Upgrading illuminate/collections (v9.22.1 => v9.23.0)
- Upgrading illuminate/conditionable (v9.22.1 => v9.23.0)
- Upgrading illuminate/config (v9.22.1 => v9.23.0)
- Upgrading illuminate/console (v9.22.1 => v9.23.0)
- Upgrading illuminate/container (v9.22.1 => v9.23.0)
- Upgrading illuminate/contracts (v9.22.1 => v9.23.0)
- Upgrading illuminate/events (v9.22.1 => v9.23.0)
- Upgrading illuminate/filesystem (v9.22.1 => v9.23.0)
- Upgrading illuminate/macroable (v9.22.1 => v9.23.0)
- Upgrading illuminate/pipeline (v9.22.1 => v9.23.0)
- Upgrading illuminate/support (v9.22.1 => v9.23.0)
- Upgrading illuminate/testing (v9.22.1 => v9.23.0)
- Upgrading illuminate/view (v9.22.1 => v9.23.0)
=> Composer update with 15 changes 2022-08-03

update/composer.lock
- Upgrading brick/math (0.9.3 => 0.10.1)
- Upgrading ramsey/uuid (4.3.1 => 4.4.0)
=> Composer update with 2 changes 2022-08-06

update/composer.lock
- Upgrading nesbot/carbon (2.60.0 => 2.61.0)
=> Composer update with 1 changes 2022-08-07

update/composer.lock
- Upgrading illuminate/bus (v9.23.0 => v9.24.0)
- Upgrading illuminate/cache (v9.23.0 => v9.24.0)
- Upgrading illuminate/collections (v9.23.0 => v9.24.0)
- Upgrading illuminate/conditionable (v9.23.0 => v9.24.0)
- Upgrading illuminate/config (v9.23.0 => v9.24.0)
- Upgrading illuminate/console (v9.23.0 => v9.24.0)
- Upgrading illuminate/container (v9.23.0 => v9.24.0)
- Upgrading illuminate/contracts (v9.23.0 => v9.24.0)
- Upgrading illuminate/events (v9.23.0 => v9.24.0)
- Upgrading illuminate/filesystem (v9.23.0 => v9.24.0)
- Upgrading illuminate/macroable (v9.23.0 => v9.24.0)
- Upgrading illuminate/pipeline (v9.23.0 => v9.24.0)
- Upgrading illuminate/support (v9.23.0 => v9.24.0)
- Upgrading illuminate/testing (v9.23.0 => v9.24.0)
- Upgrading illuminate/view (v9.23.0 => v9.24.0)
=> Composer update with 15 changes 2022-08-10

update/composer.lock
- Upgrading brick/math (0.10.1 => 0.10.2)
=> Composer update with 1 changes 2022-08-11

update/composer.lock
- Upgrading league/flysystem (3.2.0 => 3.2.1)
=> Composer update with 1 changes 2022-08-15

update/composer.lock
- Upgrading illuminate/bus (v9.24.0 => v9.25.1)
- Upgrading illuminate/cache (v9.24.0 => v9.25.1)
- Upgrading illuminate/collections (v9.24.0 => v9.25.1)
- Upgrading illuminate/conditionable (v9.24.0 => v9.25.1)
- Upgrading illuminate/config (v9.24.0 => v9.25.1)
- Upgrading illuminate/console (v9.24.0 => v9.25.1)
- Upgrading illuminate/container (v9.24.0 => v9.25.1)
- Upgrading illuminate/contracts (v9.24.0 => v9.25.1)
- Upgrading illuminate/events (v9.24.0 => v9.25.1)
- Upgrading illuminate/filesystem (v9.24.0 => v9.25.1)
- Upgrading illuminate/macroable (v9.24.0 => v9.25.1)
- Upgrading illuminate/pipeline (v9.24.0 => v9.25.1)
- Upgrading illuminate/support (v9.24.0 => v9.25.1)
- Upgrading illuminate/testing (v9.24.0 => v9.25.1)
- Upgrading illuminate/view (v9.24.0 => v9.25.1)
=> Composer update with 15 changes 2022-08-17

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.15 => 9.2.16)
- Upgrading phpunit/phpunit (9.5.21 => 9.5.22)
=> Composer update with 2 changes 2022-08-21

update/composer.lock
- Upgrading illuminate/bus (v9.25.1 => v9.26.1)
- Upgrading illuminate/cache (v9.25.1 => v9.26.1)
- Upgrading illuminate/collections (v9.25.1 => v9.26.1)
- Upgrading illuminate/conditionable (v9.25.1 => v9.26.1)
- Upgrading illuminate/config (v9.25.1 => v9.26.1)
- Upgrading illuminate/console (v9.25.1 => v9.26.1)
- Upgrading illuminate/container (v9.25.1 => v9.26.1)
- Upgrading illuminate/contracts (v9.25.1 => v9.26.1)
- Upgrading illuminate/events (v9.25.1 => v9.26.1)
- Upgrading illuminate/filesystem (v9.25.1 => v9.26.1)
- Upgrading illuminate/macroable (v9.25.1 => v9.26.1)
- Upgrading illuminate/pipeline (v9.25.1 => v9.26.1)
- Upgrading illuminate/support (v9.25.1 => v9.26.1)
- Upgrading illuminate/testing (v9.25.1 => v9.26.1)
- Upgrading illuminate/view (v9.25.1 => v9.26.0)
=> Composer update with 15 changes 2022-08-24

update/composer.lock
- Upgrading laravel-zero/foundation (v9.21.0 => v9.26.1)
- Upgrading symfony/console (v6.1.3 => v6.1.4)
- Upgrading symfony/string (v6.1.3 => v6.1.4)
- Upgrading symfony/translation (v6.1.3 => v6.1.4)
=> Composer update with 4 changes 2022-08-27

update/composer.lock
- Removing facade/ignition-contracts (1.0.2)
- Upgrading guzzlehttp/guzzle (7.4.5 => 7.5.0)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
- Upgrading guzzlehttp/psr7 (2.4.0 => 2.4.1)
- Upgrading nesbot/carbon (2.61.0 => 2.62.0)
- Upgrading nunomaduro/collision (v6.2.1 => v6.3.0)
- Upgrading sebastian/type (3.0.0 => 3.1.0)
=> Composer update with 7 changes 2022-08-30

update/composer.lock
- Upgrading nesbot/carbon (2.62.0 => 2.62.1)
- Upgrading nikic/php-parser (v4.14.0 => v4.15.0)
=> Composer update with 2 changes 2022-09-04

update/composer.lock
- Upgrading nikic/php-parser (v4.15.0 => v4.15.1)
=> Composer update with 1 changes 2022-09-05

update/composer.lock
- Upgrading illuminate/bus (v9.27.0 => v9.28.0)
- Upgrading illuminate/cache (v9.27.0 => v9.28.0)
- Upgrading illuminate/collections (v9.27.0 => v9.28.0)
- Upgrading illuminate/conditionable (v9.27.0 => v9.28.0)
- Upgrading illuminate/config (v9.27.0 => v9.28.0)
- Upgrading illuminate/console (v9.27.0 => v9.28.0)
- Upgrading illuminate/container (v9.27.0 => v9.28.0)
- Upgrading illuminate/contracts (v9.27.0 => v9.28.0)
- Upgrading illuminate/events (v9.27.0 => v9.28.0)
- Upgrading illuminate/filesystem (v9.27.0 => v9.28.0)
- Upgrading illuminate/macroable (v9.27.0 => v9.28.0)
- Upgrading illuminate/pipeline (v9.27.0 => v9.28.0)
- Upgrading illuminate/support (v9.27.0 => v9.28.0)
- Upgrading illuminate/testing (v9.27.0 => v9.28.0)
- Upgrading illuminate/view (v9.27.0 => v9.28.0)
=> Composer update with 15 changes 2022-09-07

update/composer.lock
- Upgrading doctrine/inflector (2.0.4 => 2.0.5)
- Upgrading mockery/mockery (1.5.0 => 1.5.1)
=> Composer update with 2 changes 2022-09-08

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.3.1 => v3.3.2)
=> Composer update with 1 changes 2022-09-11

update/composer.lock
- Upgrading sebastian/type (3.1.0 => 3.2.0)
=> Composer update with 1 changes 2022-09-13

update/composer.lock
- Upgrading illuminate/bus (v9.29.0 => v9.30.0)
- Upgrading illuminate/cache (v9.29.0 => v9.30.0)
- Upgrading illuminate/collections (v9.29.0 => v9.30.0)
- Upgrading illuminate/conditionable (v9.29.0 => v9.30.0)
- Upgrading illuminate/config (v9.29.0 => v9.30.0)
- Upgrading illuminate/console (v9.29.0 => v9.30.0)
- Upgrading illuminate/container (v9.29.0 => v9.30.0)
- Upgrading illuminate/contracts (v9.29.0 => v9.30.0)
- Upgrading illuminate/events (v9.29.0 => v9.30.0)
- Upgrading illuminate/filesystem (v9.29.0 => v9.30.0)
- Upgrading illuminate/macroable (v9.29.0 => v9.30.0)
- Upgrading illuminate/pipeline (v9.29.0 => v9.30.0)
- Upgrading illuminate/support (v9.29.0 => v9.30.0)
- Upgrading illuminate/testing (v9.29.0 => v9.30.0)
- Upgrading illuminate/view (v9.29.0 => v9.30.0)
=> Composer update with 15 changes 2022-09-14

update/composer.lock
- Upgrading ramsey/uuid (4.4.0 => 4.5.0)
- Upgrading sebastian/comparator (4.0.6 => 4.0.8)
- Upgrading sebastian/exporter (4.0.4 => 4.0.5)
=> Composer update with 3 changes 2022-09-15

update/composer.lock
- Upgrading league/flysystem (3.3.0 => 3.4.0)
=> Composer update with 1 changes 2022-09-17

update/composer.lock
- Upgrading league/flysystem (3.4.0 => 3.5.0)
=> Composer update with 1 changes 2022-09-18

update/composer.lock
- Upgrading league/flysystem (3.5.0 => 3.5.1)
=> Composer update with 1 changes 2022-09-19

update/composer.lock
- Upgrading league/flysystem (3.5.1 => 3.5.2)
=> Composer update with 1 changes 2022-09-24

update/composer.lock
- Upgrading phpunit/phpunit (9.5.24 => 9.5.25)
=> Composer update with 1 changes 2022-09-26

update/composer.lock
- Upgrading symfony/console (v6.1.5 => v6.1.6)
- Upgrading symfony/error-handler (v6.1.3 => v6.1.6)
- Upgrading symfony/string (v6.1.5 => v6.1.6)
- Upgrading symfony/translation (v6.1.4 => v6.1.6)
- Upgrading symfony/var-dumper (v6.1.5 => v6.1.6)
=> Composer update with 5 changes 2022-10-13

update/composer.lock
- Upgrading league/flysystem (3.5.2 => 3.6.0)
=> Composer update with 1 changes 2022-10-14

update/composer.lock
- Upgrading vlucas/phpdotenv (v5.4.1 => v5.5.0)
=> Composer update with 1 changes 2022-10-16

update/composer.lock
- Upgrading league/flysystem (3.7.0 => 3.8.0)
=> Composer update with 1 changes 2022-10-18

update/composer.lock
- Upgrading league/flysystem (3.9.0 => 3.10.1)
=> Composer update with 1 changes 2022-10-22

update/composer.lock
- Upgrading guzzlehttp/psr7 (2.4.2 => 2.4.3)
=> Composer update with 1 changes 2022-10-27

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.17 => 9.2.18)
- Upgrading phpunit/phpunit (9.5.25 => 9.5.26)
=> Composer update with 2 changes 2022-10-28

update/composer.lock
- Upgrading nunomaduro/termwind (v1.14.1 => v1.14.2)
- Upgrading symfony/cache (v6.1.5 => v6.1.7)
- Upgrading symfony/console (v6.1.6 => v6.1.7)
- Upgrading symfony/error-handler (v6.1.6 => v6.1.7)
- Upgrading symfony/string (v6.1.6 => v6.1.7)
=> Composer update with 5 changes 2022-10-29

update/composer.lock
- Upgrading filp/whoops (2.14.5 => 2.14.6)
=> Composer update with 1 changes 2022-11-03

update/composer.lock
- Upgrading ramsey/uuid (4.5.1 => 4.6.0)
=> Composer update with 1 changes 2022-11-06

update/composer.lock
- Upgrading nesbot/carbon (2.62.1 => 2.63.0)
=> Composer update with 1 changes 2022-11-10

update/composer.lock
- Upgrading symfony/polyfill-ctype (v1.26.0 => v1.27.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.26.0 => v1.27.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.26.0 => v1.27.0)
- Upgrading symfony/polyfill-mbstring (v1.26.0 => v1.27.0)
- Upgrading symfony/polyfill-php80 (v1.26.0 => v1.27.0)
- Upgrading symfony/polyfill-php81 (v1.26.0 => v1.27.0)
=> Composer update with 6 changes 2022-11-11

update/composer.lock
- Upgrading nikic/php-parser (v4.15.1 => v4.15.2)
=> Composer update with 1 changes 2022-11-13

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.18 => 9.2.19)
=> Composer update with 1 changes 2022-11-19

update/composer.lock
- Upgrading league/flysystem (3.10.3 => 3.10.4)
=> Composer update with 1 changes 2022-11-27

update/composer.lock
- Upgrading symfony/cache (v6.1.7 => v6.1.8)
- Upgrading symfony/console (v6.1.7 => v6.1.8)
=> Composer update with 2 changes 2022-11-29

update/composer.lock
- Upgrading league/flysystem (3.10.4 => 3.11.0)
- Upgrading nesbot/carbon (2.63.0 => 2.64.0)
=> Composer update with 2 changes 2022-12-03

update/composer.lock
- Upgrading phpunit/phpunit (9.5.26 => 9.5.27)
=> Composer update with 1 changes 2022-12-10

update/composer.lock
- Upgrading czproject/git-php (v4.0.5 => v4.1.0)
=> Composer update with 1 changes 2022-12-11

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.19 => 9.2.20)
=> Composer update with 1 changes 2022-12-14

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.20 => 9.2.21)
=> Composer update with 1 changes 2022-12-15

update/composer.lock
- Upgrading symfony/cache (v6.2.0 => v6.2.2)
- Upgrading symfony/console (v6.2.1 => v6.2.2)
- Upgrading symfony/error-handler (v6.2.1 => v6.2.2)
- Upgrading symfony/service-contracts (v3.1.1 => v3.2.0)
- Upgrading symfony/string (v6.2.0 => v6.2.2)
- Upgrading symfony/translation (v6.2.0 => v6.2.2)
- Upgrading symfony/var-dumper (v6.2.1 => v6.2.2)
- Upgrading symfony/var-exporter (v6.2.1 => v6.2.2)
=> Composer update with 8 changes 2022-12-17

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.21 => 9.2.22)
=> Composer update with 1 changes 2022-12-19

update/composer.lock
- Upgrading ramsey/uuid (4.6.0 => 4.7.0)
=> Composer update with 1 changes 2022-12-20

update/composer.lock
- Upgrading nunomaduro/collision (v6.3.1 => v6.3.2)
=> Composer update with 1 changes 2022-12-24

update/composer.lock
- Upgrading jolicode/jolinotif (v2.4.0 => v2.5.0)
=> Composer update with 1 changes 2022-12-27

update/composer.lock
- Upgrading ramsey/collection (1.2.2 => 1.3.0)
=> Composer update with 1 changes 2022-12-28

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.22 => 9.2.23)
- Upgrading symfony/cache (v6.2.2 => v6.2.3)
- Upgrading symfony/console (v6.2.2 => v6.2.3)
- Upgrading symfony/error-handler (v6.2.2 => v6.2.3)
- Upgrading symfony/finder (v6.2.0 => v6.2.3)
- Upgrading symfony/translation (v6.2.2 => v6.2.3)
- Upgrading symfony/var-dumper (v6.2.2 => v6.2.3)
- Upgrading symfony/var-exporter (v6.2.2 => v6.2.3)
=> Composer update with 8 changes 2022-12-29

update/composer.lock
- Upgrading doctrine/instantiator (1.4.1 => 1.5.0)
- Upgrading symfony/cache (v6.2.3 => v6.2.4)
=> Composer update with 2 changes 2022-12-31

update/composer.lock
- Removing symfony/polyfill-php81 (v1.27.0)
- Upgrading ramsey/collection (1.3.0 => 2.0.0)
- Upgrading ramsey/uuid (4.7.0 => 4.7.1)
=> Composer update with 3 changes 2023-01-01

update/composer.lock
- Upgrading nesbot/carbon (2.64.0 => 2.64.1)
=> Composer update with 1 changes 2023-01-03

update/composer.lock
- Upgrading league/flysystem (3.12.0 => 3.12.1)
- Upgrading nesbot/carbon (2.64.1 => 2.65.0)
=> Composer update with 2 changes 2023-01-07

update/composer.lock
- Removing ramsey/collection (2.0.0)
- Upgrading laravel-zero/foundation (v9.26.1 => v9.47.0)
- Upgrading nunomaduro/laravel-console-summary (v1.8.0 => v1.9.0)
- Upgrading nunomaduro/laravel-console-task (v1.7.0 => v1.8.0)
- Upgrading nunomaduro/laravel-desktop-notifier (v2.6.0 => v2.7.0)
- Upgrading ramsey/uuid (4.7.1 => 4.7.2)
=> Composer update with 6 changes 2023-01-12

update/composer.lock
- Locking ramsey/collection (2.0.0)
- Upgrading ramsey/uuid (4.7.2 => 4.7.3)
=> Composer update with 2 changes 2023-01-13

update/composer.lock
- Upgrading doctrine/instantiator (1.5.0 => 2.0.0)
- Upgrading phpunit/phpunit (9.5.27 => 9.5.28)
=> Composer update with 2 changes 2023-01-15

update/composer.lock
- Upgrading nikic/php-parser (v4.15.2 => v4.15.3)
=> Composer update with 1 changes 2023-01-17

update/composer.lock
- Upgrading league/flysystem (3.12.1 => 3.12.2)
=> Composer update with 1 changes 2023-01-20

update/composer.lock
- Upgrading symfony/cache (v6.2.4 => v6.2.5)
- Upgrading symfony/console (v6.2.3 => v6.2.5)
- Upgrading symfony/error-handler (v6.2.3 => v6.2.5)
- Upgrading symfony/finder (v6.2.3 => v6.2.5)
- Upgrading symfony/options-resolver (v6.2.0 => v6.2.5)
- Upgrading symfony/process (v6.2.0 => v6.2.5)
- Upgrading symfony/string (v6.2.2 => v6.2.5)
- Upgrading symfony/translation (v6.2.3 => v6.2.5)
- Upgrading symfony/var-dumper (v6.2.3 => v6.2.5)
- Upgrading symfony/var-exporter (v6.2.3 => v6.2.5)
=> Composer update with 10 changes 2023-01-25

update/composer.lock
- Upgrading phpunit/php-code-coverage (9.2.23 => 9.2.24)
=> Composer update with 1 changes 2023-01-27

update/composer.lock
- Upgrading illuminate/bus (v9.48.0 => v9.50.2)
- Upgrading illuminate/cache (v9.48.0 => v9.50.2)
- Upgrading illuminate/collections (v9.48.0 => v9.50.2)
- Upgrading illuminate/conditionable (v9.48.0 => v9.50.2)
- Upgrading illuminate/config (v9.48.0 => v9.50.2)
- Upgrading illuminate/console (v9.48.0 => v9.50.2)
- Upgrading illuminate/container (v9.48.0 => v9.50.2)
- Upgrading illuminate/contracts (v9.48.0 => v9.50.2)
- Upgrading illuminate/events (v9.48.0 => v9.50.2)
- Upgrading illuminate/filesystem (v9.48.0 => v9.50.2)
- Upgrading illuminate/macroable (v9.48.0 => v9.50.2)
- Upgrading illuminate/pipeline (v9.48.0 => v9.50.2)
- Upgrading illuminate/support (v9.48.0 => v9.50.2)
- Upgrading illuminate/testing (v9.48.0 => v9.50.2)
- Upgrading illuminate/view (v9.48.0 => v9.50.2)
- …
=> Composer update with 21 changes 2023-02-06

update/composer.lock
- Upgrading illuminate/bus (v9.48.0 => v9.50.2)
- Upgrading illuminate/cache (v9.48.0 => v9.50.2)
- Upgrading illuminate/collections (v9.48.0 => v9.50.2)
- Upgrading illuminate/conditionable (v9.48.0 => v9.50.2)
- Upgrading illuminate/config (v9.48.0 => v9.50.2)
- Upgrading illuminate/console (v9.48.0 => v9.50.2)
- Upgrading illuminate/container (v9.48.0 => v9.50.2)
- Upgrading illuminate/contracts (v9.48.0 => v9.50.2)
- Upgrading illuminate/events (v9.48.0 => v9.50.2)
- Upgrading illuminate/filesystem (v9.48.0 => v9.50.2)
- Upgrading illuminate/macroable (v9.48.0 => v9.50.2)
- Upgrading illuminate/pipeline (v9.48.0 => v9.50.2)
- Upgrading illuminate/support (v9.48.0 => v9.50.2)
- Upgrading illuminate/testing (v9.48.0 => v9.50.2)
- Upgrading illuminate/view (v9.48.0 => v9.50.2)
- …
=> Composer update with 22 changes 2023-02-06

update/composer.lock
- Removing symfony/polyfill-php81 (v1.26.0)
- Upgrading czproject/git-php (v4.0.5 => v4.1.0)
- Upgrading doctrine/instantiator (1.4.1 => 2.0.0)
- Upgrading illuminate/bus (v9.38.0 => v9.50.2)
- Upgrading illuminate/cache (v9.38.0 => v9.50.2)
- Upgrading illuminate/collections (v9.38.0 => v9.50.2)
- Upgrading illuminate/conditionable (v9.38.0 => v9.50.2)
- Upgrading illuminate/config (v9.38.0 => v9.50.2)
- Upgrading illuminate/console (v9.38.0 => v9.50.2)
- Upgrading illuminate/container (v9.38.0 => v9.50.2)
- Upgrading illuminate/contracts (v9.38.0 => v9.50.2)
- Upgrading illuminate/events (v9.38.0 => v9.50.2)
- Upgrading illuminate/filesystem (v9.38.0 => v9.50.2)
- Upgrading illuminate/macroable (v9.38.0 => v9.50.2)
- Upgrading illuminate/pipeline (v9.38.0 => v9.50.2)
- Upgrading …
=> Composer update with 54 changes 2023-02-06

update/composer.lock
- Upgrading illuminate/bus (v9.50.2 => v9.51.0)
- Upgrading illuminate/cache (v9.50.2 => v9.51.0)
- Upgrading illuminate/collections (v9.50.2 => v9.51.0)
- Upgrading illuminate/conditionable (v9.50.2 => v9.51.0)
- Upgrading illuminate/config (v9.50.2 => v9.51.0)
- Upgrading illuminate/console (v9.50.2 => v9.51.0)
- Upgrading illuminate/container (v9.50.2 => v9.51.0)
- Upgrading illuminate/contracts (v9.50.2 => v9.51.0)
- Upgrading illuminate/events (v9.50.2 => v9.51.0)
- Upgrading illuminate/filesystem (v9.50.2 => v9.51.0)
- Upgrading illuminate/macroable (v9.50.2 => v9.51.0)
- Upgrading illuminate/pipeline (v9.50.2 => v9.51.0)
- Upgrading illuminate/support (v9.50.2 => v9.51.0)
- Upgrading illuminate/testing (v9.50.2 => v9.51.0)
- Upgrading illuminate/view (v9.50.2 => v9.51.0)
- …
=> Composer update with 16 changes 2023-02-08

update/composer.lock
- Upgrading php-http/discovery (1.14.3 => 1.15.0)
=> Composer update with 1 changes 2023-02-10

update/composer.lock
- Upgrading illuminate/bus (v9.50.2 => v9.51.0)
- Upgrading illuminate/cache (v9.50.2 => v9.51.0)
- Upgrading illuminate/collections (v9.50.2 => v9.51.0)
- Upgrading illuminate/conditionable (v9.50.2 => v9.51.0)
- Upgrading illuminate/config (v9.50.2 => v9.51.0)
- Upgrading illuminate/console (v9.50.2 => v9.51.0)
- Upgrading illuminate/container (v9.50.2 => v9.51.0)
- Upgrading illuminate/contracts (v9.50.2 => v9.51.0)
- Upgrading illuminate/events (v9.50.2 => v9.51.0)
- Upgrading illuminate/filesystem (v9.50.2 => v9.51.0)
- Upgrading illuminate/macroable (v9.50.2 => v9.51.0)
- Upgrading illuminate/pipeline (v9.50.2 => v9.51.0)
- Upgrading illuminate/support (v9.50.2 => v9.51.0)
- Upgrading illuminate/testing (v9.50.2 => v9.51.0)
- Upgrading illuminate/view (v9.50.2 => v9.51.0)
- …
=> Composer update with 17 changes 2023-02-10

update/composer.lock
- Upgrading php-http/discovery (1.15.0 => 1.15.1)
=> Composer update with 1 changes 2023-02-11

update/composer.lock
- Upgrading php-http/discovery (1.15.1 => 1.15.2)
=> Composer update with 1 changes 2023-02-12

update/composer.lock
- Upgrading illuminate/bus (v9.51.0 => v9.52.0)
- Upgrading illuminate/cache (v9.51.0 => v9.52.0)
- Upgrading illuminate/collections (v9.51.0 => v9.52.0)
- Upgrading illuminate/conditionable (v9.51.0 => v9.52.0)
- Upgrading illuminate/config (v9.51.0 => v9.52.0)
- Upgrading illuminate/console (v9.51.0 => v9.52.0)
- Upgrading illuminate/container (v9.51.0 => v9.52.0)
- Upgrading illuminate/contracts (v9.51.0 => v9.52.0)
- Upgrading illuminate/events (v9.51.0 => v9.52.0)
- Upgrading illuminate/filesystem (v9.51.0 => v9.52.0)
- Upgrading illuminate/macroable (v9.51.0 => v9.52.0)
- Upgrading illuminate/pipeline (v9.51.0 => v9.52.0)
- Upgrading illuminate/support (v9.51.0 => v9.52.0)
- Upgrading illuminate/testing (v9.51.0 => v9.52.0)
- Upgrading illuminate/view (v9.51.0 => v9.52.0)
=> Composer update with 15 changes 2023-02-15

update/composer.lock
- Upgrading league/flysystem (3.12.2 => 3.12.3)
=> Composer update with 1 changes 2023-02-20

update/composer.lock
- Upgrading illuminate/bus (v9.52.0 => v9.52.2)
- Upgrading illuminate/cache (v9.52.0 => v9.52.2)
- Upgrading illuminate/collections (v9.52.0 => v9.52.2)
- Upgrading illuminate/conditionable (v9.52.0 => v9.52.2)
- Upgrading illuminate/config (v9.52.0 => v9.52.2)
- Upgrading illuminate/console (v9.52.0 => v9.52.2)
- Upgrading illuminate/container (v9.52.0 => v9.52.2)
- Upgrading illuminate/contracts (v9.52.0 => v9.52.2)
- Upgrading illuminate/events (v9.52.0 => v9.52.2)
- Upgrading illuminate/filesystem (v9.52.0 => v9.52.2)
- Upgrading illuminate/macroable (v9.52.0 => v9.52.2)
- Upgrading illuminate/pipeline (v9.52.0 => v9.52.2)
- Upgrading illuminate/support (v9.52.0 => v9.52.2)
- Upgrading illuminate/testing (v9.52.0 => v9.52.2)
- Upgrading illuminate/view (v9.52.0 => v9.52.2)
=> Composer update with 15 changes 2023-02-22

update/composer.lock
- Upgrading illuminate/bus (v9.52.2 => v9.52.4)
- Upgrading illuminate/cache (v9.52.2 => v9.52.4)
- Upgrading illuminate/collections (v9.52.2 => v9.52.4)
- Upgrading illuminate/conditionable (v9.52.2 => v9.52.4)
- Upgrading illuminate/config (v9.52.2 => v9.52.4)
- Upgrading illuminate/console (v9.52.2 => v9.52.4)
- Upgrading illuminate/container (v9.52.2 => v9.52.4)
- Upgrading illuminate/contracts (v9.52.2 => v9.52.4)
- Upgrading illuminate/events (v9.52.2 => v9.52.4)
- Upgrading illuminate/filesystem (v9.52.2 => v9.52.4)
- Upgrading illuminate/macroable (v9.52.2 => v9.52.4)
- Upgrading illuminate/pipeline (v9.52.2 => v9.52.4)
- Upgrading illuminate/support (v9.52.2 => v9.52.4)
- Upgrading illuminate/testing (v9.52.2 => v9.52.4)
- Upgrading illuminate/view (v9.52.2 => v9.52.4)
=> Composer update with 15 changes 2023-02-23

update/composer.lock
- Upgrading graham-campbell/bounded-cache (v2.1.0 => v2.1.1)
- Upgrading graham-campbell/result-type (v1.1.0 => v1.1.1)
- Upgrading phpoption/phpoption (1.9.0 => 1.9.1)
- Upgrading phpunit/php-code-coverage (9.2.24 => 9.2.25)
=> Composer update with 4 changes 2023-02-26

update/composer.lock
- Upgrading phpunit/phpunit (9.6.3 => 9.6.4)
=> Composer update with 1 changes 2023-02-28

update/composer.lock
- Upgrading symfony/console (v6.2.5 => v6.2.7)
- Upgrading symfony/deprecation-contracts (v3.2.0 => v3.2.1)
- Upgrading symfony/error-handler (v6.2.5 => v6.2.7)
- Upgrading symfony/finder (v6.2.5 => v6.2.7)
- Upgrading symfony/options-resolver (v6.2.5 => v6.2.7)
- Upgrading symfony/process (v6.2.5 => v6.2.7)
- Upgrading symfony/service-contracts (v3.2.0 => v3.2.1)
- Upgrading symfony/string (v6.2.5 => v6.2.7)
- Upgrading symfony/translation (v6.2.5 => v6.2.7)
- Upgrading symfony/translation-contracts (v3.2.0 => v3.2.1)
- Upgrading symfony/var-dumper (v6.2.5 => v6.2.7)
=> Composer update with 11 changes 2023-03-01

update/composer.lock
- Upgrading phpunit/phpunit (10.0.13 => 10.0.14)
- Upgrading symfony/deprecation-contracts (v3.2.1 0121954 => v3.2.1 e2d1534)
- Upgrading symfony/service-contracts (v3.2.1 aee5f59 => v3.2.1 a8c9ced)
- Upgrading symfony/translation-contracts (v3.2.1 1f40e77 => v3.2.1 dfec258)
=> Composer update with 4 changes 2023-03-02

update/composer.lock
- Upgrading illuminate/bus (v10.1.5 => v10.2.0)
- Upgrading illuminate/cache (v10.1.5 => v10.2.0)
- Upgrading illuminate/collections (v10.1.5 => v10.2.0)
- Upgrading illuminate/conditionable (v10.1.5 => v10.2.0)
- Upgrading illuminate/config (v10.1.5 => v10.2.0)
- Upgrading illuminate/console (v10.1.5 => v10.2.0)
- Upgrading illuminate/container (v10.1.5 => v10.2.0)
- Upgrading illuminate/contracts (v10.1.5 => v10.2.0)
- Upgrading illuminate/events (v10.1.5 => v10.2.0)
- Upgrading illuminate/filesystem (v10.1.5 => v10.2.0)
- Upgrading illuminate/macroable (v10.1.5 => v10.2.0)
- Upgrading illuminate/pipeline (v10.1.5 => v10.2.0)
- Upgrading illuminate/process (v10.1.5 => v10.2.0)
- Upgrading illuminate/support (v10.1.5 => v10.2.0)
- Upgrading illuminate/testing (v10.1.5 => v10.2.0)
- …
=> Composer update with 16 changes 2023-03-03

update/composer.lock
- Upgrading filp/whoops (2.14.6 => 2.15.0)
=> Composer update with 1 changes 2023-03-04

update/composer.lock
- Upgrading nikic/php-parser (v4.15.3 => v4.15.4)
=> Composer update with 1 changes 2023-03-06

update/composer.lock
- Upgrading filp/whoops (2.15.0 => 2.15.1)
- Upgrading phpunit/php-code-coverage (10.0.1 => 10.0.2)
=> Composer update with 2 changes 2023-03-07

update/composer.lock
- Upgrading illuminate/bus (v10.2.0 => v10.3.1)
- Upgrading illuminate/cache (v10.2.0 => v10.3.1)
- Upgrading illuminate/collections (v10.2.0 => v10.3.1)
- Upgrading illuminate/conditionable (v10.2.0 => v10.3.1)
- Upgrading illuminate/config (v10.2.0 => v10.3.1)
- Upgrading illuminate/console (v10.2.0 => v10.3.1)
- Upgrading illuminate/container (v10.2.0 => v10.3.1)
- Upgrading illuminate/contracts (v10.2.0 => v10.3.1)
- Upgrading illuminate/events (v10.2.0 => v10.3.1)
- Upgrading illuminate/filesystem (v10.2.0 => v10.3.1)
- Upgrading illuminate/macroable (v10.2.0 => v10.3.1)
- Upgrading illuminate/pipeline (v10.2.0 => v10.3.1)
- Upgrading illuminate/process (v10.2.0 => v10.3.1)
- Upgrading illuminate/support (v10.2.0 => v10.3.1)
- Upgrading illuminate/testing (v10.2.0 => v10.3.1)
- …
=> Composer update with 16 changes 2023-03-08

update/composer.lock
- Upgrading illuminate/bus (v10.3.1 => v10.3.2)
- Upgrading illuminate/cache (v10.3.1 => v10.3.2)
- Upgrading illuminate/collections (v10.3.1 => v10.3.2)
- Upgrading illuminate/conditionable (v10.3.1 => v10.3.2)
- Upgrading illuminate/config (v10.3.1 => v10.3.2)
- Upgrading illuminate/console (v10.3.1 => v10.3.2)
- Upgrading illuminate/container (v10.3.1 => v10.3.2)
- Upgrading illuminate/contracts (v10.3.1 => v10.3.2)
- Upgrading illuminate/events (v10.3.1 => v10.3.2)
- Upgrading illuminate/filesystem (v10.3.1 => v10.3.2)
- Upgrading illuminate/macroable (v10.3.1 => v10.3.2)
- Upgrading illuminate/pipeline (v10.3.1 => v10.3.2)
- Upgrading illuminate/process (v10.3.1 => v10.3.2)
- Upgrading illuminate/support (v10.3.1 => v10.3.2)
- Upgrading illuminate/testing (v10.3.1 => v10.3.2)
- …
=> Composer update with 17 changes 2023-03-09

update/composer.lock
- Upgrading guzzlehttp/psr7 (2.4.3 => 2.4.4)
- Upgrading illuminate/bus (v10.3.2 => v10.3.3)
- Upgrading illuminate/cache (v10.3.2 => v10.3.3)
- Upgrading illuminate/collections (v10.3.2 => v10.3.3)
- Upgrading illuminate/conditionable (v10.3.2 => v10.3.3)
- Upgrading illuminate/config (v10.3.2 => v10.3.3)
- Upgrading illuminate/console (v10.3.2 => v10.3.3)
- Upgrading illuminate/container (v10.3.2 => v10.3.3)
- Upgrading illuminate/contracts (v10.3.2 => v10.3.3)
- Upgrading illuminate/events (v10.3.2 => v10.3.3)
- Upgrading illuminate/filesystem (v10.3.2 => v10.3.3)
- Upgrading illuminate/macroable (v10.3.2 => v10.3.3)
- Upgrading illuminate/pipeline (v10.3.2 => v10.3.3)
- Upgrading illuminate/process (v10.3.2 => v10.3.3)
- Upgrading illuminate/support (v10.3.2 => v10.3.3)
- Upgrading …
=> Composer update with 19 changes 2023-03-10

update/composer.lock
- Upgrading knplabs/github-api (v3.10.0 => v3.11.0)
=> Composer update with 1 changes 2023-03-12

update/composer.lock
- Upgrading phpunit/phpunit (10.0.15 => 10.0.16)
=> Composer update with 1 changes 2023-03-14

update/composer.lock
- Upgrading illuminate/bus (v10.3.3 => v10.4.0)
- Upgrading illuminate/cache (v10.3.3 => v10.4.0)
- Upgrading illuminate/collections (v10.3.3 => v10.4.0)
- Upgrading illuminate/conditionable (v10.3.3 => v10.4.0)
- Upgrading illuminate/config (v10.3.3 => v10.4.0)
- Upgrading illuminate/console (v10.3.3 => v10.4.0)
- Upgrading illuminate/container (v10.3.3 => v10.4.0)
- Upgrading illuminate/contracts (v10.3.3 => v10.4.0)
- Upgrading illuminate/events (v10.3.3 => v10.4.0)
- Upgrading illuminate/filesystem (v10.3.3 => v10.4.0)
- Upgrading illuminate/macroable (v10.3.3 => v10.4.0)
- Upgrading illuminate/pipeline (v10.3.3 => v10.4.0)
- Upgrading illuminate/process (v10.3.3 => v10.4.0)
- Upgrading illuminate/support (v10.3.3 => v10.4.0)
- Upgrading illuminate/testing (v10.3.3 => v10.4.0)
- …
=> Composer update with 20 changes 2023-03-18

update/composer.lock
- Upgrading illuminate/bus (v10.4.0 => v10.4.1)
- Upgrading illuminate/cache (v10.4.0 => v10.4.1)
- Upgrading illuminate/collections (v10.4.0 => v10.4.1)
- Upgrading illuminate/conditionable (v10.4.0 => v10.4.1)
- Upgrading illuminate/config (v10.4.0 => v10.4.1)
- Upgrading illuminate/console (v10.4.0 => v10.4.1)
- Upgrading illuminate/container (v10.4.0 => v10.4.1)
- Upgrading illuminate/contracts (v10.4.0 => v10.4.1)
- Upgrading illuminate/events (v10.4.0 => v10.4.1)
- Upgrading illuminate/filesystem (v10.4.0 => v10.4.1)
- Upgrading illuminate/macroable (v10.4.0 => v10.4.1)
- Upgrading illuminate/pipeline (v10.4.0 => v10.4.1)
- Upgrading illuminate/process (v10.4.0 => v10.4.1)
- Upgrading illuminate/support (v10.4.0 => v10.4.1)
- Upgrading illuminate/testing (v10.4.0 => v10.4.1)
- …
=> Composer update with 16 changes 2023-03-19

update/composer.lock
- Upgrading phpunit/phpunit (10.0.16 => 10.0.17)
=> Composer update with 1 changes 2023-03-21

update/composer.lock
- Upgrading laravel-zero/framework (v10.0.1 => v10.0.2)
- Upgrading nunomaduro/collision (v6.4.0 => v7.3.2)
=> Composer update with 2 changes 2023-03-22

update/composer.lock
- Upgrading phpunit/phpunit (10.0.17 => 10.0.18)
=> Composer update with 1 changes 2023-03-23

update/composer.lock
- Upgrading nunomaduro/collision (v7.3.2 => v7.3.3)
- Upgrading sebastian/diff (5.0.0 => 5.0.1)
=> Composer update with 2 changes 2023-03-24

update/composer.lock
- Upgrading phpunit/phpunit (10.0.18 => 10.0.19)
=> Composer update with 1 changes 2023-03-28

update/composer.lock
- Upgrading illuminate/bus (v10.4.1 => v10.5.0)
- Upgrading illuminate/cache (v10.4.1 => v10.5.0)
- Upgrading illuminate/collections (v10.4.1 => v10.5.0)
- Upgrading illuminate/conditionable (v10.4.1 => v10.5.0)
- Upgrading illuminate/config (v10.4.1 => v10.5.0)
- Upgrading illuminate/console (v10.4.1 => v10.5.0)
- Upgrading illuminate/container (v10.4.1 => v10.5.0)
- Upgrading illuminate/contracts (v10.4.1 => v10.5.0)
- Upgrading illuminate/events (v10.4.1 => v10.5.0)
- Upgrading illuminate/filesystem (v10.4.1 => v10.5.0)
- Upgrading illuminate/macroable (v10.4.1 => v10.5.0)
- Upgrading illuminate/pipeline (v10.4.1 => v10.5.0)
- Upgrading illuminate/process (v10.4.1 => v10.5.0)
- Upgrading illuminate/support (v10.4.1 => v10.5.0)
- Upgrading illuminate/testing (v10.4.1 => v10.5.0)
- …
=> Composer update with 16 changes 2023-03-29

update/composer.lock
- Upgrading illuminate/bus (v10.5.0 => v10.5.1)
- Upgrading illuminate/cache (v10.5.0 => v10.5.1)
- Upgrading illuminate/collections (v10.5.0 => v10.5.1)
- Upgrading illuminate/conditionable (v10.5.0 => v10.5.1)
- Upgrading illuminate/config (v10.5.0 => v10.5.1)
- Upgrading illuminate/console (v10.5.0 => v10.5.1)
- Upgrading illuminate/container (v10.5.0 => v10.5.1)
- Upgrading illuminate/contracts (v10.5.0 => v10.5.1)
- Upgrading illuminate/events (v10.5.0 => v10.5.1)
- Upgrading illuminate/filesystem (v10.5.0 => v10.5.1)
- Upgrading illuminate/macroable (v10.5.0 => v10.5.1)
- Upgrading illuminate/pipeline (v10.5.0 => v10.5.1)
- Upgrading illuminate/process (v10.5.0 => v10.5.1)
- Upgrading illuminate/support (v10.5.0 => v10.5.1)
- Upgrading illuminate/testing (v10.5.0 => v10.5.1)
- …
=> Composer update with 16 changes 2023-03-30

update/composer.lock
- Upgrading nunomaduro/collision (v7.3.3 => v7.4.0)
- Upgrading php-http/discovery (1.15.2 => 1.15.3)
- Upgrading symfony/console (v6.2.7 => v6.2.8)
- Upgrading symfony/event-dispatcher (v6.2.7 => v6.2.8)
- Upgrading symfony/process (v6.2.7 => v6.2.8)
- Upgrading symfony/string (v6.2.7 => v6.2.8)
- Upgrading symfony/translation (v6.2.7 => v6.2.8)
- Upgrading symfony/var-dumper (v6.2.7 => v6.2.8)
=> Composer update with 8 changes 2023-04-01

update/composer.lock
- Upgrading illuminate/bus (v10.5.1 => v10.6.1)
- Upgrading illuminate/cache (v10.5.1 => v10.6.1)
- Upgrading illuminate/collections (v10.5.1 => v10.6.1)
- Upgrading illuminate/conditionable (v10.5.1 => v10.6.1)
- Upgrading illuminate/config (v10.5.1 => v10.6.1)
- Upgrading illuminate/console (v10.5.1 => v10.6.1)
- Upgrading illuminate/container (v10.5.1 => v10.6.1)
- Upgrading illuminate/contracts (v10.5.1 => v10.6.1)
- Upgrading illuminate/events (v10.5.1 => v10.6.1)
- Upgrading illuminate/filesystem (v10.5.1 => v10.6.1)
- Upgrading illuminate/macroable (v10.5.1 => v10.6.1)
- Upgrading illuminate/pipeline (v10.5.1 => v10.6.1)
- Upgrading illuminate/process (v10.5.1 => v10.6.1)
- Upgrading illuminate/support (v10.5.1 => v10.6.1)
- Upgrading illuminate/testing (v10.5.1 => v10.6.1)
- …
=> Composer update with 17 changes 2023-04-05

update/composer.lock
- Upgrading illuminate/bus (v10.6.1 => v10.6.2)
- Upgrading illuminate/cache (v10.6.1 => v10.6.2)
- Upgrading illuminate/collections (v10.6.1 => v10.6.2)
- Upgrading illuminate/conditionable (v10.6.1 => v10.6.2)
- Upgrading illuminate/config (v10.6.1 => v10.6.2)
- Upgrading illuminate/console (v10.6.1 => v10.6.2)
- Upgrading illuminate/container (v10.6.1 => v10.6.2)
- Upgrading illuminate/contracts (v10.6.1 => v10.6.2)
- Upgrading illuminate/events (v10.6.1 => v10.6.2)
- Upgrading illuminate/filesystem (v10.6.1 => v10.6.2)
- Upgrading illuminate/macroable (v10.6.1 => v10.6.2)
- Upgrading illuminate/pipeline (v10.6.1 => v10.6.2)
- Upgrading illuminate/process (v10.6.1 => v10.6.2)
- Upgrading illuminate/support (v10.6.1 => v10.6.2)
- Upgrading illuminate/testing (v10.6.1 => v10.6.2)
- …
=> Composer update with 16 changes 2023-04-06

update/composer.lock
- Upgrading psr/http-client (1.0.1 => 1.0.2)
- Upgrading psr/http-factory (1.0.1 => 1.0.2)
=> Composer update with 2 changes 2023-04-11

update/composer.lock
- Upgrading illuminate/bus (v10.6.2 => v10.7.1)
- Upgrading illuminate/cache (v10.6.2 => v10.7.1)
- Upgrading illuminate/collections (v10.6.2 => v10.7.1)
- Upgrading illuminate/conditionable (v10.6.2 => v10.7.1)
- Upgrading illuminate/config (v10.6.2 => v10.7.1)
- Upgrading illuminate/console (v10.6.2 => v10.7.1)
- Upgrading illuminate/container (v10.6.2 => v10.7.1)
- Upgrading illuminate/contracts (v10.6.2 => v10.7.1)
- Upgrading illuminate/events (v10.6.2 => v10.7.1)
- Upgrading illuminate/filesystem (v10.6.2 => v10.7.1)
- Upgrading illuminate/macroable (v10.6.2 => v10.7.1)
- Upgrading illuminate/pipeline (v10.6.2 => v10.7.1)
- Upgrading illuminate/process (v10.6.2 => v10.7.1)
- Upgrading illuminate/support (v10.6.2 => v10.7.1)
- Upgrading illuminate/testing (v10.6.2 => v10.7.1)
- …
=> Composer update with 18 changes 2023-04-12

update/composer.lock
- Upgrading filp/whoops (2.15.1 => 2.15.2)
=> Composer update with 1 changes 2023-04-13

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.0.2 => 10.1.0)
- Upgrading symfony/error-handler (v6.2.7 => v6.2.9)
=> Composer update with 2 changes 2023-04-14

update/composer.lock
- Upgrading nunomaduro/collision (v7.4.0 => v7.5.0)
- Upgrading php-http/client-common (2.6.0 => 2.6.1)
- Upgrading php-http/httplug (2.3.0 => 2.4.0)
- Upgrading php-http/message (1.13.0 => 1.14.0)
- Upgrading php-http/message-factory (v1.0.2 => 1.1.0)
- Upgrading phpunit/phpunit (10.0.19 => 10.1.0)
=> Composer update with 6 changes 2023-04-15

update/composer.lock
- Upgrading brick/math (0.10.2 => 0.11.0)
- Upgrading ramsey/uuid (4.7.3 => 4.7.4)
=> Composer update with 2 changes 2023-04-16

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.5.0 => 7.5.1)
- Upgrading guzzlehttp/psr7 (2.4.4 => 2.5.0)
- Upgrading phpunit/php-code-coverage (10.1.0 => 10.1.1)
- Upgrading phpunit/phpunit (10.1.0 => 10.1.1)
=> Composer update with 4 changes 2023-04-18

update/composer.lock
- Upgrading illuminate/bus (v10.7.1 => v10.8.0)
- Upgrading illuminate/cache (v10.7.1 => v10.8.0)
- Upgrading illuminate/collections (v10.7.1 => v10.8.0)
- Upgrading illuminate/conditionable (v10.7.1 => v10.8.0)
- Upgrading illuminate/config (v10.7.1 => v10.8.0)
- Upgrading illuminate/console (v10.7.1 => v10.8.0)
- Upgrading illuminate/container (v10.7.1 => v10.8.0)
- Upgrading illuminate/contracts (v10.7.1 => v10.8.0)
- Upgrading illuminate/events (v10.7.1 => v10.8.0)
- Upgrading illuminate/filesystem (v10.7.1 => v10.8.0)
- Upgrading illuminate/macroable (v10.7.1 => v10.8.0)
- Upgrading illuminate/pipeline (v10.7.1 => v10.8.0)
- Upgrading illuminate/process (v10.7.1 => v10.8.0)
- Upgrading illuminate/support (v10.7.1 => v10.8.0)
- Upgrading illuminate/testing (v10.7.1 => v10.8.0)
- …
=> Composer update with 16 changes 2023-04-19

update/composer.lock
- Upgrading nunomaduro/collision (v7.5.0 => v7.5.2)
- Upgrading phpunit/phpunit (10.1.1 => 10.1.2)
=> Composer update with 2 changes 2023-04-23

update/composer.lock
- Upgrading illuminate/bus (v10.8.0 => v10.9.0)
- Upgrading illuminate/cache (v10.8.0 => v10.9.0)
- Upgrading illuminate/collections (v10.8.0 => v10.9.0)
- Upgrading illuminate/conditionable (v10.8.0 => v10.9.0)
- Upgrading illuminate/config (v10.8.0 => v10.9.0)
- Upgrading illuminate/console (v10.8.0 => v10.9.0)
- Upgrading illuminate/container (v10.8.0 => v10.9.0)
- Upgrading illuminate/contracts (v10.8.0 => v10.9.0)
- Upgrading illuminate/events (v10.8.0 => v10.9.0)
- Upgrading illuminate/filesystem (v10.8.0 => v10.9.0)
- Upgrading illuminate/macroable (v10.8.0 => v10.9.0)
- Upgrading illuminate/pipeline (v10.8.0 => v10.9.0)
- Upgrading illuminate/process (v10.8.0 => v10.9.0)
- Upgrading illuminate/support (v10.8.0 => v10.9.0)
- Upgrading illuminate/testing (v10.8.0 => v10.9.0)
- …
=> Composer update with 16 changes 2023-04-26

update/composer.lock
- Upgrading php-http/discovery (1.15.3 => 1.17.0)
=> Composer update with 1 changes 2023-04-27

update/composer.lock
- Upgrading php-http/cache-plugin (1.7.5 => 1.8.0)
- Upgrading php-http/multipart-stream-builder (1.2.0 => 1.3.0)
- Upgrading symfony/console (v6.2.8 => v6.2.10)
- Upgrading symfony/error-handler (v6.2.9 => v6.2.10)
- Upgrading symfony/process (v6.2.8 => v6.2.10)
- Upgrading symfony/var-dumper (v6.2.8 => v6.2.10)
=> Composer update with 6 changes 2023-04-29

update/composer.lock
- Upgrading sebastian/diff (5.0.1 => 5.0.3)
=> Composer update with 1 changes 2023-05-03

update/composer.lock
- Upgrading php-http/discovery (1.17.0 => 1.18.0)
=> Composer update with 1 changes 2023-05-04

update/composer.lock
- Upgrading league/flysystem (3.14.0 => 3.15.1)
- Locking league/flysystem-local (3.15.0)
=> Composer update with 2 changes 2023-05-05

update/composer.lock
- Upgrading phpunit/php-file-iterator (4.0.1 => 4.0.2)
=> Composer update with 1 changes 2023-05-08

update/composer.lock
- Upgrading illuminate/bus (v10.9.0 => v10.10.0)
- Upgrading illuminate/cache (v10.9.0 => v10.10.0)
- Upgrading illuminate/collections (v10.9.0 => v10.10.0)
- Upgrading illuminate/conditionable (v10.9.0 => v10.10.0)
- Upgrading illuminate/config (v10.9.0 => v10.10.0)
- Upgrading illuminate/console (v10.9.0 => v10.10.0)
- Upgrading illuminate/container (v10.9.0 => v10.10.0)
- Upgrading illuminate/contracts (v10.9.0 => v10.10.0)
- Upgrading illuminate/events (v10.9.0 => v10.10.0)
- Upgrading illuminate/filesystem (v10.9.0 => v10.10.0)
- Upgrading illuminate/macroable (v10.9.0 => v10.10.0)
- Upgrading illuminate/pipeline (v10.9.0 => v10.10.0)
- Upgrading illuminate/process (v10.9.0 => v10.10.0)
- Upgrading illuminate/support (v10.9.0 => v10.10.0)
- Upgrading illuminate/testing (v10.9.0 => …
=> Composer update with 17 changes 2023-05-10

update/composer.lock
- Upgrading php-http/message (1.14.0 => 1.15.0)
=> Composer update with 1 changes 2023-05-11

update/composer.lock
- Upgrading illuminate/bus (v10.10.0 => v10.10.1)
- Upgrading illuminate/cache (v10.10.0 => v10.10.1)
- Upgrading illuminate/collections (v10.10.0 => v10.10.1)
- Upgrading illuminate/conditionable (v10.10.0 => v10.10.1)
- Upgrading illuminate/config (v10.10.0 => v10.10.1)
- Upgrading illuminate/console (v10.10.0 => v10.10.1)
- Upgrading illuminate/container (v10.10.0 => v10.10.1)
- Upgrading illuminate/contracts (v10.10.0 => v10.10.1)
- Upgrading illuminate/events (v10.10.0 => v10.10.1)
- Upgrading illuminate/filesystem (v10.10.0 => v10.10.1)
- Upgrading illuminate/macroable (v10.10.0 => v10.10.1)
- Upgrading illuminate/pipeline (v10.10.0 => v10.10.1)
- Upgrading illuminate/process (v10.10.0 => v10.10.1)
- Upgrading illuminate/support (v10.10.0 => v10.10.1) …
=> Composer update with 17 changes 2023-05-12

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.5.1 => 7.6.0)
=> Composer update with 1 changes 2023-05-15

update/composer.lock
- Upgrading illuminate/bus (v10.10.1 => v10.11.0)
- Upgrading illuminate/cache (v10.10.1 => v10.11.0)
- Upgrading illuminate/collections (v10.10.1 => v10.11.0)
- Upgrading illuminate/conditionable (v10.10.1 => v10.11.0)
- Upgrading illuminate/config (v10.10.1 => v10.11.0)
- Upgrading illuminate/console (v10.10.1 => v10.11.0)
- Upgrading illuminate/container (v10.10.1 => v10.11.0)
- Upgrading illuminate/contracts (v10.10.1 => v10.11.0)
- Upgrading illuminate/events (v10.10.1 => v10.11.0)
- Upgrading illuminate/filesystem (v10.10.1 => v10.11.0)
- Upgrading illuminate/macroable (v10.10.1 => v10.11.0)
- Upgrading illuminate/pipeline (v10.10.1 => v10.11.0)
- Upgrading illuminate/process (v10.10.1 => v10.11.0)
- Upgrading illuminate/support (v10.10.1 => v10.11.0) …
=> Composer update with 16 changes 2023-05-17

update/composer.lock
- Upgrading php-http/client-common (2.6.1 => 2.7.0)
- Upgrading php-http/discovery (1.18.0 => 1.18.1)
- Upgrading php-http/message (1.15.0 => 1.16.0)
=> Composer update with 3 changes 2023-05-18

update/composer.lock
- Upgrading nikic/php-parser (v4.15.4 => v4.15.5)
=> Composer update with 1 changes 2023-05-20

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.6.1 => 7.7.0)
- Upgrading guzzlehttp/promises (1.5.2 => 2.0.0)
=> Composer update with 2 changes 2023-05-22

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.1 => 10.1.2)
=> Composer update with 1 changes 2023-05-23

update/composer.lock
- Upgrading illuminate/bus (v10.11.0 => v10.12.0)
- Upgrading illuminate/cache (v10.11.0 => v10.12.0)
- Upgrading illuminate/collections (v10.11.0 => v10.12.0)
- Upgrading illuminate/conditionable (v10.11.0 => v10.12.0)
- Upgrading illuminate/config (v10.11.0 => v10.12.0)
- Upgrading illuminate/console (v10.11.0 => v10.12.0)
- Upgrading illuminate/container (v10.11.0 => v10.12.0)
- Upgrading illuminate/contracts (v10.11.0 => v10.12.0)
- Upgrading illuminate/events (v10.11.0 => v10.12.0)
- Upgrading illuminate/filesystem (v10.11.0 => v10.12.0)
- Upgrading illuminate/macroable (v10.11.0 => v10.12.0)
- Upgrading illuminate/pipeline (v10.11.0 => v10.12.0)
- Upgrading illuminate/process (v10.11.0 => v10.12.0)
- Upgrading illuminate/support (v10.11.0 => v10.12.0) …
=> Composer update with 17 changes 2023-05-24

update/composer.lock
- Upgrading laravel-zero/foundation (v10.11.0 => v10.12.0)
=> Composer update with 1 changes 2023-05-25

update/composer.lock
- Upgrading jolicode/jolinotif (v2.5.0 => v2.5.2)
=> Composer update with 1 changes 2023-05-26

update/composer.lock
- Upgrading nesbot/carbon (2.66.0 => 2.67.0)
- Upgrading symfony/console (v6.2.10 => v6.2.11)
- Upgrading symfony/error-handler (v6.2.10 => v6.2.11)
- Upgrading symfony/process (v6.2.10 => v6.2.11)
- Upgrading symfony/translation (v6.2.8 => v6.2.11)
- Upgrading symfony/var-dumper (v6.2.10 => v6.2.11)
=> Composer update with 6 changes 2023-05-30

update/composer.lock
- Upgrading illuminate/bus (v10.12.0 => v10.13.0)
- Upgrading illuminate/cache (v10.12.0 => v10.13.0)
- Upgrading illuminate/collections (v10.12.0 => v10.13.0)
- Upgrading illuminate/conditionable (v10.12.0 => v10.13.0)
- Upgrading illuminate/console (v10.12.0 => v10.13.0)
- Upgrading illuminate/container (v10.12.0 => v10.13.0)
- Upgrading illuminate/contracts (v10.12.0 => v10.13.0)
- Upgrading illuminate/events (v10.12.0 => v10.13.0)
- Upgrading illuminate/filesystem (v10.12.0 => v10.13.0)
- Upgrading illuminate/macroable (v10.12.0 => v10.13.0)
- Upgrading illuminate/pipeline (v10.12.0 => v10.13.0)
- Upgrading illuminate/process (v10.12.0 => v10.13.0)
- Upgrading illuminate/support (v10.12.0 => v10.13.0)
- Upgrading illuminate/testing (v10.12.0 => v10.13.0)
- Upgrading illuminate/view …
=> Composer update with 28 changes 2023-05-31

update/composer.lock
- Upgrading illuminate/bus (v10.13.0 => v10.13.1)
- Upgrading illuminate/cache (v10.13.0 => v10.13.1)
- Upgrading illuminate/collections (v10.13.0 => v10.13.1)
- Upgrading illuminate/conditionable (v10.13.0 => v10.13.1)
- Upgrading illuminate/config (v10.12.0 => v10.13.1)
- Upgrading illuminate/console (v10.13.0 => v10.13.1)
- Upgrading illuminate/container (v10.13.0 => v10.13.1)
- Upgrading illuminate/contracts (v10.13.0 => v10.13.1)
- Upgrading illuminate/events (v10.13.0 => v10.13.1)
- Upgrading illuminate/filesystem (v10.13.0 => v10.13.1)
- Upgrading illuminate/macroable (v10.13.0 => v10.13.1)
- Upgrading illuminate/pipeline (v10.13.0 => v10.13.1)
- Upgrading illuminate/process (v10.13.0 => v10.13.1)
- Upgrading illuminate/support (v10.13.0 => v10.13.1) …
=> Composer update with 17 changes 2023-06-03
