update/composer.lock

- Upgrading illuminate/bus (v8.16.0 => v8.16.1)
- Upgrading illuminate/cache (v8.16.0 => v8.16.1)
- Upgrading illuminate/collections (v8.16.0 => v8.16.1)
- Upgrading illuminate/config (v8.16.0 => v8.16.1)
- Upgrading illuminate/console (v8.16.0 => v8.16.1)
- Upgrading illuminate/container (v8.16.0 => v8.16.1)
- Upgrading illuminate/contracts (v8.16.0 => v8.16.1)
- Upgrading illuminate/events (v8.16.0 => v8.16.1)
- Upgrading illuminate/filesystem (v8.16.0 => v8.16.1)
- Upgrading illuminate/macroable (v8.15.0 => v8.16.1)
- Upgrading illuminate/pipeline (v8.16.0 => v8.16.1)
- Upgrading illuminate/support (v8.16.0 => v8.16.1)
- Upgrading illuminate/testing (v8.16.0 => v8.16.1)

composer update 2020-11-26

---

update/composer.lock

- Upgrading symfony/cache (v5.1.8 => v5.1.9)
- Upgrading symfony/console (v5.1.8 => v5.1.9)
- Upgrading symfony/error-handler (v5.1.8 => v5.1.9)
- Upgrading symfony/finder (v5.1.8 => v5.1.9)
- Upgrading symfony/options-resolver (v5.1.8 => v5.1.9)
- Upgrading symfony/process (v5.1.8 => v5.1.9)
- Upgrading symfony/string (v5.1.8 => v5.1.9)
- Upgrading symfony/translation (v5.1.8 => v5.1.9)
- Upgrading symfony/var-dumper (v5.1.8 => v5.1.9)
- Upgrading symfony/var-exporter (v5.1.8 => v5.1.9)

composer update 2020-11-30

---

update/composer.lock

- Upgrading phar-io/version (3.0.2 => 3.0.3)
- Upgrading symfony/cache (v5.1.9 => v5.2.0)
- Upgrading symfony/console (v5.1.9 => v5.2.0)
- Upgrading symfony/error-handler (v5.1.9 => v5.2.0)
- Upgrading symfony/finder (v5.1.9 => v5.2.0)
- Upgrading symfony/options-resolver (v5.1.9 => v5.2.0)
- Upgrading symfony/process (v5.1.9 => v5.2.0)
- Upgrading symfony/string (v5.1.9 => v5.2.0)
- Upgrading symfony/translation (v5.1.9 => v5.2.0)
- Upgrading symfony/var-dumper (v5.1.9 => v5.2.0)
- Upgrading symfony/var-exporter (v5.1.9 => v5.2.0)

composer update 2020-12-01

---

update/composer.lock

- Upgrading phar-io/version (3.0.3 => 3.0.4)

composer update 2020-12-14

---

update/composer.lock

- Upgrading illuminate/bus (v8.23.1 => v8.24.0)
- Upgrading illuminate/cache (v8.23.1 => v8.24.0)
- Upgrading illuminate/collections (v8.23.1 => v8.24.0)
- Upgrading illuminate/config (v8.23.1 => v8.24.0)
- Upgrading illuminate/console (v8.23.1 => v8.24.0)
- Upgrading illuminate/container (v8.23.1 => v8.24.0)
- Upgrading illuminate/contracts (v8.23.1 => v8.24.0)
- Upgrading illuminate/events (v8.23.1 => v8.24.0)
- Upgrading illuminate/filesystem (v8.23.1 => v8.24.0)
- Upgrading illuminate/macroable (v8.23.1 => v8.24.0)
- Upgrading illuminate/pipeline (v8.23.1 => v8.24.0)
- Upgrading illuminate/support (v8.23.1 => v8.24.0)
- Upgrading illuminate/testing (v8.23.1 => v8.24.0)
- Upgrading ramsey/collection (1.1.2 => 1.1.3)

composer update 2021-01-22

---

update/composer.lock

- Upgrading illuminate/bus (v8.28.1 => v8.29.0)
- Upgrading illuminate/cache (v8.28.1 => v8.29.0)
- Upgrading illuminate/collections (v8.28.1 => v8.29.0)
- Upgrading illuminate/config (v8.28.1 => v8.29.0)
- Upgrading illuminate/console (v8.28.1 => v8.29.0)
- Upgrading illuminate/container (v8.28.1 => v8.29.0)
- Upgrading illuminate/contracts (v8.28.1 => v8.29.0)
- Upgrading illuminate/events (v8.28.1 => v8.29.0)
- Upgrading illuminate/filesystem (v8.28.1 => v8.29.0)
- Upgrading illuminate/macroable (v8.28.1 => v8.29.0)
- Upgrading illuminate/pipeline (v8.28.1 => v8.29.0)
- Upgrading illuminate/support (v8.28.1 => v8.29.0)
- Upgrading illuminate/testing (v8.28.1 => v8.29.0)
- Upgrading phar-io/version (3.0.4 => 3.1.0)

composer update 2021-02-24

---

update/composer.lock

- Upgrading illuminate/bus (v8.29.0 => v8.30.0)
- Upgrading illuminate/cache (v8.29.0 => v8.30.0)
- Upgrading illuminate/collections (v8.29.0 => v8.30.0)
- Upgrading illuminate/config (v8.29.0 => v8.30.0)
- Upgrading illuminate/console (v8.29.0 => v8.30.0)
- Upgrading illuminate/container (v8.29.0 => v8.30.0)
- Upgrading illuminate/contracts (v8.29.0 => v8.30.0)
- Upgrading illuminate/events (v8.29.0 => v8.30.0)
- Upgrading illuminate/filesystem (v8.29.0 => v8.30.0)
- Upgrading illuminate/macroable (v8.29.0 => v8.30.0)
- Upgrading illuminate/pipeline (v8.29.0 => v8.30.0)
- Upgrading illuminate/support (v8.29.0 => v8.30.0)
- Upgrading illuminate/testing (v8.29.0 => v8.30.0)

composer update 2021-03-03

---

update/composer.lock

- Upgrading illuminate/bus (v8.30.0 => v8.30.1)
- Upgrading illuminate/cache (v8.30.0 => v8.30.1)
- Upgrading illuminate/collections (v8.30.0 => v8.30.1)
- Upgrading illuminate/config (v8.30.0 => v8.30.1)
- Upgrading illuminate/console (v8.30.0 => v8.30.1)
- Upgrading illuminate/container (v8.30.0 => v8.30.1)
- Upgrading illuminate/contracts (v8.30.0 => v8.30.1)
- Upgrading illuminate/events (v8.30.0 => v8.30.1)
- Upgrading illuminate/filesystem (v8.30.0 => v8.30.1)
- Upgrading illuminate/macroable (v8.30.0 => v8.30.1)
- Upgrading illuminate/pipeline (v8.30.0 => v8.30.1)
- Upgrading illuminate/support (v8.30.0 => v8.30.1)
- Upgrading illuminate/testing (v8.30.0 => v8.30.1)

composer update 2021-03-04

---

update/composer.lock

- Upgrading illuminate/bus (v8.30.1 => v8.31.0)
- Upgrading illuminate/cache (v8.30.1 => v8.31.0)
- Upgrading illuminate/collections (v8.30.1 => v8.31.0)
- Upgrading illuminate/config (v8.30.1 => v8.31.0)
- Upgrading illuminate/console (v8.30.1 => v8.31.0)
- Upgrading illuminate/container (v8.30.1 => v8.31.0)
- Upgrading illuminate/contracts (v8.30.1 => v8.31.0)
- Upgrading illuminate/events (v8.30.1 => v8.31.0)
- Upgrading illuminate/filesystem (v8.30.1 => v8.31.0)
- Upgrading illuminate/macroable (v8.30.1 => v8.31.0)
- Upgrading illuminate/pipeline (v8.30.1 => v8.31.0)
- Upgrading illuminate/support (v8.30.1 => v8.31.0)
- Upgrading illuminate/testing (v8.30.1 => v8.31.0)
- Upgrading symfony/cache (v5.2.3 => v5.2.4)
- Upgrading symfony/console (v5.2.3 => v5.2.4)
- Upgrading …

composer update 2021-03-05

---

update/composer.lock

- Upgrading illuminate/bus (v8.31.0 => v8.32.1)
- Upgrading illuminate/cache (v8.31.0 => v8.32.1)
- Upgrading illuminate/collections (v8.31.0 => v8.32.1)
- Upgrading illuminate/config (v8.31.0 => v8.32.1)
- Upgrading illuminate/console (v8.31.0 => v8.32.1)
- Upgrading illuminate/container (v8.31.0 => v8.32.1)
- Upgrading illuminate/contracts (v8.31.0 => v8.32.1)
- Upgrading illuminate/events (v8.31.0 => v8.32.1)
- Upgrading illuminate/filesystem (v8.31.0 => v8.32.1)
- Upgrading illuminate/macroable (v8.31.0 => v8.32.1)
- Upgrading illuminate/pipeline (v8.31.0 => v8.32.1)
- Upgrading illuminate/support (v8.31.0 => v8.32.1)
- Upgrading illuminate/testing (v8.31.0 => v8.32.1)
- Upgrading webmozart/assert (1.9.1 => 1.10.0)

composer update 2021-03-10

---

update/composer.lock

- Upgrading filp/whoops (2.9.2 => 2.10.0)
- Upgrading illuminate/bus (v8.32.1 => v8.33.1)
- Upgrading illuminate/cache (v8.32.1 => v8.33.1)
- Upgrading illuminate/collections (v8.32.1 => v8.33.1)
- Upgrading illuminate/config (v8.32.1 => v8.33.1)
- Upgrading illuminate/console (v8.32.1 => v8.33.1)
- Upgrading illuminate/container (v8.32.1 => v8.33.1)
- Upgrading illuminate/contracts (v8.32.1 => v8.33.1)
- Upgrading illuminate/events (v8.32.1 => v8.33.1)
- Upgrading illuminate/filesystem (v8.32.1 => v8.33.1)
- Upgrading illuminate/macroable (v8.32.1 => v8.33.1)
- Upgrading illuminate/pipeline (v8.32.1 => v8.33.1)
- Upgrading illuminate/support (v8.32.1 => v8.33.1)
- Upgrading illuminate/testing (v8.32.1 => v8.33.1)

composer update 2021-03-17

---

update/composer.lock

- Upgrading guzzlehttp/guzzle (7.2.0 => 7.3.0)
- Upgrading illuminate/bus (v8.33.1 => v8.34.0)
- Upgrading illuminate/cache (v8.33.1 => v8.34.0)
- Upgrading illuminate/collections (v8.33.1 => v8.34.0)
- Upgrading illuminate/config (v8.33.1 => v8.34.0)
- Upgrading illuminate/console (v8.33.1 => v8.34.0)
- Upgrading illuminate/container (v8.33.1 => v8.34.0)
- Upgrading illuminate/contracts (v8.33.1 => v8.34.0)
- Upgrading illuminate/events (v8.33.1 => v8.34.0)
- Upgrading illuminate/filesystem (v8.33.1 => v8.34.0)
- Upgrading illuminate/macroable (v8.33.1 => v8.34.0)
- Upgrading illuminate/pipeline (v8.33.1 => v8.34.0)
- Upgrading illuminate/support (v8.33.1 => v8.34.0)
- Upgrading illuminate/testing (v8.33.1 => v8.34.0)
- Upgrading laravel-zero/foundation (v8.32.1 => v8.34.0)
- Upgrading …

composer update 2021-03-24

---

update/composer.lock

- Upgrading filp/whoops (2.11.0 => 2.12.0)
- Upgrading illuminate/bus (v8.34.0 => v8.35.1)
- Upgrading illuminate/cache (v8.34.0 => v8.35.1)
- Upgrading illuminate/collections (v8.34.0 => v8.35.1)
- Upgrading illuminate/config (v8.34.0 => v8.35.1)
- Upgrading illuminate/console (v8.34.0 => v8.35.1)
- Upgrading illuminate/container (v8.34.0 => v8.35.1)
- Upgrading illuminate/contracts (v8.34.0 => v8.35.1)
- Upgrading illuminate/events (v8.34.0 => v8.35.1)
- Upgrading illuminate/filesystem (v8.34.0 => v8.35.1)
- Upgrading illuminate/macroable (v8.34.0 => v8.35.1)
- Upgrading illuminate/pipeline (v8.34.0 => v8.35.1)
- Upgrading illuminate/support (v8.34.0 => v8.35.1)
- Upgrading illuminate/testing (v8.34.0 => v8.35.1)

composer update 2021-03-31

---

update/composer.lock

- Upgrading illuminate/bus (v8.35.1 => v8.36.1)
- Upgrading illuminate/cache (v8.35.1 => v8.36.1)
- Upgrading illuminate/collections (v8.35.1 => v8.36.1)
- Upgrading illuminate/config (v8.35.1 => v8.36.1)
- Upgrading illuminate/console (v8.35.1 => v8.36.1)
- Upgrading illuminate/container (v8.35.1 => v8.36.1)
- Upgrading illuminate/contracts (v8.35.1 => v8.36.1)
- Upgrading illuminate/events (v8.35.1 => v8.36.1)
- Upgrading illuminate/filesystem (v8.35.1 => v8.36.1)
- Upgrading illuminate/macroable (v8.35.1 => v8.36.1)
- Upgrading illuminate/pipeline (v8.35.1 => v8.36.1)
- Upgrading illuminate/support (v8.35.1 => v8.36.1)
- Upgrading illuminate/testing (v8.35.1 => v8.36.1)
- Upgrading laravel-zero/foundation (v8.34.0 => v8.35.1)

composer update 2021-04-07

---

update/composer.lock

- Upgrading illuminate/bus (v8.36.1 => v8.36.2)
- Upgrading illuminate/cache (v8.36.1 => v8.36.2)
- Upgrading illuminate/collections (v8.36.1 => v8.36.2)
- Upgrading illuminate/config (v8.36.1 => v8.36.2)
- Upgrading illuminate/console (v8.36.1 => v8.36.2)
- Upgrading illuminate/container (v8.36.1 => v8.36.2)
- Upgrading illuminate/contracts (v8.36.1 => v8.36.2)
- Upgrading illuminate/events (v8.36.1 => v8.36.2)
- Upgrading illuminate/filesystem (v8.36.1 => v8.36.2)
- Upgrading illuminate/macroable (v8.36.1 => v8.36.2)
- Upgrading illuminate/pipeline (v8.36.1 => v8.36.2)
- Upgrading illuminate/support (v8.36.1 => v8.36.2)
- Upgrading illuminate/testing (v8.36.1 => v8.36.2)

composer update 2021-04-08

---

update/composer.lock

- Upgrading illuminate/bus (v8.36.2 => v8.37.0)
- Upgrading illuminate/cache (v8.36.2 => v8.37.0)
- Upgrading illuminate/collections (v8.36.2 => v8.37.0)
- Upgrading illuminate/config (v8.36.2 => v8.37.0)
- Upgrading illuminate/console (v8.36.2 => v8.37.0)
- Upgrading illuminate/container (v8.36.2 => v8.37.0)
- Upgrading illuminate/contracts (v8.36.2 => v8.37.0)
- Upgrading illuminate/events (v8.36.2 => v8.37.0)
- Upgrading illuminate/filesystem (v8.36.2 => v8.37.0)
- Upgrading illuminate/macroable (v8.36.2 => v8.37.0)
- Upgrading illuminate/pipeline (v8.36.2 => v8.37.0)
- Upgrading illuminate/support (v8.36.2 => v8.37.0)
- Upgrading illuminate/testing (v8.36.2 => v8.37.0)

composer update 2021-04-14

---

update/composer.lock

- Upgrading illuminate/bus (v8.37.0 => v8.38.0)
- Upgrading illuminate/cache (v8.37.0 => v8.38.0)
- Upgrading illuminate/collections (v8.37.0 => v8.38.0)
- Upgrading illuminate/config (v8.37.0 => v8.38.0)
- Upgrading illuminate/console (v8.37.0 => v8.38.0)
- Upgrading illuminate/container (v8.37.0 => v8.38.0)
- Upgrading illuminate/contracts (v8.37.0 => v8.38.0)
- Upgrading illuminate/events (v8.37.0 => v8.38.0)
- Upgrading illuminate/filesystem (v8.37.0 => v8.38.0)
- Upgrading illuminate/macroable (v8.37.0 => v8.38.0)
- Upgrading illuminate/pipeline (v8.37.0 => v8.38.0)
- Upgrading illuminate/support (v8.37.0 => v8.38.0)
- Upgrading illuminate/testing (v8.37.0 => v8.38.0)

composer update 2021-04-21

---

update/composer.lock

- Upgrading illuminate/bus (v8.38.0 => v8.39.0)
- Upgrading illuminate/cache (v8.38.0 => v8.39.0)
- Upgrading illuminate/collections (v8.38.0 => v8.39.0)
- Upgrading illuminate/config (v8.38.0 => v8.39.0)
- Upgrading illuminate/console (v8.38.0 => v8.39.0)
- Upgrading illuminate/container (v8.38.0 => v8.39.0)
- Upgrading illuminate/contracts (v8.38.0 => v8.39.0)
- Upgrading illuminate/events (v8.38.0 => v8.39.0)
- Upgrading illuminate/filesystem (v8.38.0 => v8.39.0)
- Upgrading illuminate/pipeline (v8.38.0 => v8.39.0)
- Upgrading illuminate/support (v8.38.0 => v8.39.0)
- Upgrading illuminate/testing (v8.38.0 => v8.39.0)

composer update 2021-04-28

---

update/composer.lock

- Upgrading illuminate/bus (v8.41.0 => v8.42.0)
- Upgrading illuminate/cache (v8.41.0 => v8.42.0)
- Upgrading illuminate/collections (v8.41.0 => v8.42.0)
- Upgrading illuminate/config (v8.41.0 => v8.42.0)
- Upgrading illuminate/console (v8.41.0 => v8.42.0)
- Upgrading illuminate/container (v8.41.0 => v8.42.0)
- Upgrading illuminate/contracts (v8.41.0 => v8.42.0)
- Upgrading illuminate/events (v8.41.0 => v8.42.0)
- Upgrading illuminate/filesystem (v8.41.0 => v8.42.0)
- Upgrading illuminate/macroable (v8.41.0 => v8.42.0)
- Upgrading illuminate/pipeline (v8.41.0 => v8.42.0)
- Upgrading illuminate/support (v8.41.0 => v8.42.0)
- Upgrading illuminate/testing (v8.41.0 => v8.42.0)

composer update 2021-05-19

---

update/composer.lock

- Upgrading illuminate/bus (v8.45.1 => v8.46.0)
- Upgrading illuminate/cache (v8.45.1 => v8.46.0)
- Upgrading illuminate/collections (v8.45.1 => v8.46.0)
- Upgrading illuminate/config (v8.45.1 => v8.46.0)
- Upgrading illuminate/console (v8.45.1 => v8.46.0)
- Upgrading illuminate/container (v8.45.1 => v8.46.0)
- Upgrading illuminate/contracts (v8.45.1 => v8.46.0)
- Upgrading illuminate/events (v8.45.1 => v8.46.0)
- Upgrading illuminate/filesystem (v8.45.1 => v8.46.0)
- Upgrading illuminate/macroable (v8.45.1 => v8.46.0)
- Upgrading illuminate/pipeline (v8.45.1 => v8.46.0)
- Upgrading illuminate/support (v8.45.1 => v8.46.0)
- Upgrading illuminate/testing (v8.45.1 => v8.46.0)

composer update 2021-06-09

---

Dockerfile
README.md
update/app/Commands/UpdateCommand.php

* Introduces a number of new configurations and changes to the code that allows changes to be applied to the same pull request. The benefit of this is that you don't end up with lots of environments for different pull requests in continuous deployment settings.
* The Dockerfile has also been simplified for increased speed.
* Introduces a possibility to define a commit message prefix, such as "[UPDATE] " or "[TASK] ".
This PR has only been tested with the v1 branch and PHP 7.4, not with v2 and PHP 8.
For a full overview of changes to configuration options, please check the changes to the readme file.

[FEATURE] Keep updating the same branch and pull request

---

update/composer.lock

- Upgrading filp/whoops (2.13.0 => 2.14.0)
- Upgrading illuminate/bus (v8.49.2 => v8.50.0)
- Upgrading illuminate/cache (v8.49.2 => v8.50.0)
- Upgrading illuminate/collections (v8.49.2 => v8.50.0)
- Upgrading illuminate/config (v8.49.2 => v8.50.0)
- Upgrading illuminate/console (v8.49.2 => v8.50.0)
- Upgrading illuminate/container (v8.49.2 => v8.50.0)
- Upgrading illuminate/contracts (v8.49.2 => v8.50.0)
- Upgrading illuminate/events (v8.49.2 => v8.50.0)
- Upgrading illuminate/filesystem (v8.49.2 => v8.50.0)
- Upgrading illuminate/macroable (v8.49.2 => v8.50.0)
- Upgrading illuminate/pipeline (v8.49.2 => v8.50.0)
- Upgrading illuminate/support (v8.49.2 => v8.50.0)
- Upgrading illuminate/testing (v8.49.2 => v8.50.0)

Composer update with 14 changes 2021-07-14

---

update/composer.lock

- Upgrading illuminate/bus (v8.50.0 => v8.51.0)
- Upgrading illuminate/cache (v8.50.0 => v8.51.0)
- Upgrading illuminate/collections (v8.50.0 => v8.51.0)
- Upgrading illuminate/config (v8.50.0 => v8.51.0)
- Upgrading illuminate/console (v8.50.0 => v8.51.0)
- Upgrading illuminate/container (v8.50.0 => v8.51.0)
- Upgrading illuminate/contracts (v8.50.0 => v8.51.0)
- Upgrading illuminate/events (v8.50.0 => v8.51.0)
- Upgrading illuminate/filesystem (v8.50.0 => v8.51.0)
- Upgrading illuminate/macroable (v8.50.0 => v8.51.0)
- Upgrading illuminate/pipeline (v8.50.0 => v8.51.0)
- Upgrading illuminate/support (v8.50.0 => v8.51.0)
- Upgrading illuminate/testing (v8.50.0 => v8.51.0)
- Upgrading phar-io/manifest (2.0.1 => 2.0.3)

Composer update with 14 changes 2021-07-21

---

update/composer.lock

- Upgrading illuminate/bus (v8.56.0 => v8.57.0)
- Upgrading illuminate/cache (v8.56.0 => v8.57.0)
- Upgrading illuminate/collections (v8.56.0 => v8.57.0)
- Upgrading illuminate/config (v8.56.0 => v8.57.0)
- Upgrading illuminate/console (v8.56.0 => v8.57.0)
- Upgrading illuminate/container (v8.56.0 => v8.57.0)
- Upgrading illuminate/contracts (v8.56.0 => v8.57.0)
- Upgrading illuminate/events (v8.56.0 => v8.57.0)
- Upgrading illuminate/filesystem (v8.56.0 => v8.57.0)
- Upgrading illuminate/macroable (v8.56.0 => v8.57.0)
- Upgrading illuminate/pipeline (v8.56.0 => v8.57.0)
- Upgrading illuminate/support (v8.56.0 => v8.57.0)
- Upgrading illuminate/testing (v8.56.0 => v8.57.0)

Composer update with 13 changes 2021-08-28

---

update/composer.lock

- Upgrading illuminate/bus (v8.57.0 => v8.58.0)
- Upgrading illuminate/cache (v8.57.0 => v8.58.0)
- Upgrading illuminate/collections (v8.57.0 => v8.58.0)
- Upgrading illuminate/config (v8.57.0 => v8.58.0)
- Upgrading illuminate/console (v8.57.0 => v8.58.0)
- Upgrading illuminate/container (v8.57.0 => v8.58.0)
- Upgrading illuminate/contracts (v8.57.0 => v8.58.0)
- Upgrading illuminate/events (v8.57.0 => v8.58.0)
- Upgrading illuminate/filesystem (v8.57.0 => v8.58.0)
- Upgrading illuminate/macroable (v8.57.0 => v8.58.0)
- Upgrading illuminate/pipeline (v8.57.0 => v8.58.0)
- Upgrading illuminate/support (v8.57.0 => v8.58.0)
- Upgrading illuminate/testing (v8.57.0 => v8.58.0)
- Upgrading phpunit/phpunit (9.5.8 => 9.5.9)

Composer update with 14 changes 2021-09-01

---

update/composer.lock

- Upgrading illuminate/bus (v8.68.1 => v8.69.0)
- Upgrading illuminate/cache (v8.68.1 => v8.69.0)
- Upgrading illuminate/collections (v8.68.1 => v8.69.0)
- Upgrading illuminate/config (v8.68.1 => v8.69.0)
- Upgrading illuminate/console (v8.68.1 => v8.69.0)
- Upgrading illuminate/container (v8.68.1 => v8.69.0)
- Upgrading illuminate/contracts (v8.68.1 => v8.69.0)
- Upgrading illuminate/events (v8.68.1 => v8.69.0)
- Upgrading illuminate/filesystem (v8.68.1 => v8.69.0)
- Upgrading illuminate/macroable (v8.68.1 => v8.69.0)
- Upgrading illuminate/pipeline (v8.68.1 => v8.69.0)
- Upgrading illuminate/support (v8.68.1 => v8.69.0)
- Upgrading illuminate/testing (v8.68.1 => v8.69.0)

Composer update with 13 changes 2021-11-03

---

update/composer.lock

- Upgrading illuminate/bus (v8.73.0 => v8.73.1)
- Upgrading illuminate/cache (v8.73.0 => v8.73.1)
- Upgrading illuminate/collections (v8.73.0 => v8.73.1)
- Upgrading illuminate/config (v8.73.0 => v8.73.1)
- Upgrading illuminate/console (v8.73.0 => v8.73.1)
- Upgrading illuminate/container (v8.73.0 => v8.73.1)
- Upgrading illuminate/contracts (v8.73.0 => v8.73.1)
- Upgrading illuminate/events (v8.73.0 => v8.73.1)
- Upgrading illuminate/filesystem (v8.73.0 => v8.73.1)
- Upgrading illuminate/macroable (v8.73.0 => v8.73.1)
- Upgrading illuminate/pipeline (v8.73.0 => v8.73.1)
- Upgrading illuminate/support (v8.73.0 => v8.73.1)
- Upgrading illuminate/testing (v8.73.0 => v8.73.1)

Composer update with 13 changes 2021-11-21

---

update/composer.lock

- Upgrading symfony/cache (v5.3.12 => v5.4.0)
- Upgrading symfony/console (v5.3.11 => v5.4.0)
- Upgrading symfony/error-handler (v5.3.11 => v5.4.0)
- Upgrading symfony/finder (v5.3.7 => v5.4.0)
- Upgrading symfony/options-resolver (v5.3.7 => v5.4.0)
- Upgrading symfony/process (v5.3.12 => v5.4.0)
- Upgrading symfony/string (v5.3.10 => v6.0.0)
- Upgrading symfony/translation (v5.3.11 => v5.4.0)
- Upgrading symfony/var-dumper (v5.3.11 => v5.4.0)
- Upgrading symfony/var-exporter (v5.3.11 => v6.0.0)

Composer update with 10 changes 2021-11-30

---

update/composer.lock

- Upgrading illuminate/bus (v8.76.2 => v8.77.1)
- Upgrading illuminate/cache (v8.76.2 => v8.77.1)
- Upgrading illuminate/collections (v8.76.2 => v8.77.1)
- Upgrading illuminate/config (v8.76.2 => v8.77.1)
- Upgrading illuminate/console (v8.76.2 => v8.77.1)
- Upgrading illuminate/container (v8.76.2 => v8.77.1)
- Upgrading illuminate/contracts (v8.76.2 => v8.77.1)
- Upgrading illuminate/events (v8.76.2 => v8.77.1)
- Upgrading illuminate/filesystem (v8.76.2 => v8.77.1)
- Upgrading illuminate/macroable (v8.76.2 => v8.77.1)
- Upgrading illuminate/pipeline (v8.76.2 => v8.77.1)
- Upgrading illuminate/support (v8.76.2 => v8.77.1)
- Upgrading illuminate/testing (v8.76.2 => v8.77.1)

Composer update with 13 changes 2021-12-22

---

update/composer.lock

- Upgrading illuminate/bus (v8.80.0 => v8.81.0)
- Upgrading illuminate/cache (v8.80.0 => v8.81.0)
- Upgrading illuminate/collections (v8.80.0 => v8.81.0)
- Upgrading illuminate/config (v8.80.0 => v8.81.0)
- Upgrading illuminate/console (v8.80.0 => v8.81.0)
- Upgrading illuminate/container (v8.80.0 => v8.81.0)
- Upgrading illuminate/contracts (v8.80.0 => v8.81.0)
- Upgrading illuminate/events (v8.80.0 => v8.81.0)
- Upgrading illuminate/filesystem (v8.80.0 => v8.81.0)
- Upgrading illuminate/macroable (v8.80.0 => v8.81.0)
- Upgrading illuminate/pipeline (v8.80.0 => v8.81.0)
- Upgrading illuminate/support (v8.80.0 => v8.81.0)
- Upgrading illuminate/testing (v8.80.0 => v8.81.0)

Composer update with 13 changes 2022-01-26

---

update/composer.lock

- Upgrading illuminate/bus (v8.81.0 => v8.82.0)
- Upgrading illuminate/cache (v8.81.0 => v8.82.0)
- Upgrading illuminate/collections (v8.81.0 => v8.82.0)
- Upgrading illuminate/config (v8.81.0 => v8.82.0)
- Upgrading illuminate/console (v8.81.0 => v8.82.0)
- Upgrading illuminate/container (v8.81.0 => v8.82.0)
- Upgrading illuminate/contracts (v8.81.0 => v8.82.0)
- Upgrading illuminate/events (v8.81.0 => v8.82.0)
- Upgrading illuminate/filesystem (v8.81.0 => v8.82.0)
- Upgrading illuminate/macroable (v8.81.0 => v8.82.0)
- Upgrading illuminate/pipeline (v8.81.0 => v8.82.0)
- Upgrading illuminate/support (v8.81.0 => v8.82.0)
- Upgrading illuminate/testing (v8.81.0 => v8.82.0)

Composer update with 13 changes 2022-02-02

---

update/composer.lock

- Upgrading illuminate/bus (v8.82.0 => v8.83.0)
- Upgrading illuminate/cache (v8.82.0 => v8.83.0)
- Upgrading illuminate/collections (v8.82.0 => v8.83.0)
- Upgrading illuminate/config (v8.82.0 => v8.83.0)
- Upgrading illuminate/console (v8.82.0 => v8.83.0)
- Upgrading illuminate/container (v8.82.0 => v8.83.0)
- Upgrading illuminate/contracts (v8.82.0 => v8.83.0)
- Upgrading illuminate/events (v8.82.0 => v8.83.0)
- Upgrading illuminate/filesystem (v8.82.0 => v8.83.0)
- Upgrading illuminate/macroable (v8.82.0 => v8.83.0)
- Upgrading illuminate/pipeline (v8.82.0 => v8.83.0)
- Upgrading illuminate/support (v8.82.0 => v8.83.0)
- Upgrading illuminate/testing (v8.82.0 => v8.83.0)

Composer update with 13 changes 2022-02-09

---

update/composer.lock

- Upgrading illuminate/bus (v8.83.1 => v8.83.2)
- Upgrading illuminate/cache (v8.83.1 => v8.83.2)
- Upgrading illuminate/collections (v8.83.1 => v8.83.2)
- Upgrading illuminate/config (v8.83.1 => v8.83.2)
- Upgrading illuminate/console (v8.83.1 => v8.83.2)
- Upgrading illuminate/container (v8.83.1 => v8.83.2)
- Upgrading illuminate/contracts (v8.83.1 => v8.83.2)
- Upgrading illuminate/events (v8.83.1 => v8.83.2)
- Upgrading illuminate/filesystem (v8.83.1 => v8.83.2)
- Upgrading illuminate/macroable (v8.83.1 => v8.83.2)
- Upgrading illuminate/pipeline (v8.83.1 => v8.83.2)
- Upgrading illuminate/support (v8.83.1 => v8.83.2)
- Upgrading illuminate/testing (v8.83.1 => v8.83.2)

Composer update with 13 changes 2022-02-23

---

update/composer.lock

- Upgrading illuminate/bus (v9.2.0 => v9.3.0)
- Upgrading illuminate/cache (v9.2.0 => v9.3.0)
- Upgrading illuminate/collections (v9.2.0 => v9.3.0)
- Upgrading illuminate/conditionable (v9.2.0 => v9.3.0)
- Upgrading illuminate/console (v9.2.0 => v9.3.0)
- Upgrading illuminate/container (v9.2.0 => v9.3.0)
- Upgrading illuminate/contracts (v9.2.0 => v9.3.0)
- Upgrading illuminate/events (v9.2.0 => v9.3.0)
- Upgrading illuminate/filesystem (v9.2.0 => v9.3.0)
- Upgrading illuminate/macroable (v9.2.0 => v9.3.0)
- Upgrading illuminate/pipeline (v9.2.0 => v9.3.0)
- Upgrading illuminate/support (v9.2.0 => v9.3.0)
- Upgrading illuminate/testing (v9.2.0 => v9.3.0)
- Upgrading myclabs/deep-copy (1.10.2 => 1.10.3)

Composer update with 14 changes 2022-03-03

---

update/composer.lock

- Upgrading illuminate/bus (v9.5.1 => v9.6.0)
- Upgrading illuminate/cache (v9.5.1 => v9.6.0)
- Upgrading illuminate/collections (v9.5.1 => v9.6.0)
- Upgrading illuminate/conditionable (v9.5.1 => v9.6.0)
- Upgrading illuminate/config (v9.5.1 => v9.6.0)
- Upgrading illuminate/console (v9.5.1 => v9.6.0)
- Upgrading illuminate/container (v9.5.1 => v9.6.0)
- Upgrading illuminate/contracts (v9.5.1 => v9.6.0)
- Upgrading illuminate/events (v9.5.1 => v9.6.0)
- Upgrading illuminate/filesystem (v9.5.1 => v9.6.0)
- Upgrading illuminate/macroable (v9.5.1 => v9.6.0)
- Upgrading illuminate/pipeline (v9.5.1 => v9.6.0)
- Upgrading illuminate/support (v9.5.1 => v9.6.0)
- Upgrading illuminate/testing (v9.5.1 => v9.6.0)
- Upgrading phpdocumentor/type-resolver (1.6.0 => 1.6.1)

Composer update with 15 changes 2022-03-30

---

update/composer.lock

- Upgrading illuminate/bus (v9.6.0 => v9.7.0)
- Upgrading illuminate/cache (v9.6.0 => v9.7.0)
- Upgrading illuminate/collections (v9.6.0 => v9.7.0)
- Upgrading illuminate/conditionable (v9.6.0 => v9.7.0)
- Upgrading illuminate/config (v9.6.0 => v9.7.0)
- Upgrading illuminate/console (v9.6.0 => v9.7.0)
- Upgrading illuminate/container (v9.6.0 => v9.7.0)
- Upgrading illuminate/contracts (v9.6.0 => v9.7.0)
- Upgrading illuminate/events (v9.6.0 => v9.7.0)
- Upgrading illuminate/filesystem (v9.6.0 => v9.7.0)
- Upgrading illuminate/macroable (v9.6.0 => v9.7.0)
- Upgrading illuminate/pipeline (v9.6.0 => v9.7.0)
- Upgrading illuminate/support (v9.6.0 => v9.7.0)
- Upgrading illuminate/testing (v9.6.0 => v9.7.0)
- Upgrading nunomaduro/collision (v6.1.0 => v6.2.0)
- Upgrading symfony/cache-contracts …

Composer update with 19 changes 2022-04-06

---

update/composer.lock

- Upgrading illuminate/bus (v9.10.1 => v9.11.0)
- Upgrading illuminate/cache (v9.10.1 => v9.11.0)
- Upgrading illuminate/collections (v9.10.1 => v9.11.0)
- Upgrading illuminate/conditionable (v9.10.1 => v9.11.0)
- Upgrading illuminate/config (v9.10.1 => v9.11.0)
- Upgrading illuminate/console (v9.10.1 => v9.11.0)
- Upgrading illuminate/container (v9.10.1 => v9.11.0)
- Upgrading illuminate/contracts (v9.10.1 => v9.11.0)
- Upgrading illuminate/events (v9.10.1 => v9.11.0)
- Upgrading illuminate/filesystem (v9.10.1 => v9.11.0)
- Upgrading illuminate/macroable (v9.10.1 => v9.11.0)
- Upgrading illuminate/pipeline (v9.10.1 => v9.11.0)
- Upgrading illuminate/support (v9.10.1 => v9.11.0)
- Upgrading illuminate/testing (v9.10.1 => v9.11.0)
- Upgrading league/flysystem (3.0.18 => 3.0.19)
- Upgrading …

Composer update with 16 changes 2022-05-04

---

update/composer.lock

- Upgrading illuminate/bus (v9.11.0 => v9.12.1)
- Upgrading illuminate/cache (v9.11.0 => v9.12.1)
- Upgrading illuminate/collections (v9.11.0 => v9.12.1)
- Upgrading illuminate/conditionable (v9.11.0 => v9.12.1)
- Upgrading illuminate/config (v9.11.0 => v9.12.1)
- Upgrading illuminate/console (v9.11.0 => v9.12.1)
- Upgrading illuminate/container (v9.11.0 => v9.12.1)
- Upgrading illuminate/contracts (v9.11.0 => v9.12.1)
- Upgrading illuminate/events (v9.11.0 => v9.12.1)
- Upgrading illuminate/filesystem (v9.11.0 => v9.12.1)
- Upgrading illuminate/macroable (v9.11.0 => v9.12.1)
- Upgrading illuminate/pipeline (v9.11.0 => v9.12.1)
- Upgrading illuminate/support (v9.11.0 => v9.12.1)
- Upgrading illuminate/testing (v9.11.0 => v9.12.1)

Composer update with 14 changes 2022-05-11

---

update/composer.lock

- Upgrading illuminate/bus (v9.12.1 => v9.12.2)
- Upgrading illuminate/cache (v9.12.1 => v9.12.2)
- Upgrading illuminate/collections (v9.12.1 => v9.12.2)
- Upgrading illuminate/conditionable (v9.12.1 => v9.12.2)
- Upgrading illuminate/config (v9.12.1 => v9.12.2)
- Upgrading illuminate/console (v9.12.1 => v9.12.2)
- Upgrading illuminate/container (v9.12.1 => v9.12.2)
- Upgrading illuminate/contracts (v9.12.1 => v9.12.2)
- Upgrading illuminate/events (v9.12.1 => v9.12.2)
- Upgrading illuminate/filesystem (v9.12.1 => v9.12.2)
- Upgrading illuminate/macroable (v9.12.1 => v9.12.2)
- Upgrading illuminate/pipeline (v9.12.1 => v9.12.2)
- Upgrading illuminate/support (v9.12.1 => v9.12.2)
- Upgrading illuminate/testing (v9.12.1 => v9.12.2)
- Upgrading nunomaduro/termwind (v1.9.0 => v1.10.1)

Composer update with 15 changes 2022-05-12

---

update/composer.lock

- Upgrading illuminate/bus (v9.12.2 => v9.13.0)
- Upgrading illuminate/cache (v9.12.2 => v9.13.0)
- Upgrading illuminate/collections (v9.12.2 => v9.13.0)
- Upgrading illuminate/conditionable (v9.12.2 => v9.13.0)
- Upgrading illuminate/config (v9.12.2 => v9.13.0)
- Upgrading illuminate/console (v9.12.2 => v9.13.0)
- Upgrading illuminate/container (v9.12.2 => v9.13.0)
- Upgrading illuminate/contracts (v9.12.2 => v9.13.0)
- Upgrading illuminate/events (v9.12.2 => v9.13.0)
- Upgrading illuminate/filesystem (v9.12.2 => v9.13.0)
- Upgrading illuminate/macroable (v9.12.2 => v9.13.0)
- Upgrading illuminate/pipeline (v9.12.2 => v9.13.0)
- Upgrading illuminate/support (v9.12.2 => v9.13.0)
- Upgrading illuminate/testing (v9.12.2 => v9.13.0)

Composer update with 14 changes 2022-05-18

---

update/composer.lock

- Upgrading illuminate/bus (v9.13.0 => v9.14.0)
- Upgrading illuminate/cache (v9.13.0 => v9.14.0)
- Upgrading illuminate/collections (v9.13.0 => v9.14.0)
- Upgrading illuminate/conditionable (v9.13.0 => v9.14.0)
- Upgrading illuminate/config (v9.13.0 => v9.14.0)
- Upgrading illuminate/console (v9.13.0 => v9.14.0)
- Upgrading illuminate/container (v9.13.0 => v9.14.0)
- Upgrading illuminate/contracts (v9.13.0 => v9.14.0)
- Upgrading illuminate/events (v9.13.0 => v9.14.0)
- Upgrading illuminate/filesystem (v9.13.0 => v9.14.0)
- Upgrading illuminate/macroable (v9.13.0 => v9.14.0)
- Upgrading illuminate/pipeline (v9.13.0 => v9.14.0)
- Upgrading illuminate/support (v9.13.0 => v9.14.0)
- Upgrading illuminate/testing (v9.13.0 => v9.14.0)

Composer update with 14 changes 2022-05-25

---

update/composer.lock

- Upgrading guzzlehttp/guzzle (7.4.2 => 7.4.3)
- Upgrading illuminate/bus (v9.14.0 => v9.14.1)
- Upgrading illuminate/cache (v9.14.0 => v9.14.1)
- Upgrading illuminate/collections (v9.14.0 => v9.14.1)
- Upgrading illuminate/conditionable (v9.14.0 => v9.14.1)
- Upgrading illuminate/config (v9.14.0 => v9.14.1)
- Upgrading illuminate/console (v9.14.0 => v9.14.1)
- Upgrading illuminate/container (v9.14.0 => v9.14.1)
- Upgrading illuminate/contracts (v9.14.0 => v9.14.1)
- Upgrading illuminate/events (v9.14.0 => v9.14.1)
- Upgrading illuminate/filesystem (v9.14.0 => v9.14.1)
- Upgrading illuminate/macroable (v9.14.0 => v9.14.1)
- Upgrading illuminate/pipeline (v9.14.0 => v9.14.1)
- Upgrading illuminate/support (v9.14.0 => v9.14.1)
- Upgrading illuminate/testing (v9.14.0 => v9.14.1)
- Upgrading …

Composer update with 17 changes 2022-05-26

---

update/composer.lock

- Upgrading illuminate/bus (v9.15.0 => v9.16.0)
- Upgrading illuminate/cache (v9.15.0 => v9.16.0)
- Upgrading illuminate/collections (v9.15.0 => v9.16.0)
- Upgrading illuminate/conditionable (v9.15.0 => v9.16.0)
- Upgrading illuminate/config (v9.15.0 => v9.16.0)
- Upgrading illuminate/console (v9.15.0 => v9.16.0)
- Upgrading illuminate/container (v9.15.0 => v9.16.0)
- Upgrading illuminate/contracts (v9.15.0 => v9.16.0)
- Upgrading illuminate/events (v9.15.0 => v9.16.0)
- Upgrading illuminate/filesystem (v9.15.0 => v9.16.0)
- Upgrading illuminate/macroable (v9.15.0 => v9.16.0)
- Upgrading illuminate/pipeline (v9.15.0 => v9.16.0)
- Upgrading illuminate/support (v9.15.0 => v9.16.0)
- Upgrading illuminate/testing (v9.15.0 => v9.16.0)
- Upgrading symfony/polyfill-ctype (v1.25.0 => v1.26.0)
- …

Composer update with 20 changes 2022-06-03

---

update/composer.lock

- Upgrading illuminate/bus (v9.16.0 => v9.17.0)
- Upgrading illuminate/cache (v9.16.0 => v9.17.0)
- Upgrading illuminate/collections (v9.16.0 => v9.17.0)
- Upgrading illuminate/conditionable (v9.16.0 => v9.17.0)
- Upgrading illuminate/config (v9.16.0 => v9.17.0)
- Upgrading illuminate/console (v9.16.0 => v9.17.0)
- Upgrading illuminate/container (v9.16.0 => v9.17.0)
- Upgrading illuminate/contracts (v9.16.0 => v9.17.0)
- Upgrading illuminate/events (v9.16.0 => v9.17.0)
- Upgrading illuminate/filesystem (v9.16.0 => v9.17.0)
- Upgrading illuminate/macroable (v9.16.0 => v9.17.0)
- Upgrading illuminate/pipeline (v9.16.0 => v9.17.0)
- Upgrading illuminate/support (v9.16.0 => v9.17.0)
- Upgrading illuminate/testing (v9.16.0 => v9.17.0)

Composer update with 14 changes 2022-06-08

---

update/composer.lock

- Upgrading illuminate/bus (v9.17.0 => v9.18.0)
- Upgrading illuminate/cache (v9.17.0 => v9.18.0)
- Upgrading illuminate/collections (v9.17.0 => v9.18.0)
- Upgrading illuminate/conditionable (v9.17.0 => v9.18.0)
- Upgrading illuminate/config (v9.17.0 => v9.18.0)
- Upgrading illuminate/console (v9.17.0 => v9.18.0)
- Upgrading illuminate/container (v9.17.0 => v9.18.0)
- Upgrading illuminate/contracts (v9.17.0 => v9.18.0)
- Upgrading illuminate/events (v9.17.0 => v9.18.0)
- Upgrading illuminate/filesystem (v9.17.0 => v9.18.0)
- Upgrading illuminate/macroable (v9.17.0 => v9.18.0)
- Upgrading illuminate/pipeline (v9.17.0 => v9.18.0)
- Upgrading illuminate/support (v9.17.0 => v9.18.0)
- Upgrading illuminate/testing (v9.17.0 => v9.18.0)

Composer update with 14 changes 2022-06-22

---

update/composer.lock

- Upgrading illuminate/bus (v9.18.0 => v9.19.0)
- Upgrading illuminate/cache (v9.18.0 => v9.19.0)
- Upgrading illuminate/collections (v9.18.0 => v9.19.0)
- Upgrading illuminate/conditionable (v9.18.0 => v9.19.0)
- Upgrading illuminate/config (v9.18.0 => v9.19.0)
- Upgrading illuminate/console (v9.18.0 => v9.19.0)
- Upgrading illuminate/container (v9.18.0 => v9.19.0)
- Upgrading illuminate/contracts (v9.18.0 => v9.19.0)
- Upgrading illuminate/events (v9.18.0 => v9.19.0)
- Upgrading illuminate/filesystem (v9.18.0 => v9.19.0)
- Upgrading illuminate/macroable (v9.18.0 => v9.19.0)
- Upgrading illuminate/pipeline (v9.18.0 => v9.19.0)
- Upgrading illuminate/support (v9.18.0 => v9.19.0)
- Upgrading illuminate/testing (v9.18.0 => v9.19.0)
- Upgrading symfony/cache-contracts (v3.1.0 => v3.1.1)
- …

Composer update with 18 changes 2022-06-29

---

update/composer.lock

- Removing phpdocumentor/reflection-common (2.2.0)
- Removing phpdocumentor/reflection-docblock (5.3.0)
- Removing phpdocumentor/type-resolver (1.6.1)
- Removing phpspec/prophecy (v1.15.0)
- Upgrading laravel-zero/framework (v9.1.2 => v9.1.3)
- Upgrading phpunit/phpunit (9.5.22 => 9.5.23)

Composer update with 6 changes 2022-08-23

---

update/composer.lock

- Upgrading illuminate/bus (v9.26.1 => v9.27.0)
- Upgrading illuminate/cache (v9.26.1 => v9.27.0)
- Upgrading illuminate/collections (v9.26.1 => v9.27.0)
- Upgrading illuminate/conditionable (v9.26.1 => v9.27.0)
- Upgrading illuminate/config (v9.26.1 => v9.27.0)
- Upgrading illuminate/console (v9.26.1 => v9.27.0)
- Upgrading illuminate/container (v9.26.1 => v9.27.0)
- Upgrading illuminate/contracts (v9.26.1 => v9.27.0)
- Upgrading illuminate/events (v9.26.1 => v9.27.0)
- Upgrading illuminate/filesystem (v9.26.1 => v9.27.0)
- Upgrading illuminate/macroable (v9.26.1 => v9.27.0)
- Upgrading illuminate/pipeline (v9.26.1 => v9.27.0)
- Upgrading illuminate/support (v9.26.1 => v9.27.0)
- Upgrading illuminate/testing (v9.26.1 => v9.27.0)
- Upgrading illuminate/view (v9.26.0 => v9.27.0)
- …

Composer update with 17 changes 2022-08-31

---

update/composer.lock

- Upgrading illuminate/bus (v9.28.0 => v9.29.0)
- Upgrading illuminate/cache (v9.28.0 => v9.29.0)
- Upgrading illuminate/collections (v9.28.0 => v9.29.0)
- Upgrading illuminate/conditionable (v9.28.0 => v9.29.0)
- Upgrading illuminate/config (v9.28.0 => v9.29.0)
- Upgrading illuminate/console (v9.28.0 => v9.29.0)
- Upgrading illuminate/container (v9.28.0 => v9.29.0)
- Upgrading illuminate/contracts (v9.28.0 => v9.29.0)
- Upgrading illuminate/events (v9.28.0 => v9.29.0)
- Upgrading illuminate/filesystem (v9.28.0 => v9.29.0)
- Upgrading illuminate/macroable (v9.28.0 => v9.29.0)
- Upgrading illuminate/pipeline (v9.28.0 => v9.29.0)
- Upgrading illuminate/support (v9.28.0 => v9.29.0)
- Upgrading illuminate/testing (v9.28.0 => v9.29.0)
- Upgrading illuminate/view (v9.28.0 => v9.29.0)
- …

Composer update with 16 changes 2022-09-10

---

update/composer.lock

- Upgrading illuminate/bus (v9.30.0 => v9.30.1)
- Upgrading illuminate/cache (v9.30.0 => v9.30.1)
- Upgrading illuminate/collections (v9.30.0 => v9.30.1)
- Upgrading illuminate/conditionable (v9.30.0 => v9.30.1)
- Upgrading illuminate/config (v9.30.0 => v9.30.1)
- Upgrading illuminate/console (v9.30.0 => v9.30.1)
- Upgrading illuminate/container (v9.30.0 => v9.30.1)
- Upgrading illuminate/contracts (v9.30.0 => v9.30.1)
- Upgrading illuminate/events (v9.30.0 => v9.30.1)
- Upgrading illuminate/filesystem (v9.30.0 => v9.30.1)
- Upgrading illuminate/macroable (v9.30.0 => v9.30.1)
- Upgrading illuminate/pipeline (v9.30.0 => v9.30.1)
- Upgrading illuminate/support (v9.30.0 => v9.30.1)
- Upgrading illuminate/testing (v9.30.0 => v9.30.1)
- Upgrading illuminate/view (v9.30.0 => v9.30.1)
- …

Composer update with 16 changes 2022-09-16

---

update/composer.lock

- Upgrading illuminate/bus (v9.30.1 => v9.31.0)
- Upgrading illuminate/cache (v9.30.1 => v9.31.0)
- Upgrading illuminate/collections (v9.30.1 => v9.31.0)
- Upgrading illuminate/conditionable (v9.30.1 => v9.31.0)
- Upgrading illuminate/config (v9.30.1 => v9.31.0)
- Upgrading illuminate/console (v9.30.1 => v9.31.0)
- Upgrading illuminate/container (v9.30.1 => v9.31.0)
- Upgrading illuminate/contracts (v9.30.1 => v9.31.0)
- Upgrading illuminate/events (v9.30.1 => v9.31.0)
- Upgrading illuminate/filesystem (v9.30.1 => v9.31.0)
- Upgrading illuminate/macroable (v9.30.1 => v9.31.0)
- Upgrading illuminate/pipeline (v9.30.1 => v9.31.0)
- Upgrading illuminate/support (v9.30.1 => v9.31.0)
- Upgrading illuminate/testing (v9.30.1 => v9.31.0)
- Upgrading illuminate/view (v9.30.1 => v9.31.0)

Composer update with 15 changes 2022-09-21

---

update/composer.lock

- Upgrading illuminate/bus (v9.31.0 => v9.32.0)
- Upgrading illuminate/cache (v9.31.0 => v9.32.0)
- Upgrading illuminate/collections (v9.31.0 => v9.32.0)
- Upgrading illuminate/conditionable (v9.31.0 => v9.32.0)
- Upgrading illuminate/config (v9.31.0 => v9.32.0)
- Upgrading illuminate/console (v9.31.0 => v9.32.0)
- Upgrading illuminate/container (v9.31.0 => v9.32.0)
- Upgrading illuminate/contracts (v9.31.0 => v9.32.0)
- Upgrading illuminate/events (v9.31.0 => v9.32.0)
- Upgrading illuminate/filesystem (v9.31.0 => v9.32.0)
- Upgrading illuminate/macroable (v9.31.0 => v9.32.0)
- Upgrading illuminate/pipeline (v9.31.0 => v9.32.0)
- Upgrading illuminate/support (v9.31.0 => v9.32.0)
- Upgrading illuminate/testing (v9.31.0 => v9.32.0)
- Upgrading illuminate/view (v9.31.0 => v9.32.0)

Composer update with 15 changes 2022-09-28

---

update/composer.lock

- Upgrading illuminate/bus (v9.32.0 => v9.33.0)
- Upgrading illuminate/cache (v9.32.0 => v9.33.0)
- Upgrading illuminate/collections (v9.32.0 => v9.33.0)
- Upgrading illuminate/conditionable (v9.32.0 => v9.33.0)
- Upgrading illuminate/config (v9.32.0 => v9.33.0)
- Upgrading illuminate/console (v9.32.0 => v9.33.0)
- Upgrading illuminate/container (v9.32.0 => v9.33.0)
- Upgrading illuminate/contracts (v9.32.0 => v9.33.0)
- Upgrading illuminate/events (v9.32.0 => v9.33.0)
- Upgrading illuminate/filesystem (v9.32.0 => v9.33.0)
- Upgrading illuminate/macroable (v9.32.0 => v9.33.0)
- Upgrading illuminate/pipeline (v9.32.0 => v9.33.0)
- Upgrading illuminate/support (v9.32.0 => v9.33.0)
- Upgrading illuminate/testing (v9.32.0 => v9.33.0)
- Upgrading illuminate/view (v9.32.0 => v9.33.0)
- …

Composer update with 22 changes 2022-10-01

---

update/composer.lock

- Upgrading illuminate/bus (v9.33.0 => v9.34.0)
- Upgrading illuminate/cache (v9.33.0 => v9.34.0)
- Upgrading illuminate/collections (v9.33.0 => v9.34.0)
- Upgrading illuminate/conditionable (v9.33.0 => v9.34.0)
- Upgrading illuminate/config (v9.33.0 => v9.34.0)
- Upgrading illuminate/console (v9.33.0 => v9.34.0)
- Upgrading illuminate/container (v9.33.0 => v9.34.0)
- Upgrading illuminate/contracts (v9.33.0 => v9.34.0)
- Upgrading illuminate/events (v9.33.0 => v9.34.0)
- Upgrading illuminate/filesystem (v9.33.0 => v9.34.0)
- Upgrading illuminate/macroable (v9.33.0 => v9.34.0)
- Upgrading illuminate/pipeline (v9.33.0 => v9.34.0)
- Upgrading illuminate/support (v9.33.0 => v9.34.0)
- Upgrading illuminate/testing (v9.33.0 => v9.34.0)
- Upgrading illuminate/view (v9.33.0 => v9.34.0)

Composer update with 15 changes 2022-10-05

---

update/composer.lock

- Upgrading illuminate/bus (v9.34.0 => v9.35.1)
- Upgrading illuminate/cache (v9.34.0 => v9.35.1)
- Upgrading illuminate/collections (v9.34.0 => v9.35.1)
- Upgrading illuminate/conditionable (v9.34.0 => v9.35.1)
- Upgrading illuminate/config (v9.34.0 => v9.35.1)
- Upgrading illuminate/console (v9.34.0 => v9.35.1)
- Upgrading illuminate/container (v9.34.0 => v9.35.1)
- Upgrading illuminate/contracts (v9.34.0 => v9.35.1)
- Upgrading illuminate/events (v9.34.0 => v9.35.1)
- Upgrading illuminate/filesystem (v9.34.0 => v9.35.1)
- Upgrading illuminate/macroable (v9.34.0 => v9.35.1)
- Upgrading illuminate/pipeline (v9.34.0 => v9.35.1)
- Upgrading illuminate/support (v9.34.0 => v9.35.1)
- Upgrading illuminate/testing (v9.34.0 => v9.35.1)
- Upgrading illuminate/view (v9.34.0 => v9.35.1)

Composer update with 15 changes 2022-10-12

---

update/composer.lock

- Upgrading illuminate/bus (v9.35.1 => v9.36.2)
- Upgrading illuminate/cache (v9.35.1 => v9.36.2)
- Upgrading illuminate/collections (v9.35.1 => v9.36.2)
- Upgrading illuminate/conditionable (v9.35.1 => v9.36.2)
- Upgrading illuminate/config (v9.35.1 => v9.36.2)
- Upgrading illuminate/console (v9.35.1 => v9.36.2)
- Upgrading illuminate/container (v9.35.1 => v9.36.2)
- Upgrading illuminate/contracts (v9.35.1 => v9.36.2)
- Upgrading illuminate/events (v9.35.1 => v9.36.2)
- Upgrading illuminate/filesystem (v9.35.1 => v9.36.2)
- Upgrading illuminate/macroable (v9.35.1 => v9.36.2)
- Upgrading illuminate/pipeline (v9.35.1 => v9.36.2)
- Upgrading illuminate/support (v9.35.1 => v9.36.2)
- Upgrading illuminate/testing (v9.35.1 => v9.36.2)
- Upgrading illuminate/view (v9.35.1 => v9.36.2)
- …

Composer update with 16 changes 2022-10-19

---

update/composer.lock

- Upgrading illuminate/bus (v9.36.2 => v9.36.3)
- Upgrading illuminate/cache (v9.36.2 => v9.36.3)
- Upgrading illuminate/collections (v9.36.2 => v9.36.3)
- Upgrading illuminate/conditionable (v9.36.2 => v9.36.3)
- Upgrading illuminate/config (v9.36.2 => v9.36.3)
- Upgrading illuminate/console (v9.36.2 => v9.36.3)
- Upgrading illuminate/container (v9.36.2 => v9.36.3)
- Upgrading illuminate/contracts (v9.36.2 => v9.36.3)
- Upgrading illuminate/events (v9.36.2 => v9.36.3)
- Upgrading illuminate/filesystem (v9.36.2 => v9.36.3)
- Upgrading illuminate/macroable (v9.36.2 => v9.36.3)
- Upgrading illuminate/pipeline (v9.36.2 => v9.36.3)
- Upgrading illuminate/support (v9.36.2 => v9.36.3)
- Upgrading illuminate/testing (v9.36.2 => v9.36.3)
- Upgrading illuminate/view (v9.36.2 => v9.36.3)

Composer update with 15 changes 2022-10-20

---

update/composer.lock

- Upgrading doctrine/inflector (2.0.5 => 2.0.6)
- Upgrading illuminate/bus (v9.36.3 => v9.36.4)
- Upgrading illuminate/cache (v9.36.3 => v9.36.4)
- Upgrading illuminate/collections (v9.36.3 => v9.36.4)
- Upgrading illuminate/conditionable (v9.36.3 => v9.36.4)
- Upgrading illuminate/config (v9.36.3 => v9.36.4)
- Upgrading illuminate/console (v9.36.3 => v9.36.4)
- Upgrading illuminate/container (v9.36.3 => v9.36.4)
- Upgrading illuminate/contracts (v9.36.3 => v9.36.4)
- Upgrading illuminate/events (v9.36.3 => v9.36.4)
- Upgrading illuminate/filesystem (v9.36.3 => v9.36.4)
- Upgrading illuminate/macroable (v9.36.3 => v9.36.4)
- Upgrading illuminate/pipeline (v9.36.3 => v9.36.4)
- Upgrading illuminate/support (v9.36.3 => v9.36.4)
- Upgrading illuminate/testing (v9.36.3 => v9.36.4)
- Upgrading …

Composer update with 16 changes 2022-10-21

---

update/composer.lock

- Upgrading guzzlehttp/psr7 (2.4.1 => 2.4.2)
- Upgrading illuminate/bus (v9.36.4 => v9.37.0)
- Upgrading illuminate/cache (v9.36.4 => v9.37.0)
- Upgrading illuminate/collections (v9.36.4 => v9.37.0)
- Upgrading illuminate/conditionable (v9.36.4 => v9.37.0)
- Upgrading illuminate/config (v9.36.4 => v9.37.0)
- Upgrading illuminate/console (v9.36.4 => v9.37.0)
- Upgrading illuminate/container (v9.36.4 => v9.37.0)
- Upgrading illuminate/contracts (v9.36.4 => v9.37.0)
- Upgrading illuminate/events (v9.36.4 => v9.37.0)
- Upgrading illuminate/filesystem (v9.36.4 => v9.37.0)
- Upgrading illuminate/macroable (v9.36.4 => v9.37.0)
- Upgrading illuminate/pipeline (v9.36.4 => v9.37.0)
- Upgrading illuminate/support (v9.36.4 => v9.37.0)
- Upgrading illuminate/testing (v9.36.4 => v9.37.0)
- Upgrading …

Composer update with 17 changes 2022-10-26

---

update/composer.lock

- Upgrading illuminate/bus (v9.37.0 => v9.38.0)
- Upgrading illuminate/cache (v9.37.0 => v9.38.0)
- Upgrading illuminate/collections (v9.37.0 => v9.38.0)
- Upgrading illuminate/conditionable (v9.37.0 => v9.38.0)
- Upgrading illuminate/config (v9.37.0 => v9.38.0)
- Upgrading illuminate/console (v9.37.0 => v9.38.0)
- Upgrading illuminate/container (v9.37.0 => v9.38.0)
- Upgrading illuminate/contracts (v9.37.0 => v9.38.0)
- Upgrading illuminate/events (v9.37.0 => v9.38.0)
- Upgrading illuminate/filesystem (v9.37.0 => v9.38.0)
- Upgrading illuminate/macroable (v9.37.0 => v9.38.0)
- Upgrading illuminate/pipeline (v9.37.0 => v9.38.0)
- Upgrading illuminate/support (v9.37.0 => v9.38.0)
- Upgrading illuminate/testing (v9.37.0 => v9.38.0)
- Upgrading illuminate/view (v9.37.0 => v9.38.0)

Composer update with 15 changes 2022-11-02

---

update/composer.lock

- Removing facade/ignition-contracts (1.0.2)
- Removing phpdocumentor/reflection-common (2.2.0)
- Removing phpdocumentor/reflection-docblock (5.3.0)
- Removing phpdocumentor/type-resolver (1.6.1)
- Removing phpspec/prophecy (v1.15.0)
- Upgrading brick/math (0.9.3 => 0.10.2)
- Upgrading doctrine/inflector (2.0.4 => 2.0.6)
- Upgrading dragonmantank/cron-expression (v3.3.1 => v3.3.2)
- Upgrading filp/whoops (2.14.5 => 2.14.6)
- Upgrading graham-campbell/bounded-cache (v1.1.3 => v2.1.0)
- Upgrading graham-campbell/github (v10.5.0 => v10.6.0)
- Upgrading graham-campbell/result-type (v1.0.4 => v1.1.0)
- Upgrading guzzlehttp/guzzle (7.4.2 => 7.5.0)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
- Upgrading guzzlehttp/psr7 (2.2.1 => 2.4.3)
- Upgrading illuminate/bus (v9.10.0 => v9.38.0)
- …

Composer update with 71 changes 2022-11-06

---

update/composer.lock

- Upgrading illuminate/bus (v9.38.0 => v9.39.0)
- Upgrading illuminate/cache (v9.38.0 => v9.39.0)
- Upgrading illuminate/collections (v9.38.0 => v9.39.0)
- Upgrading illuminate/conditionable (v9.38.0 => v9.39.0)
- Upgrading illuminate/config (v9.38.0 => v9.39.0)
- Upgrading illuminate/console (v9.38.0 => v9.39.0)
- Upgrading illuminate/container (v9.38.0 => v9.39.0)
- Upgrading illuminate/contracts (v9.38.0 => v9.39.0)
- Upgrading illuminate/events (v9.38.0 => v9.39.0)
- Upgrading illuminate/filesystem (v9.38.0 => v9.39.0)
- Upgrading illuminate/macroable (v9.38.0 => v9.39.0)
- Upgrading illuminate/pipeline (v9.38.0 => v9.39.0)
- Upgrading illuminate/support (v9.38.0 => v9.39.0)
- Upgrading illuminate/testing (v9.38.0 => v9.39.0)
- Upgrading illuminate/view (v9.38.0 => v9.39.0)

Composer update with 15 changes 2022-11-09

---

update/composer.lock

- Upgrading illuminate/bus (v9.39.0 => v9.40.1)
- Upgrading illuminate/cache (v9.39.0 => v9.40.1)
- Upgrading illuminate/collections (v9.39.0 => v9.40.1)
- Upgrading illuminate/conditionable (v9.39.0 => v9.40.1)
- Upgrading illuminate/config (v9.39.0 => v9.40.1)
- Upgrading illuminate/console (v9.39.0 => v9.40.1)
- Upgrading illuminate/container (v9.39.0 => v9.40.1)
- Upgrading illuminate/contracts (v9.39.0 => v9.40.1)
- Upgrading illuminate/events (v9.39.0 => v9.40.1)
- Upgrading illuminate/filesystem (v9.39.0 => v9.40.1)
- Upgrading illuminate/macroable (v9.39.0 => v9.40.1)
- Upgrading illuminate/pipeline (v9.39.0 => v9.40.1)
- Upgrading illuminate/support (v9.39.0 => v9.40.1)
- Upgrading illuminate/testing (v9.39.0 => v9.40.1)
- Upgrading illuminate/view (v9.39.0 => v9.40.1)
- …

Composer update with 16 changes 2022-11-16

---

update/composer.lock

- Upgrading illuminate/bus (v9.40.1 => v9.41.0)
- Upgrading illuminate/cache (v9.40.1 => v9.41.0)
- Upgrading illuminate/collections (v9.40.1 => v9.41.0)
- Upgrading illuminate/conditionable (v9.40.1 => v9.41.0)
- Upgrading illuminate/config (v9.40.1 => v9.41.0)
- Upgrading illuminate/console (v9.40.1 => v9.41.0)
- Upgrading illuminate/container (v9.40.1 => v9.41.0)
- Upgrading illuminate/contracts (v9.40.1 => v9.41.0)
- Upgrading illuminate/events (v9.40.1 => v9.41.0)
- Upgrading illuminate/filesystem (v9.40.1 => v9.41.0)
- Upgrading illuminate/macroable (v9.40.1 => v9.41.0)
- Upgrading illuminate/pipeline (v9.40.1 => v9.41.0)
- Upgrading illuminate/support (v9.40.1 => v9.41.0)
- Upgrading illuminate/testing (v9.40.1 => v9.41.0)
- Upgrading illuminate/view (v9.40.1 => v9.41.0)

Composer update with 15 changes 2022-11-23

---

update/composer.lock

- Upgrading illuminate/bus (v9.41.0 => v9.42.2)
- Upgrading illuminate/cache (v9.41.0 => v9.42.2)
- Upgrading illuminate/collections (v9.41.0 => v9.42.2)
- Upgrading illuminate/conditionable (v9.41.0 => v9.42.2)
- Upgrading illuminate/config (v9.41.0 => v9.42.2)
- Upgrading illuminate/console (v9.41.0 => v9.42.2)
- Upgrading illuminate/container (v9.41.0 => v9.42.2)
- Upgrading illuminate/contracts (v9.41.0 => v9.42.2)
- Upgrading illuminate/events (v9.41.0 => v9.42.2)
- Upgrading illuminate/filesystem (v9.41.0 => v9.42.2)
- Upgrading illuminate/macroable (v9.41.0 => v9.42.2)
- Upgrading illuminate/pipeline (v9.41.0 => v9.42.2)
- Upgrading illuminate/support (v9.41.0 => v9.42.2)
- Upgrading illuminate/testing (v9.41.0 => v9.42.2)
- Upgrading illuminate/view (v9.41.0 => v9.42.2)
- …

Composer update with 25 changes 2022-12-01

---

update/composer.lock

- Upgrading illuminate/bus (v9.42.2 => v9.43.0)
- Upgrading illuminate/cache (v9.42.2 => v9.43.0)
- Upgrading illuminate/collections (v9.42.2 => v9.43.0)
- Upgrading illuminate/conditionable (v9.42.2 => v9.43.0)
- Upgrading illuminate/config (v9.42.2 => v9.43.0)
- Upgrading illuminate/console (v9.42.2 => v9.43.0)
- Upgrading illuminate/container (v9.42.2 => v9.43.0)
- Upgrading illuminate/contracts (v9.42.2 => v9.43.0)
- Upgrading illuminate/events (v9.42.2 => v9.43.0)
- Upgrading illuminate/macroable (v9.42.2 => v9.43.0)
- Upgrading illuminate/pipeline (v9.42.2 => v9.43.0)
- Upgrading illuminate/support (v9.42.2 => v9.43.0)
- Upgrading illuminate/testing (v9.42.2 => v9.43.0)
- Upgrading illuminate/view (v9.42.2 => v9.43.0)
- Upgrading symfony/console (v6.2.0 => v6.2.1)
- Upgrading …

Composer update with 18 changes 2022-12-07

---

update/composer.lock

- Upgrading illuminate/bus (v9.43.0 => v9.44.0)
- Upgrading illuminate/cache (v9.43.0 => v9.44.0)
- Upgrading illuminate/collections (v9.43.0 => v9.44.0)
- Upgrading illuminate/conditionable (v9.43.0 => v9.44.0)
- Upgrading illuminate/config (v9.43.0 => v9.44.0)
- Upgrading illuminate/console (v9.43.0 => v9.44.0)
- Upgrading illuminate/container (v9.43.0 => v9.44.0)
- Upgrading illuminate/contracts (v9.43.0 => v9.44.0)
- Upgrading illuminate/events (v9.43.0 => v9.44.0)
- Upgrading illuminate/filesystem (v9.43.0 => v9.44.0)
- Upgrading illuminate/macroable (v9.43.0 => v9.44.0)
- Upgrading illuminate/pipeline (v9.43.0 => v9.44.0)
- Upgrading illuminate/support (v9.43.0 => v9.44.0)
- Upgrading illuminate/testing (v9.43.0 => v9.44.0)
- Upgrading illuminate/view (v9.43.0 => v9.44.0)

Composer update with 15 changes 2022-12-16

---

update/composer.lock

- Upgrading illuminate/bus (v9.44.0 => v9.45.0)
- Upgrading illuminate/cache (v9.44.0 => v9.45.0)
- Upgrading illuminate/collections (v9.44.0 => v9.45.0)
- Upgrading illuminate/conditionable (v9.44.0 => v9.45.0)
- Upgrading illuminate/config (v9.44.0 => v9.45.0)
- Upgrading illuminate/console (v9.44.0 => v9.45.0)
- Upgrading illuminate/container (v9.44.0 => v9.45.0)
- Upgrading illuminate/contracts (v9.44.0 => v9.45.0)
- Upgrading illuminate/events (v9.44.0 => v9.45.0)
- Upgrading illuminate/filesystem (v9.44.0 => v9.45.0)
- Upgrading illuminate/macroable (v9.44.0 => v9.45.0)
- Upgrading illuminate/pipeline (v9.44.0 => v9.45.0)
- Upgrading illuminate/support (v9.44.0 => v9.45.0)
- Upgrading illuminate/testing (v9.44.0 => v9.45.0)
- Upgrading illuminate/view (v9.44.0 => v9.45.0)
- …

Composer update with 17 changes 2022-12-21

---

update/composer.lock

- Upgrading illuminate/bus (v9.45.0 => v9.45.1)
- Upgrading illuminate/cache (v9.45.0 => v9.45.1)
- Upgrading illuminate/collections (v9.45.0 => v9.45.1)
- Upgrading illuminate/conditionable (v9.45.0 => v9.45.1)
- Upgrading illuminate/config (v9.45.0 => v9.45.1)
- Upgrading illuminate/console (v9.45.0 => v9.45.1)
- Upgrading illuminate/container (v9.45.0 => v9.45.1)
- Upgrading illuminate/contracts (v9.45.0 => v9.45.1)
- Upgrading illuminate/events (v9.45.0 => v9.45.1)
- Upgrading illuminate/filesystem (v9.45.0 => v9.45.1)
- Upgrading illuminate/macroable (v9.45.0 => v9.45.1)
- Upgrading illuminate/pipeline (v9.45.0 => v9.45.1)
- Upgrading illuminate/support (v9.45.0 => v9.45.1)
- Upgrading illuminate/testing (v9.45.0 => v9.45.1)
- Upgrading illuminate/view (v9.45.0 => v9.45.1)

Composer update with 15 changes 2022-12-22

---

update/composer.lock

- Upgrading illuminate/bus (v9.45.1 => v9.46.0)
- Upgrading illuminate/cache (v9.45.1 => v9.46.0)
- Upgrading illuminate/collections (v9.45.1 => v9.46.0)
- Upgrading illuminate/conditionable (v9.45.1 => v9.46.0)
- Upgrading illuminate/config (v9.45.1 => v9.46.0)
- Upgrading illuminate/console (v9.45.1 => v9.46.0)
- Upgrading illuminate/container (v9.45.1 => v9.46.0)
- Upgrading illuminate/contracts (v9.45.1 => v9.46.0)
- Upgrading illuminate/events (v9.45.1 => v9.46.0)
- Upgrading illuminate/filesystem (v9.45.1 => v9.46.0)
- Upgrading illuminate/macroable (v9.45.1 => v9.46.0)
- Upgrading illuminate/pipeline (v9.45.1 => v9.46.0)
- Upgrading illuminate/support (v9.45.1 => v9.46.0)
- Upgrading illuminate/testing (v9.45.1 => v9.46.0)
- Upgrading illuminate/view (v9.45.1 => v9.46.0)
- …

Composer update with 16 changes 2023-01-04

---

update/composer.lock

- Upgrading illuminate/bus (v9.46.0 => v9.47.0)
- Upgrading illuminate/cache (v9.46.0 => v9.47.0)
- Upgrading illuminate/collections (v9.46.0 => v9.47.0)
- Upgrading illuminate/conditionable (v9.46.0 => v9.47.0)
- Upgrading illuminate/config (v9.46.0 => v9.47.0)
- Upgrading illuminate/console (v9.46.0 => v9.47.0)
- Upgrading illuminate/container (v9.46.0 => v9.47.0)
- Upgrading illuminate/contracts (v9.46.0 => v9.47.0)
- Upgrading illuminate/events (v9.46.0 => v9.47.0)
- Upgrading illuminate/filesystem (v9.46.0 => v9.47.0)
- Upgrading illuminate/macroable (v9.46.0 => v9.47.0)
- Upgrading illuminate/pipeline (v9.46.0 => v9.47.0)
- Upgrading illuminate/support (v9.46.0 => v9.47.0)
- Upgrading illuminate/testing (v9.46.0 => v9.47.0)
- Upgrading illuminate/view (v9.46.0 => v9.47.0)

Composer update with 15 changes 2023-01-11

---

update/composer.lock

- Upgrading illuminate/bus (v9.47.0 => v9.48.0)
- Upgrading illuminate/cache (v9.47.0 => v9.48.0)
- Upgrading illuminate/collections (v9.47.0 => v9.48.0)
- Upgrading illuminate/conditionable (v9.47.0 => v9.48.0)
- Upgrading illuminate/config (v9.47.0 => v9.48.0)
- Upgrading illuminate/console (v9.47.0 => v9.48.0)
- Upgrading illuminate/container (v9.47.0 => v9.48.0)
- Upgrading illuminate/contracts (v9.47.0 => v9.48.0)
- Upgrading illuminate/events (v9.47.0 => v9.48.0)
- Upgrading illuminate/filesystem (v9.47.0 => v9.48.0)
- Upgrading illuminate/macroable (v9.47.0 => v9.48.0)
- Upgrading illuminate/pipeline (v9.47.0 => v9.48.0)
- Upgrading illuminate/support (v9.47.0 => v9.48.0)
- Upgrading illuminate/testing (v9.47.0 => v9.48.0)
- Upgrading illuminate/view (v9.47.0 => v9.48.0)

Composer update with 15 changes 2023-01-18

---

update/app/Commands/UpdateCommand.php

This PR solves the following issue https://github.com/kawax/composer-update-action/actions/runs/4100227845/jobs/7070853029#step:4:13
It seems the ubuntu images updated the git version and now is complaining about the workspace directory is not in the whitelist of safe directories
I hope this can be also merged in the previous PHP version branches
Let me know if this PR is good enough I couldn't find a contribution guide thanks @kawax

fix: safe directory

---

update/composer.lock

- Upgrading illuminate/bus (v10.13.1 => v10.13.2)
- Upgrading illuminate/cache (v10.13.1 => v10.13.2)
- Upgrading illuminate/collections (v10.13.1 => v10.13.2)
- Upgrading illuminate/conditionable (v10.13.1 => v10.13.2)
- Upgrading illuminate/config (v10.13.1 => v10.13.2)
- Upgrading illuminate/console (v10.13.1 => v10.13.2)
- Upgrading illuminate/container (v10.13.1 => v10.13.2)
- Upgrading illuminate/contracts (v10.13.1 => v10.13.2)
- Upgrading illuminate/events (v10.13.1 => v10.13.2)
- Upgrading illuminate/filesystem (v10.13.1 => v10.13.2)
- Upgrading illuminate/macroable (v10.13.1 => v10.13.2)
- Upgrading illuminate/pipeline (v10.13.1 => v10.13.2)
- Upgrading illuminate/process (v10.13.1 => v10.13.2)
- Upgrading illuminate/support (v10.13.1 => v10.13.2) …

Composer update with 18 changes 2023-06-06

---

update/composer.lock

- Upgrading illuminate/bus (v10.21.0 => v10.21.1)
- Upgrading illuminate/cache (v10.21.0 => v10.21.1)
- Upgrading illuminate/collections (v10.21.0 => v10.21.1)
- Upgrading illuminate/conditionable (v10.21.0 => v10.21.1)
- Upgrading illuminate/config (v10.21.0 => v10.21.1)
- Upgrading illuminate/console (v10.21.0 => v10.21.1)
- Upgrading illuminate/container (v10.21.0 => v10.21.1)
- Upgrading illuminate/contracts (v10.21.0 => v10.21.1)
- Upgrading illuminate/events (v10.21.0 => v10.21.1)
- Upgrading illuminate/filesystem (v10.21.0 => v10.21.1)
- Upgrading illuminate/macroable (v10.21.0 => v10.21.1)
- Upgrading illuminate/pipeline (v10.21.0 => v10.21.1)
- Upgrading illuminate/process (v10.21.0 => v10.21.1)
- Upgrading illuminate/support (v10.21.0 => v10.21.1) …

Composer update with 16 changes 2023-09-05

---

update/composer.lock

- Upgrading illuminate/bus (v10.25.2 => v10.26.2)
- Upgrading illuminate/cache (v10.25.2 => v10.26.2)
- Upgrading illuminate/collections (v10.25.2 => v10.26.2)
- Upgrading illuminate/conditionable (v10.25.2 => v10.26.2)
- Upgrading illuminate/config (v10.25.2 => v10.26.2)
- Upgrading illuminate/console (v10.25.2 => v10.26.2)
- Upgrading illuminate/container (v10.25.2 => v10.26.2)
- Upgrading illuminate/contracts (v10.25.2 => v10.26.2)
- Upgrading illuminate/events (v10.25.2 => v10.26.2)
- Upgrading illuminate/filesystem (v10.25.2 => v10.26.2)
- Upgrading illuminate/macroable (v10.25.2 => v10.26.2)
- Upgrading illuminate/pipeline (v10.25.2 => v10.26.2)
- Upgrading illuminate/process (v10.25.2 => v10.26.2)
- Upgrading illuminate/support (v10.25.1 => v10.26.2) …

Composer update with 17 changes 2023-10-04

---

update/composer.lock

- Upgrading illuminate/bus (v10.26.2 => v10.27.0)
- Upgrading illuminate/cache (v10.26.2 => v10.27.0)
- Upgrading illuminate/collections (v10.26.2 => v10.27.0)
- Upgrading illuminate/conditionable (v10.26.2 => v10.27.0)
- Upgrading illuminate/config (v10.26.2 => v10.27.0)
- Upgrading illuminate/console (v10.26.2 => v10.27.0)
- Upgrading illuminate/container (v10.26.2 => v10.27.0)
- Upgrading illuminate/contracts (v10.26.2 => v10.27.0)
- Upgrading illuminate/events (v10.26.2 => v10.27.0)
- Upgrading illuminate/filesystem (v10.26.2 => v10.27.0)
- Upgrading illuminate/macroable (v10.26.2 => v10.27.0)
- Upgrading illuminate/pipeline (v10.26.2 => v10.27.0)
- Upgrading illuminate/process (v10.26.2 => v10.27.0)
- Upgrading illuminate/support (v10.26.2 => v10.27.0) …

Composer update with 16 changes 2023-10-10

---

update/composer.lock

- Upgrading illuminate/bus (v10.27.0 => v10.28.0)
- Upgrading illuminate/cache (v10.27.0 => v10.28.0)
- Upgrading illuminate/collections (v10.27.0 => v10.28.0)
- Upgrading illuminate/conditionable (v10.27.0 => v10.28.0)
- Upgrading illuminate/config (v10.27.0 => v10.28.0)
- Upgrading illuminate/console (v10.27.0 => v10.28.0)
- Upgrading illuminate/container (v10.27.0 => v10.28.0)
- Upgrading illuminate/contracts (v10.27.0 => v10.28.0)
- Upgrading illuminate/events (v10.27.0 => v10.28.0)
- Upgrading illuminate/filesystem (v10.27.0 => v10.28.0)
- Upgrading illuminate/macroable (v10.27.0 => v10.28.0)
- Upgrading illuminate/pipeline (v10.27.0 => v10.28.0)
- Upgrading illuminate/process (v10.27.0 => v10.28.0)
- Upgrading illuminate/support (v10.27.0 => v10.28.0) …

Composer update with 16 changes 2023-10-11

---

update/composer.lock

- Upgrading illuminate/bus (v10.30.1 => v10.31.0)
- Upgrading illuminate/cache (v10.30.1 => v10.31.0)
- Upgrading illuminate/collections (v10.30.1 => v10.31.0)
- Upgrading illuminate/conditionable (v10.30.1 => v10.31.0)
- Upgrading illuminate/config (v10.30.1 => v10.31.0)
- Upgrading illuminate/console (v10.30.1 => v10.31.0)
- Upgrading illuminate/container (v10.30.1 => v10.31.0)
- Upgrading illuminate/contracts (v10.30.1 => v10.31.0)
- Upgrading illuminate/events (v10.30.1 => v10.31.0)
- Upgrading illuminate/filesystem (v10.30.1 => v10.31.0)
- Upgrading illuminate/macroable (v10.30.1 => v10.31.0)
- Upgrading illuminate/pipeline (v10.30.1 => v10.31.0)
- Upgrading illuminate/process (v10.30.1 => v10.31.0)
- Upgrading illuminate/support (v10.30.1 => v10.31.0) …

Composer update with 18 changes 2023-11-08

---

update/composer.lock

- Upgrading illuminate/bus (v10.32.1 => v10.33.0)
- Upgrading illuminate/cache (v10.32.1 => v10.33.0)
- Upgrading illuminate/collections (v10.32.1 => v10.33.0)
- Upgrading illuminate/conditionable (v10.32.1 => v10.33.0)
- Upgrading illuminate/config (v10.32.1 => v10.33.0)
- Upgrading illuminate/console (v10.32.1 => v10.33.0)
- Upgrading illuminate/container (v10.32.1 => v10.33.0)
- Upgrading illuminate/contracts (v10.32.1 => v10.33.0)
- Upgrading illuminate/events (v10.32.1 => v10.33.0)
- Upgrading illuminate/filesystem (v10.32.1 => v10.33.0)
- Upgrading illuminate/macroable (v10.32.1 => v10.33.0)
- Upgrading illuminate/pipeline (v10.32.1 => v10.33.0)
- Upgrading illuminate/process (v10.32.1 => v10.33.0)
- Upgrading illuminate/support (v10.32.1 => v10.33.0) …

Composer update with 17 changes 2023-11-22

---

update/composer.lock

- Upgrading illuminate/bus (v10.33.0 => v10.34.2)
- Upgrading illuminate/cache (v10.33.0 => v10.34.2)
- Upgrading illuminate/collections (v10.33.0 => v10.34.2)
- Upgrading illuminate/conditionable (v10.33.0 => v10.34.2)
- Upgrading illuminate/config (v10.33.0 => v10.34.2)
- Upgrading illuminate/console (v10.33.0 => v10.34.2)
- Upgrading illuminate/container (v10.33.0 => v10.34.2)
- Upgrading illuminate/contracts (v10.33.0 => v10.34.2)
- Upgrading illuminate/events (v10.33.0 => v10.34.2)
- Upgrading illuminate/filesystem (v10.33.0 => v10.34.2)
- Upgrading illuminate/macroable (v10.33.0 => v10.34.2)
- Upgrading illuminate/pipeline (v10.33.0 => v10.34.2)
- Upgrading illuminate/process (v10.33.0 => v10.34.2)
- Upgrading illuminate/support (v10.33.0 => v10.34.2) …

Composer update with 25 changes 2023-11-30

---

update/composer.lock

- Upgrading illuminate/bus (v10.34.2 => v10.35.0)
- Upgrading illuminate/cache (v10.34.2 => v10.35.0)
- Upgrading illuminate/collections (v10.34.2 => v10.35.0)
- Upgrading illuminate/conditionable (v10.34.2 => v10.35.0)
- Upgrading illuminate/config (v10.34.2 => v10.35.0)
- Upgrading illuminate/console (v10.34.2 => v10.35.0)
- Upgrading illuminate/container (v10.34.2 => v10.35.0)
- Upgrading illuminate/contracts (v10.34.2 => v10.35.0)
- Upgrading illuminate/events (v10.34.2 => v10.35.0)
- Upgrading illuminate/filesystem (v10.34.2 => v10.35.0)
- Upgrading illuminate/macroable (v10.34.2 => v10.35.0)
- Upgrading illuminate/pipeline (v10.34.2 => v10.35.0)
- Upgrading illuminate/process (v10.34.2 => v10.35.0)
- Upgrading illuminate/support (v10.34.2 => v10.35.0) …

Composer update with 17 changes 2023-12-06

---

update/composer.lock

- Upgrading illuminate/bus (v10.37.3 => v10.38.0)
- Upgrading illuminate/cache (v10.37.3 => v10.38.0)
- Upgrading illuminate/collections (v10.37.3 => v10.38.0)
- Upgrading illuminate/conditionable (v10.37.3 => v10.38.0)
- Upgrading illuminate/config (v10.37.3 => v10.38.0)
- Upgrading illuminate/console (v10.37.3 => v10.38.0)
- Upgrading illuminate/container (v10.37.3 => v10.38.0)
- Upgrading illuminate/contracts (v10.37.3 => v10.38.0)
- Upgrading illuminate/events (v10.37.3 => v10.38.0)
- Upgrading illuminate/filesystem (v10.37.3 => v10.38.0)
- Upgrading illuminate/macroable (v10.37.3 => v10.38.0)
- Upgrading illuminate/pipeline (v10.37.3 => v10.38.0)
- Upgrading illuminate/process (v10.37.3 => v10.38.0)
- Upgrading illuminate/support (v10.37.3 => v10.38.0) …

Composer update with 16 changes 2023-12-20

---

update/composer.lock

- Upgrading clue/stream-filter (v1.6.0 => v1.7.0)
- Upgrading illuminate/bus (v10.38.0 => v10.38.1)
- Upgrading illuminate/cache (v10.38.0 => v10.38.1)
- Upgrading illuminate/collections (v10.38.0 => v10.38.1)
- Upgrading illuminate/conditionable (v10.38.0 => v10.38.1)
- Upgrading illuminate/config (v10.38.0 => v10.38.1)
- Upgrading illuminate/console (v10.38.0 => v10.38.1)
- Upgrading illuminate/container (v10.38.0 => v10.38.1)
- Upgrading illuminate/contracts (v10.38.0 => v10.38.1)
- Upgrading illuminate/events (v10.38.0 => v10.38.1)
- Upgrading illuminate/filesystem (v10.38.0 => v10.38.1)
- Upgrading illuminate/macroable (v10.38.0 => v10.38.1)
- Upgrading illuminate/pipeline (v10.38.0 => v10.38.1)
- Upgrading illuminate/process (v10.38.0 => v10.38.1)
- Upgrading illuminate/support …

Composer update with 17 changes 2023-12-21

---

update/composer.lock

- Upgrading illuminate/bus (v10.38.2 => v10.39.0)
- Upgrading illuminate/cache (v10.38.2 => v10.39.0)
- Upgrading illuminate/collections (v10.38.2 => v10.39.0)
- Upgrading illuminate/conditionable (v10.38.2 => v10.39.0)
- Upgrading illuminate/config (v10.38.2 => v10.39.0)
- Upgrading illuminate/console (v10.38.2 => v10.39.0)
- Upgrading illuminate/container (v10.38.2 => v10.39.0)
- Upgrading illuminate/contracts (v10.38.2 => v10.39.0)
- Upgrading illuminate/events (v10.38.2 => v10.39.0)
- Upgrading illuminate/filesystem (v10.38.2 => v10.39.0)
- Upgrading illuminate/macroable (v10.38.2 => v10.39.0)
- Upgrading illuminate/pipeline (v10.38.2 => v10.39.0)
- Upgrading illuminate/process (v10.38.2 => v10.39.0)
- Upgrading illuminate/support (v10.38.2 => v10.39.0) …

Composer update with 18 changes 2023-12-28

---

update/composer.lock

- Upgrading illuminate/bus (v10.42.0 => v10.43.0)
- Upgrading illuminate/cache (v10.42.0 => v10.43.0)
- Upgrading illuminate/collections (v10.42.0 => v10.43.0)
- Upgrading illuminate/conditionable (v10.42.0 => v10.43.0)
- Upgrading illuminate/config (v10.42.0 => v10.43.0)
- Upgrading illuminate/console (v10.42.0 => v10.43.0)
- Upgrading illuminate/container (v10.42.0 => v10.43.0)
- Upgrading illuminate/contracts (v10.42.0 => v10.43.0)
- Upgrading illuminate/events (v10.42.0 => v10.43.0)
- Upgrading illuminate/filesystem (v10.42.0 => v10.43.0)
- Upgrading illuminate/macroable (v10.42.0 => v10.43.0)
- Upgrading illuminate/pipeline (v10.42.0 => v10.43.0)
- Upgrading illuminate/process (v10.42.0 => v10.43.0)
- Upgrading illuminate/support (v10.42.0 => v10.43.0) …

Composer update with 16 changes 2024-01-31

---

update/composer.lock

- Upgrading illuminate/bus (v10.47.0 => v10.48.2)
- Upgrading illuminate/cache (v10.47.0 => v10.48.2)
- Upgrading illuminate/collections (v10.47.0 => v10.48.2)
- Upgrading illuminate/conditionable (v10.47.0 => v10.48.2)
- Upgrading illuminate/config (v10.47.0 => v10.48.2)
- Upgrading illuminate/console (v10.47.0 => v10.48.2)
- Upgrading illuminate/container (v10.47.0 => v10.48.2)
- Upgrading illuminate/contracts (v10.47.0 => v10.48.2)
- Upgrading illuminate/events (v10.47.0 => v10.48.2)
- Upgrading illuminate/filesystem (v10.47.0 => v10.48.2)
- Upgrading illuminate/macroable (v10.47.0 => v10.48.2)
- Upgrading illuminate/pipeline (v10.47.0 => v10.48.2)
- Upgrading illuminate/process (v10.47.0 => v10.48.2)
- Upgrading illuminate/support (v10.47.0 => v10.48.2) …

Composer update with 19 changes 2024-03-14

---

update/composer.lock

- Upgrading illuminate/bus (v10.48.2 => v10.48.3)
- Upgrading illuminate/cache (v10.48.2 => v10.48.3)
- Upgrading illuminate/collections (v10.48.2 => v10.48.3)
- Upgrading illuminate/conditionable (v10.48.2 => v10.48.3)
- Upgrading illuminate/config (v10.48.2 => v10.48.3)
- Upgrading illuminate/console (v10.48.2 => v10.48.3)
- Upgrading illuminate/container (v10.48.2 => v10.48.3)
- Upgrading illuminate/contracts (v10.48.2 => v10.48.3)
- Upgrading illuminate/events (v10.48.2 => v10.48.3)
- Upgrading illuminate/filesystem (v10.48.2 => v10.48.3)
- Upgrading illuminate/macroable (v10.48.2 => v10.48.3)
- Upgrading illuminate/pipeline (v10.48.2 => v10.48.3)
- Upgrading illuminate/process (v10.48.2 => v10.48.3)
- Upgrading illuminate/support (v10.48.2 => v10.48.3) …

Composer update with 17 changes 2024-03-16

---

update/composer.lock

- Upgrading illuminate/bus (v10.48.3 => v10.48.4)
- Upgrading illuminate/cache (v10.48.3 => v10.48.4)
- Upgrading illuminate/collections (v10.48.3 => v10.48.4)
- Upgrading illuminate/conditionable (v10.48.3 => v10.48.4)
- Upgrading illuminate/config (v10.48.3 => v10.48.4)
- Upgrading illuminate/console (v10.48.3 => v10.48.4)
- Upgrading illuminate/container (v10.48.3 => v10.48.4)
- Upgrading illuminate/contracts (v10.48.3 => v10.48.4)
- Upgrading illuminate/events (v10.48.3 => v10.48.4)
- Upgrading illuminate/filesystem (v10.48.3 => v10.48.4)
- Upgrading illuminate/macroable (v10.48.3 => v10.48.4)
- Upgrading illuminate/pipeline (v10.48.3 => v10.48.4)
- Upgrading illuminate/process (v10.48.3 => v10.48.4)
- Upgrading illuminate/support (v10.48.3 => v10.48.4) …

Composer update with 18 changes 2024-03-22

---

update/composer.lock

- Upgrading filp/whoops (2.15.4 => 2.16.0)
- Upgrading laravel/framework (v11.23.5 => v11.24.1)
- Upgrading laravel/pint (v1.17.3 => v1.18.1)
- Upgrading laravel/prompts (v0.1.25 => v0.2.1)
- Upgrading laravel/serializable-closure (v1.3.4 => v1.3.5)
- Upgrading laravel/tinker (v2.9.0 => v2.10.0)
- Upgrading php-http/client-common (2.7.1 => 2.7.2)

Composer update with 7 changes 2024-09-26

---

update/composer.lock

- Upgrading league/commonmark (2.5.3 => 2.6.0)
- Upgrading psy/psysh (v0.12.5 => v0.12.6)

Composer update with 2 changes 2024-12-08

---

update/composer.lock

- Removing doctrine/deprecations (1.1.4)
- Removing phpdocumentor/reflection-common (2.2.0)
- Removing phpdocumentor/type-resolver (1.10.0)
- Removing phpstan/phpdoc-parser (2.0.0)
- Upgrading barryvdh/laravel-ide-helper (v3.4.0 => v3.5.2)
- Upgrading sebastian/comparator (6.2.1 => 6.3.0)

Composer update with 6 changes 2025-01-07

---

update/composer.lock

- Upgrading laravel/pint (v1.21.1 => v1.21.2)
- Upgrading nunomaduro/collision (v8.6.1 => v8.7.0)

Composer update with 2 changes 2025-03-15
