update/composer.lock
- Upgrading mockery/mockery (1.6.1 => 1.6.2)
=> Composer update with 1 changes 2023-06-08

update/composer.lock
- Upgrading illuminate/bus (v10.13.2 => v10.13.5)
- Upgrading illuminate/cache (v10.13.2 => v10.13.5)
- Upgrading illuminate/collections (v10.13.2 => v10.13.5)
- Upgrading illuminate/conditionable (v10.13.2 => v10.13.5)
- Upgrading illuminate/config (v10.13.2 => v10.13.5)
- Upgrading illuminate/console (v10.13.2 => v10.13.5)
- Upgrading illuminate/container (v10.13.2 => v10.13.5)
- Upgrading illuminate/contracts (v10.13.2 => v10.13.5)
- Upgrading illuminate/events (v10.13.2 => v10.13.5)
- Upgrading illuminate/filesystem (v10.13.2 => v10.13.5)
- Upgrading illuminate/macroable (v10.13.2 => v10.13.5)
- Upgrading illuminate/pipeline (v10.13.2 => v10.13.5)
- Upgrading illuminate/process (v10.13.2 => v10.13.5)
- Upgrading illuminate/support (v10.13.2 => v10.13.5) …
=> Composer update with 16 changes 2023-06-10

update/composer.lock
- Upgrading phpunit/phpunit (10.2.1 => 10.2.2)
=> Composer update with 1 changes 2023-06-12

update/composer.lock
- Upgrading doctrine/inflector (2.0.6 => 2.0.8)
- Upgrading nunomaduro/collision (v7.5.2 => v7.6.0)
=> Composer update with 2 changes 2023-06-17

update/composer.lock
- Upgrading php-http/discovery (1.18.1 => 1.19.0)
=> Composer update with 1 changes 2023-06-20

update/composer.lock
- Upgrading laravel-zero/framework (v10.0.2 => v10.1.0)
=> Composer update with 1 changes 2023-06-22

update/composer.lock
- Upgrading nikic/php-parser (v4.15.5 => v4.16.0)
=> Composer update with 1 changes 2023-06-26

update/composer.lock
- Upgrading nunomaduro/laravel-console-summary (v1.9.1 => v1.10.0)
=> Composer update with 1 changes 2023-06-27

update/composer.lock
- Upgrading illuminate/bus (v10.13.5 => v10.14.0)
- Upgrading illuminate/cache (v10.13.5 => v10.14.0)
- Upgrading illuminate/collections (v10.13.5 => v10.14.0)
- Upgrading illuminate/conditionable (v10.13.5 => v10.14.0)
- Upgrading illuminate/config (v10.13.5 => v10.14.0)
- Upgrading illuminate/console (v10.13.5 => v10.14.0)
- Upgrading illuminate/container (v10.13.5 => v10.14.0)
- Upgrading illuminate/contracts (v10.13.5 => v10.14.0)
- Upgrading illuminate/events (v10.13.5 => v10.14.0)
- Upgrading illuminate/filesystem (v10.13.5 => v10.14.0)
- Upgrading illuminate/macroable (v10.13.5 => v10.14.0)
- Upgrading illuminate/pipeline (v10.13.5 => v10.14.0)
- Upgrading illuminate/process (v10.13.5 => v10.14.0)
- Upgrading illuminate/support (v10.13.5 => v10.14.0) …
=> Composer update with 16 changes 2023-06-28

update/composer.lock
- Upgrading illuminate/bus (v10.14.0 => v10.14.1)
- Upgrading illuminate/cache (v10.14.0 => v10.14.1)
- Upgrading illuminate/collections (v10.14.0 => v10.14.1)
- Upgrading illuminate/conditionable (v10.14.0 => v10.14.1)
- Upgrading illuminate/config (v10.14.0 => v10.14.1)
- Upgrading illuminate/console (v10.14.0 => v10.14.1)
- Upgrading illuminate/container (v10.14.0 => v10.14.1)
- Upgrading illuminate/contracts (v10.14.0 => v10.14.1)
- Upgrading illuminate/events (v10.14.0 => v10.14.1)
- Upgrading illuminate/filesystem (v10.14.0 => v10.14.1)
- Upgrading illuminate/macroable (v10.14.0 => v10.14.1)
- Upgrading illuminate/pipeline (v10.14.0 => v10.14.1)
- Upgrading illuminate/process (v10.14.0 => v10.14.1)
- Upgrading illuminate/support (v10.14.0 => v10.14.1) …
=> Composer update with 16 changes 2023-06-29

update/composer.lock
- Upgrading nunomaduro/collision (v7.6.0 => v7.7.0)
=> Composer update with 1 changes 2023-06-30

update/composer.lock
- Upgrading phpunit/phpunit (10.2.2 => 10.2.3)
=> Composer update with 1 changes 2023-07-01

update/composer.lock
- Upgrading nesbot/carbon (2.67.0 => 2.68.1)
=> Composer update with 1 changes 2023-07-04

update/composer.lock
- Upgrading phpunit/phpunit (10.2.3 => 10.2.4)
=> Composer update with 1 changes 2023-07-11

update/composer.lock
- Upgrading illuminate/bus (v10.14.1 => v10.15.0)
- Upgrading illuminate/cache (v10.14.1 => v10.15.0)
- Upgrading illuminate/collections (v10.14.1 => v10.15.0)
- Upgrading illuminate/conditionable (v10.14.1 => v10.15.0)
- Upgrading illuminate/config (v10.14.1 => v10.15.0)
- Upgrading illuminate/console (v10.14.1 => v10.15.0)
- Upgrading illuminate/container (v10.14.1 => v10.15.0)
- Upgrading illuminate/contracts (v10.14.1 => v10.15.0)
- Upgrading illuminate/events (v10.14.1 => v10.15.0)
- Upgrading illuminate/filesystem (v10.14.1 => v10.15.0)
- Upgrading illuminate/macroable (v10.14.1 => v10.15.0)
- Upgrading illuminate/pipeline (v10.14.1 => v10.15.0)
- Upgrading illuminate/process (v10.14.1 => v10.15.0)
- Upgrading illuminate/support (v10.14.1 => v10.15.0) …
=> Composer update with 17 changes 2023-07-12

update/composer.lock
- Upgrading czproject/git-php (v4.1.0 => v4.2.0)
=> Composer update with 1 changes 2023-07-13

update/composer.lock
- Upgrading filp/whoops (2.15.2 => 2.15.3)
=> Composer update with 1 changes 2023-07-14

update/composer.lock
- Upgrading laravel-zero/framework (v10.1.0 => v10.1.1)
=> Composer update with 1 changes 2023-07-15

update/composer.lock
- Upgrading phpunit/phpunit (10.2.5 => 10.2.6)
=> Composer update with 1 changes 2023-07-18

update/composer.lock
- Upgrading mockery/mockery (1.6.2 => 1.6.3)
=> Composer update with 1 changes 2023-07-19

update/composer.lock
- Upgrading mockery/mockery (1.6.3 => 1.6.4)
- Upgrading sebastian/global-state (6.0.0 => 6.0.1)
=> Composer update with 2 changes 2023-07-20

update/composer.lock
- Upgrading illuminate/bus (v10.15.0 => v10.16.1)
- Upgrading illuminate/cache (v10.15.0 => v10.16.1)
- Upgrading illuminate/collections (v10.15.0 => v10.16.1)
- Upgrading illuminate/conditionable (v10.15.0 => v10.16.1)
- Upgrading illuminate/config (v10.15.0 => v10.16.1)
- Upgrading illuminate/console (v10.15.0 => v10.16.1)
- Upgrading illuminate/container (v10.15.0 => v10.16.1)
- Upgrading illuminate/contracts (v10.15.0 => v10.16.1)
- Upgrading illuminate/events (v10.15.0 => v10.16.1)
- Upgrading illuminate/filesystem (v10.15.0 => v10.16.1)
- Upgrading illuminate/macroable (v10.15.0 => v10.16.1)
- Upgrading illuminate/pipeline (v10.15.0 => v10.16.1)
- Upgrading illuminate/process (v10.15.0 => v10.16.1)
- Upgrading illuminate/support (v10.15.0 => v10.16.1) …
=> Composer update with 16 changes 2023-07-26

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.2 => 10.1.3)
=> Composer update with 1 changes 2023-07-27

update/composer.lock
- Upgrading symfony/console (v6.3.0 => v6.3.2)
- Upgrading symfony/error-handler (v6.3.0 => v6.3.2)
- Upgrading symfony/event-dispatcher (v6.3.0 => v6.3.2)
- Upgrading symfony/finder (v6.3.0 => v6.3.2)
- Upgrading symfony/process (v6.3.0 => v6.3.2)
- Upgrading symfony/string (v6.3.0 => v6.3.2)
- Upgrading symfony/var-dumper (v6.3.1 => v6.3.2)
=> Composer update with 7 changes 2023-07-31

update/composer.lock
- Upgrading symfony/finder (v6.3.2 => v6.3.3)
- Upgrading symfony/translation (v6.3.0 => v6.3.3)
- Upgrading symfony/var-dumper (v6.3.2 => v6.3.3)
=> Composer update with 3 changes 2023-08-01

update/composer.lock
- Upgrading illuminate/bus (v10.16.1 => v10.17.0)
- Upgrading illuminate/cache (v10.16.1 => v10.17.0)
- Upgrading illuminate/collections (v10.16.1 => v10.17.0)
- Upgrading illuminate/conditionable (v10.16.1 => v10.17.0)
- Upgrading illuminate/config (v10.16.1 => v10.17.0)
- Upgrading illuminate/console (v10.16.1 => v10.17.0)
- Upgrading illuminate/container (v10.16.1 => v10.17.0)
- Upgrading illuminate/contracts (v10.16.1 => v10.17.0)
- Upgrading illuminate/events (v10.16.1 => v10.17.0)
- Upgrading illuminate/filesystem (v10.16.1 => v10.17.0)
- Upgrading illuminate/macroable (v10.16.1 => v10.17.0)
- Upgrading illuminate/pipeline (v10.16.1 => v10.17.0)
- Upgrading illuminate/process (v10.16.1 => v10.17.0)
- Upgrading illuminate/support (v10.16.1 => v10.17.0) …
=> Composer update with 17 changes 2023-08-02

update/composer.lock
- Upgrading illuminate/bus (v10.17.0 => v10.17.1)
- Upgrading illuminate/cache (v10.17.0 => v10.17.1)
- Upgrading illuminate/collections (v10.17.0 => v10.17.1)
- Upgrading illuminate/conditionable (v10.17.0 => v10.17.1)
- Upgrading illuminate/config (v10.17.0 => v10.17.1)
- Upgrading illuminate/console (v10.17.0 => v10.17.1)
- Upgrading illuminate/container (v10.17.0 => v10.17.1)
- Upgrading illuminate/contracts (v10.17.0 => v10.17.1)
- Upgrading illuminate/events (v10.17.0 => v10.17.1)
- Upgrading illuminate/filesystem (v10.17.0 => v10.17.1)
- Upgrading illuminate/macroable (v10.17.0 => v10.17.1)
- Upgrading illuminate/pipeline (v10.17.0 => v10.17.1)
- Upgrading illuminate/process (v10.17.0 => v10.17.1)
- Upgrading illuminate/support (v10.17.0 => v10.17.1) …
=> Composer update with 18 changes 2023-08-03

update/composer.lock
- Upgrading guzzlehttp/promises (2.0.0 => 2.0.1)
- Upgrading guzzlehttp/psr7 (2.5.0 => 2.6.0)
- Upgrading league/mime-type-detection (1.11.0 => 1.12.0)
- Upgrading phpunit/phpunit (10.2.7 => 10.3.0)
=> Composer update with 4 changes 2023-08-04

update/composer.lock
- Upgrading nunomaduro/collision (v7.7.0 => v7.8.0)
- Upgrading phpunit/phpunit (10.3.0 => 10.3.1)
=> Composer update with 2 changes 2023-08-05

update/composer.lock
- Upgrading league/mime-type-detection (1.12.0 => 1.13.0)
- Upgrading mockery/mockery (1.6.4 => 1.6.5)
=> Composer update with 2 changes 2023-08-06

update/composer.lock
- Upgrading nunomaduro/collision (v7.8.0 => v7.8.1)
=> Composer update with 1 changes 2023-08-08

update/composer.lock
- Upgrading illuminate/bus (v10.17.1 => v10.18.0)
- Upgrading illuminate/cache (v10.17.1 => v10.18.0)
- Upgrading illuminate/collections (v10.17.1 => v10.18.0)
- Upgrading illuminate/conditionable (v10.17.1 => v10.18.0)
- Upgrading illuminate/config (v10.17.1 => v10.18.0)
- Upgrading illuminate/console (v10.17.1 => v10.18.0)
- Upgrading illuminate/container (v10.17.1 => v10.18.0)
- Upgrading illuminate/contracts (v10.17.1 => v10.18.0)
- Upgrading illuminate/events (v10.17.1 => v10.18.0)
- Upgrading illuminate/filesystem (v10.17.1 => v10.18.0)
- Upgrading illuminate/macroable (v10.17.1 => v10.18.0)
- Upgrading illuminate/pipeline (v10.17.1 => v10.18.0)
- Upgrading illuminate/process (v10.17.1 => v10.18.0)
- Upgrading illuminate/support (v10.17.1 => v10.18.0) …
=> Composer update with 18 changes 2023-08-09

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.3.2 => v3.3.3)
=> Composer update with 1 changes 2023-08-11

update/composer.lock
- Upgrading nikic/php-parser (v4.16.0 => v4.17.1)
=> Composer update with 1 changes 2023-08-14

update/composer.lock
- Upgrading illuminate/bus (v10.18.0 => v10.19.0)
- Upgrading illuminate/cache (v10.18.0 => v10.19.0)
- Upgrading illuminate/collections (v10.18.0 => v10.19.0)
- Upgrading illuminate/conditionable (v10.18.0 => v10.19.0)
- Upgrading illuminate/config (v10.18.0 => v10.19.0)
- Upgrading illuminate/console (v10.18.0 => v10.19.0)
- Upgrading illuminate/container (v10.18.0 => v10.19.0)
- Upgrading illuminate/contracts (v10.18.0 => v10.19.0)
- Upgrading illuminate/events (v10.18.0 => v10.19.0)
- Upgrading illuminate/filesystem (v10.18.0 => v10.19.0)
- Upgrading illuminate/macroable (v10.18.0 => v10.19.0)
- Upgrading illuminate/pipeline (v10.18.0 => v10.19.0)
- Upgrading illuminate/process (v10.18.0 => v10.19.0)
- Upgrading illuminate/support (v10.18.0 => v10.19.0) …
=> Composer update with 19 changes 2023-08-16

update/composer.lock
- Upgrading nesbot/carbon (2.68.1 => 2.69.0)
- Locking psr/clock (1.0.0)
=> Composer update with 2 changes 2023-08-17

update/composer.lock
- Upgrading illuminate/bus (v10.19.0 => v10.20.0)
- Upgrading illuminate/cache (v10.19.0 => v10.20.0)
- Upgrading illuminate/collections (v10.19.0 => v10.20.0)
- Upgrading illuminate/conditionable (v10.19.0 => v10.20.0)
- Upgrading illuminate/config (v10.19.0 => v10.20.0)
- Upgrading illuminate/console (v10.19.0 => v10.20.0)
- Upgrading illuminate/container (v10.19.0 => v10.20.0)
- Upgrading illuminate/contracts (v10.19.0 => v10.20.0)
- Upgrading illuminate/events (v10.19.0 => v10.20.0)
- Upgrading illuminate/filesystem (v10.19.0 => v10.20.0)
- Upgrading illuminate/macroable (v10.19.0 => v10.20.0)
- Upgrading illuminate/pipeline (v10.19.0 => v10.20.0)
- Upgrading illuminate/process (v10.19.0 => v10.20.0)
- Upgrading illuminate/support (v10.19.0 => v10.20.0) …
=> Composer update with 18 changes 2023-08-23

update/composer.lock
- Upgrading symfony/console (v6.3.2 => v6.3.4)
- Upgrading symfony/process (v6.3.2 => v6.3.4)
- Upgrading symfony/var-dumper (v6.3.3 => v6.3.4)
=> Composer update with 3 changes 2023-08-27

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.7.0 => 7.8.0)
- Upgrading guzzlehttp/psr7 (2.6.0 => 2.6.1)
=> Composer update with 2 changes 2023-08-28

update/composer.lock
- Upgrading symfony/polyfill-ctype (v1.27.0 => v1.28.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.27.0 => v1.28.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.27.0 => v1.28.0)
- Upgrading symfony/polyfill-mbstring (v1.27.0 => v1.28.0)
- Upgrading symfony/polyfill-php80 (v1.27.0 => v1.28.0)
=> Composer update with 5 changes 2023-08-29

update/composer.lock
- Upgrading illuminate/bus (v10.20.0 => v10.21.0)
- Upgrading illuminate/cache (v10.20.0 => v10.21.0)
- Upgrading illuminate/collections (v10.20.0 => v10.21.0)
- Upgrading illuminate/conditionable (v10.20.0 => v10.21.0)
- Upgrading illuminate/config (v10.20.0 => v10.21.0)
- Upgrading illuminate/console (v10.20.0 => v10.21.0)
- Upgrading illuminate/container (v10.20.0 => v10.21.0)
- Upgrading illuminate/contracts (v10.20.0 => v10.21.0)
- Upgrading illuminate/events (v10.20.0 => v10.21.0)
- Upgrading illuminate/filesystem (v10.20.0 => v10.21.0)
- Upgrading illuminate/macroable (v10.20.0 => v10.21.0)
- Upgrading illuminate/pipeline (v10.20.0 => v10.21.0)
- Upgrading illuminate/process (v10.20.0 => v10.21.0)
- Upgrading illuminate/support (v10.20.0 => v10.21.0) …
=> Composer update with 17 changes 2023-08-30

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.3 => 10.1.4)
- Upgrading phpunit/php-file-iterator (4.0.2 => 4.1.0)
- Upgrading phpunit/php-text-template (3.0.0 => 3.0.1)
- Upgrading sebastian/complexity (3.0.0 => 3.0.1)
- Upgrading sebastian/lines-of-code (2.0.0 => 2.0.1)
=> Composer update with 5 changes 2023-09-01

update/composer.lock
- Upgrading illuminate/bus (v10.21.1 => v10.22.0)
- Upgrading illuminate/cache (v10.21.1 => v10.22.0)
- Upgrading illuminate/collections (v10.21.1 => v10.22.0)
- Upgrading illuminate/conditionable (v10.21.1 => v10.22.0)
- Upgrading illuminate/config (v10.21.1 => v10.22.0)
- Upgrading illuminate/console (v10.21.1 => v10.22.0)
- Upgrading illuminate/container (v10.21.1 => v10.22.0)
- Upgrading illuminate/contracts (v10.21.1 => v10.22.0)
- Upgrading illuminate/events (v10.21.1 => v10.22.0)
- Upgrading illuminate/filesystem (v10.21.1 => v10.22.0)
- Upgrading illuminate/macroable (v10.21.1 => v10.22.0)
- Upgrading illuminate/pipeline (v10.21.1 => v10.22.0)
- Upgrading illuminate/process (v10.21.1 => v10.22.0)
- Upgrading illuminate/support (v10.21.1 => v10.22.0) …
=> Composer update with 17 changes 2023-09-06

update/composer.lock
- Upgrading league/flysystem (3.15.1 => 3.16.0)
- Upgrading league/flysystem-local (3.15.0 => 3.16.0)
- Upgrading nesbot/carbon (2.69.0 => 2.70.0)
=> Composer update with 3 changes 2023-09-08

update/composer.lock
- Upgrading sebastian/exporter (5.0.0 => 5.0.1)
=> Composer update with 1 changes 2023-09-09

update/composer.lock
- Upgrading illuminate/bus (v10.22.0 => v10.23.0)
- Upgrading illuminate/cache (v10.22.0 => v10.23.0)
- Upgrading illuminate/collections (v10.22.0 => v10.23.0)
- Upgrading illuminate/conditionable (v10.22.0 => v10.23.0)
- Upgrading illuminate/config (v10.22.0 => v10.23.0)
- Upgrading illuminate/console (v10.22.0 => v10.23.0)
- Upgrading illuminate/container (v10.22.0 => v10.23.0)
- Upgrading illuminate/contracts (v10.22.0 => v10.23.0)
- Upgrading illuminate/events (v10.22.0 => v10.23.0)
- Upgrading illuminate/filesystem (v10.22.0 => v10.23.0)
- Upgrading illuminate/macroable (v10.22.0 => v10.23.0)
- Upgrading illuminate/pipeline (v10.22.0 => v10.23.0)
- Upgrading illuminate/process (v10.22.0 => v10.23.0)
- Upgrading illuminate/support (v10.22.0 => v10.23.0) …
=> Composer update with 20 changes 2023-09-13

update/composer.lock
- Upgrading illuminate/bus (v10.23.0 => v10.23.1)
- Upgrading illuminate/cache (v10.23.0 => v10.23.1)
- Upgrading illuminate/collections (v10.23.0 => v10.23.1)
- Upgrading illuminate/conditionable (v10.23.0 => v10.23.1)
- Upgrading illuminate/config (v10.23.0 => v10.23.1)
- Upgrading illuminate/console (v10.23.0 => v10.23.1)
- Upgrading illuminate/container (v10.23.0 => v10.23.1)
- Upgrading illuminate/contracts (v10.23.0 => v10.23.1)
- Upgrading illuminate/events (v10.23.0 => v10.23.1)
- Upgrading illuminate/filesystem (v10.23.0 => v10.23.1)
- Upgrading illuminate/macroable (v10.23.0 => v10.23.1)
- Upgrading illuminate/pipeline (v10.23.0 => v10.23.1)
- Upgrading illuminate/process (v10.23.0 => v10.23.1)
- Upgrading illuminate/support (v10.23.0 => v10.23.1) …
=> Composer update with 17 changes 2023-09-14

update/composer.lock
- Upgrading sebastian/exporter (5.0.1 => 5.1.0)
=> Composer update with 1 changes 2023-09-19

update/composer.lock
- Upgrading illuminate/bus (v10.23.1 => v10.24.0)
- Upgrading illuminate/cache (v10.23.1 => v10.24.0)
- Upgrading illuminate/collections (v10.23.1 => v10.24.0)
- Upgrading illuminate/conditionable (v10.23.1 => v10.24.0)
- Upgrading illuminate/config (v10.23.1 => v10.24.0)
- Upgrading illuminate/console (v10.23.1 => v10.24.0)
- Upgrading illuminate/container (v10.23.1 => v10.24.0)
- Upgrading illuminate/contracts (v10.23.1 => v10.24.0)
- Upgrading illuminate/events (v10.23.1 => v10.24.0)
- Upgrading illuminate/filesystem (v10.23.1 => v10.24.0)
- Upgrading illuminate/macroable (v10.23.1 => v10.24.0)
- Upgrading illuminate/pipeline (v10.23.1 => v10.24.0)
- Upgrading illuminate/process (v10.23.1 => v10.24.0)
- Upgrading illuminate/support (v10.23.1 => v10.24.0) …
=> Composer update with 20 changes 2023-09-20

update/composer.lock
- Upgrading psr/http-client (1.0.2 => 1.0.3)
=> Composer update with 1 changes 2023-09-24

update/composer.lock
- Upgrading sebastian/exporter (5.1.0 => 5.1.1)
=> Composer update with 1 changes 2023-09-25

update/composer.lock
- Upgrading nesbot/carbon (2.70.0 => 2.71.0)
=> Composer update with 1 changes 2023-09-26

update/composer.lock
- Upgrading illuminate/bus (v10.24.0 => v10.25.1)
- Upgrading illuminate/cache (v10.24.0 => v10.25.1)
- Upgrading illuminate/collections (v10.24.0 => v10.25.1)
- Upgrading illuminate/conditionable (v10.24.0 => v10.25.1)
- Upgrading illuminate/config (v10.24.0 => v10.25.1)
- Upgrading illuminate/console (v10.24.0 => v10.25.1)
- Upgrading illuminate/container (v10.24.0 => v10.25.1)
- Upgrading illuminate/contracts (v10.24.0 => v10.25.1)
- Upgrading illuminate/events (v10.24.0 => v10.25.1)
- Upgrading illuminate/filesystem (v10.24.0 => v10.25.1)
- Upgrading illuminate/macroable (v10.24.0 => v10.25.1)
- Upgrading illuminate/pipeline (v10.24.0 => v10.25.1)
- Upgrading illuminate/process (v10.24.0 => v10.25.1)
- Upgrading illuminate/support (v10.24.0 => v10.25.1) …
=> Composer update with 17 changes 2023-09-27

update/composer.lock
- Upgrading illuminate/bus (v10.25.1 => v10.25.2)
- Upgrading illuminate/cache (v10.25.1 => v10.25.2)
- Upgrading illuminate/collections (v10.25.1 => v10.25.2)
- Upgrading illuminate/conditionable (v10.25.1 => v10.25.2)
- Upgrading illuminate/config (v10.25.1 => v10.25.2)
- Upgrading illuminate/console (v10.25.1 => v10.25.2)
- Upgrading illuminate/container (v10.25.1 => v10.25.2)
- Upgrading illuminate/contracts (v10.25.1 => v10.25.2)
- Upgrading illuminate/events (v10.25.1 => v10.25.2)
- Upgrading illuminate/filesystem (v10.25.1 => v10.25.2)
- Upgrading illuminate/macroable (v10.25.1 => v10.25.2)
- Upgrading illuminate/pipeline (v10.25.1 => v10.25.2)
- Upgrading illuminate/process (v10.25.1 => v10.25.2)
- Upgrading sebastian/complexity (3.0.1 => 3.1.0)
=> Composer update with 14 changes 2023-09-29

update/composer.lock
- Upgrading laravel/prompts (v0.1.9 => v0.1.10)
=> Composer update with 1 changes 2023-09-30

update/composer.lock
- Upgrading knplabs/github-api (v3.11.0 => v3.12.0)
- Upgrading psr/http-message (1.1 => 2.0)
- Upgrading symfony/error-handler (v6.3.2 => v6.3.5)
- Upgrading symfony/finder (v6.3.3 => v6.3.5)
- Upgrading symfony/string (v6.3.2 => v6.3.5)
- Upgrading symfony/var-dumper (v6.3.4 => v6.3.5)
=> Composer update with 6 changes 2023-10-01

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.6 => 10.1.7)
=> Composer update with 1 changes 2023-10-05

update/composer.lock
- Upgrading league/flysystem (3.16.0 => 3.17.0)
- Upgrading phpunit/phpunit (10.3.5 => 10.4.0)
=> Composer update with 2 changes 2023-10-06

update/composer.lock
- Upgrading laravel-zero/foundation (v10.23.0 => v10.26.2)
=> Composer update with 1 changes 2023-10-08

update/composer.lock
- Upgrading phpunit/phpunit (10.4.0 => 10.4.1)
=> Composer update with 1 changes 2023-10-09

update/composer.lock
- Upgrading laravel-zero/foundation (v10.26.2 => v10.28.0)
- Upgrading laravel-zero/framework (v10.1.2 => v10.2.0)
=> Composer update with 2 changes 2023-10-14

update/composer.lock
- Upgrading league/mime-type-detection (1.13.0 => 1.14.0)
=> Composer update with 1 changes 2023-10-18

update/composer.lock
- Upgrading league/flysystem (3.17.0 => 3.18.0)
- Upgrading league/flysystem-local (3.16.0 => 3.18.0)
=> Composer update with 2 changes 2023-10-21

update/composer.lock
- Upgrading symfony/translation (v6.3.3 => v6.3.6)
- Upgrading symfony/var-dumper (v6.3.5 => v6.3.6)
=> Composer update with 2 changes 2023-10-23

update/composer.lock
- Upgrading illuminate/bus (v10.28.0 => v10.29.0)
- Upgrading illuminate/cache (v10.28.0 => v10.29.0)
- Upgrading illuminate/collections (v10.28.0 => v10.29.0)
- Upgrading illuminate/conditionable (v10.28.0 => v10.29.0)
- Upgrading illuminate/config (v10.28.0 => v10.29.0)
- Upgrading illuminate/console (v10.28.0 => v10.29.0)
- Upgrading illuminate/container (v10.28.0 => v10.29.0)
- Upgrading illuminate/contracts (v10.28.0 => v10.29.0)
- Upgrading illuminate/events (v10.28.0 => v10.29.0)
- Upgrading illuminate/filesystem (v10.28.0 => v10.29.0)
- Upgrading illuminate/macroable (v10.28.0 => v10.29.0)
- Upgrading illuminate/pipeline (v10.28.0 => v10.29.0)
- Upgrading illuminate/process (v10.28.0 => v10.29.0)
- Upgrading illuminate/support (v10.28.0 => v10.29.0) …
=> Composer update with 18 changes 2023-10-25

update/composer.lock
- Upgrading phpunit/phpunit (10.4.1 => 10.4.2)
=> Composer update with 1 changes 2023-10-28

update/composer.lock
- Upgrading symfony/translation (v6.3.6 => v6.3.7)
=> Composer update with 1 changes 2023-10-30

update/composer.lock
- Upgrading laravel-zero/framework (v10.2.0 => v10.3.0)
=> Composer update with 1 changes 2023-10-31

update/composer.lock
- Upgrading illuminate/bus (v10.29.0 => v10.30.0)
- Upgrading illuminate/cache (v10.29.0 => v10.30.0)
- Upgrading illuminate/collections (v10.29.0 => v10.30.0)
- Upgrading illuminate/conditionable (v10.29.0 => v10.30.0)
- Upgrading illuminate/config (v10.29.0 => v10.30.0)
- Upgrading illuminate/console (v10.29.0 => v10.30.0)
- Upgrading illuminate/container (v10.29.0 => v10.30.0)
- Upgrading illuminate/contracts (v10.29.0 => v10.30.0)
- Upgrading illuminate/events (v10.29.0 => v10.30.0)
- Upgrading illuminate/filesystem (v10.29.0 => v10.30.0)
- Upgrading illuminate/macroable (v10.29.0 => v10.30.0)
- Upgrading illuminate/pipeline (v10.29.0 => v10.30.0)
- Upgrading illuminate/process (v10.29.0 => v10.30.0)
- Upgrading illuminate/support (v10.29.0 => v10.30.0) …
=> Composer update with 18 changes 2023-11-01

update/composer.lock
- Upgrading illuminate/bus (v10.30.0 => v10.30.1)
- Upgrading illuminate/cache (v10.30.0 => v10.30.1)
- Upgrading illuminate/collections (v10.30.0 => v10.30.1)
- Upgrading illuminate/conditionable (v10.30.0 => v10.30.1)
- Upgrading illuminate/config (v10.30.0 => v10.30.1)
- Upgrading illuminate/console (v10.30.0 => v10.30.1)
- Upgrading illuminate/container (v10.30.0 => v10.30.1)
- Upgrading illuminate/contracts (v10.30.0 => v10.30.1)
- Upgrading illuminate/events (v10.30.0 => v10.30.1)
- Upgrading illuminate/filesystem (v10.30.0 => v10.30.1)
- Upgrading illuminate/macroable (v10.30.0 => v10.30.1)
- Upgrading illuminate/pipeline (v10.30.0 => v10.30.1)
- Upgrading illuminate/process (v10.30.0 => v10.30.1)
- Upgrading illuminate/support (v10.30.0 => v10.30.1) …
=> Composer update with 16 changes 2023-11-02

update/composer.lock
- Upgrading filp/whoops (2.15.3 => 2.15.4)
=> Composer update with 1 changes 2023-11-04

update/composer.lock
- Upgrading php-http/promise (1.2.0 => 1.2.1)
- Upgrading ramsey/uuid (4.7.4 => 4.7.5)
=> Composer update with 2 changes 2023-11-09

update/composer.lock
- Upgrading symfony/console (v6.3.4 => v6.3.8)
- Upgrading symfony/string (v6.3.5 => v6.3.8)
- Upgrading symfony/var-dumper (v6.3.6 => v6.3.8)
=> Composer update with 3 changes 2023-11-11

update/composer.lock
- Upgrading graham-campbell/result-type (v1.1.1 => v1.1.2)
- Upgrading phpoption/phpoption (1.9.1 => 1.9.2)
- Upgrading vlucas/phpdotenv (v5.5.0 => v5.6.0)
=> Composer update with 3 changes 2023-11-13

update/composer.lock
- Upgrading illuminate/bus (v10.31.0 => v10.32.1)
- Upgrading illuminate/cache (v10.31.0 => v10.32.1)
- Upgrading illuminate/collections (v10.31.0 => v10.32.1)
- Upgrading illuminate/conditionable (v10.31.0 => v10.32.1)
- Upgrading illuminate/config (v10.31.0 => v10.32.1)
- Upgrading illuminate/console (v10.31.0 => v10.32.1)
- Upgrading illuminate/container (v10.31.0 => v10.32.1)
- Upgrading illuminate/contracts (v10.31.0 => v10.32.1)
- Upgrading illuminate/events (v10.31.0 => v10.32.1)
- Upgrading illuminate/filesystem (v10.31.0 => v10.32.1)
- Upgrading illuminate/macroable (v10.31.0 => v10.32.1)
- Upgrading illuminate/pipeline (v10.31.0 => v10.32.1)
- Upgrading illuminate/process (v10.31.0 => v10.32.1)
- Upgrading illuminate/support (v10.31.0 => v10.32.1) …
=> Composer update with 16 changes 2023-11-15

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.7 => 10.1.8)
- Upgrading symfony/deprecation-contracts (v3.3.0 => v3.4.0)
- Upgrading symfony/event-dispatcher-contracts (v3.3.0 => v3.4.0)
- Upgrading symfony/service-contracts (v3.3.0 => v3.4.0)
- Upgrading symfony/translation-contracts (v3.3.0 => v3.4.0)
=> Composer update with 5 changes 2023-11-16

update/composer.lock
- Upgrading league/flysystem (3.19.0 => 3.21.0)
- Upgrading league/flysystem-local (3.19.0 => 3.21.0)
=> Composer update with 2 changes 2023-11-19

update/composer.lock
- Upgrading knplabs/github-api (v3.12.0 => v3.13.0)
- Upgrading theseer/tokenizer (1.2.1 => 1.2.2)
=> Composer update with 2 changes 2023-11-20

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.8 => 10.1.9)
=> Composer update with 1 changes 2023-11-24

update/composer.lock
- Upgrading php-http/client-common (2.7.0 => 2.7.1)
- Upgrading php-http/discovery (1.19.1 => 1.19.2)
- Upgrading symfony/options-resolver (v6.4.0 => v7.0.0)
=> Composer update with 3 changes 2023-12-01

update/composer.lock
- Upgrading phpunit/phpunit (10.4.2 => 10.5.1)
- Upgrading symfony/console (v6.4.0 => v6.4.1)
=> Composer update with 2 changes 2023-12-02

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.8.0 => 7.8.1)
- Upgrading guzzlehttp/promises (2.0.1 => 2.0.2)
- Upgrading guzzlehttp/psr7 (2.6.1 => 2.6.2)
- Upgrading jolicode/jolinotif (v2.5.2 => v2.6.0)
- Locking jolicode/php-os-helper (v0.1.0)
- Upgrading league/flysystem (3.21.0 => 3.22.0)
- Upgrading league/flysystem-local (3.21.0 => 3.22.0)
=> Composer update with 7 changes 2023-12-04

update/composer.lock
- Upgrading league/flysystem (3.22.0 => 3.23.0)
- Upgrading league/flysystem-local (3.22.0 => 3.23.0)
=> Composer update with 2 changes 2023-12-05

update/composer.lock
- Upgrading mockery/mockery (1.6.6 => 1.6.7)
- Upgrading nesbot/carbon (2.72.0 => 2.72.1)
=> Composer update with 2 changes 2023-12-10

update/composer.lock
- Upgrading carbonphp/carbon-doctrine-types (3.0.0 => 3.1.0)
- Upgrading nikic/php-parser (v4.17.1 => v4.18.0)
=> Composer update with 2 changes 2023-12-11

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.9 => 10.1.10)
=> Composer update with 1 changes 2023-12-12

update/composer.lock
- Upgrading illuminate/bus (v10.35.0 => v10.37.3)
- Upgrading illuminate/cache (v10.35.0 => v10.37.3)
- Upgrading illuminate/collections (v10.35.0 => v10.37.3)
- Upgrading illuminate/conditionable (v10.35.0 => v10.37.3)
- Upgrading illuminate/config (v10.35.0 => v10.37.3)
- Upgrading illuminate/console (v10.35.0 => v10.37.3)
- Upgrading illuminate/container (v10.35.0 => v10.37.3)
- Upgrading illuminate/contracts (v10.35.0 => v10.37.3)
- Upgrading illuminate/events (v10.35.0 => v10.37.3)
- Upgrading illuminate/filesystem (v10.35.0 => v10.37.3)
- Upgrading illuminate/macroable (v10.35.0 => v10.37.3)
- Upgrading illuminate/pipeline (v10.35.0 => v10.37.3)
- Upgrading illuminate/process (v10.35.0 => v10.37.3)
- Upgrading illuminate/support (v10.35.0 => v10.37.3) …
=> Composer update with 17 changes 2023-12-14

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.10 => 10.1.11)
- Upgrading sebastian/complexity (3.1.0 => 3.2.0)
- Upgrading sebastian/lines-of-code (2.0.1 => 2.0.2)
=> Composer update with 3 changes 2023-12-22

update/composer.lock
- Upgrading illuminate/bus (v10.38.1 => v10.38.2)
- Upgrading illuminate/cache (v10.38.1 => v10.38.2)
- Upgrading illuminate/collections (v10.38.1 => v10.38.2)
- Upgrading illuminate/conditionable (v10.38.1 => v10.38.2)
- Upgrading illuminate/config (v10.38.1 => v10.38.2)
- Upgrading illuminate/console (v10.38.1 => v10.38.2)
- Upgrading illuminate/container (v10.38.1 => v10.38.2)
- Upgrading illuminate/contracts (v10.38.1 => v10.38.2)
- Upgrading illuminate/events (v10.38.1 => v10.38.2)
- Upgrading illuminate/filesystem (v10.38.1 => v10.38.2)
- Upgrading illuminate/macroable (v10.38.1 => v10.38.2)
- Upgrading illuminate/pipeline (v10.38.1 => v10.38.2)
- Upgrading illuminate/process (v10.38.1 => v10.38.2)
- Upgrading illuminate/support (v10.38.1 => v10.38.2) …
=> Composer update with 17 changes 2023-12-23

update/composer.lock
- Upgrading symfony/service-contracts (v3.4.0 => v3.4.1)
- Upgrading symfony/translation-contracts (v3.4.0 => v3.4.1)
=> Composer update with 2 changes 2023-12-29

update/composer.lock
- Upgrading symfony/console (v6.4.1 => v6.4.2)
- Upgrading symfony/event-dispatcher (v6.4.0 => v6.4.2)
- Upgrading symfony/process (v6.4.0 => v6.4.2)
- Upgrading symfony/string (v7.0.0 => v7.0.2)
- Upgrading symfony/translation (v6.4.0 => v6.4.2)
- Upgrading symfony/var-dumper (v6.4.0 => v6.4.2)
=> Composer update with 6 changes 2023-12-31

update/composer.lock
- Upgrading php-http/promise (1.2.1 => 1.3.0)
=> Composer update with 1 changes 2024-01-05

update/composer.lock
- Upgrading nikic/php-parser (v4.18.0 => v5.0.0)
=> Composer update with 1 changes 2024-01-08

update/composer.lock
- Upgrading illuminate/bus (v10.39.0 => v10.40.0)
- Upgrading illuminate/cache (v10.39.0 => v10.40.0)
- Upgrading illuminate/collections (v10.39.0 => v10.40.0)
- Upgrading illuminate/conditionable (v10.39.0 => v10.40.0)
- Upgrading illuminate/config (v10.39.0 => v10.40.0)
- Upgrading illuminate/console (v10.39.0 => v10.40.0)
- Upgrading illuminate/container (v10.39.0 => v10.40.0)
- Upgrading illuminate/contracts (v10.39.0 => v10.40.0)
- Upgrading illuminate/events (v10.39.0 => v10.40.0)
- Upgrading illuminate/filesystem (v10.39.0 => v10.40.0)
- Upgrading illuminate/macroable (v10.39.0 => v10.40.0)
- Upgrading illuminate/pipeline (v10.39.0 => v10.40.0)
- Upgrading illuminate/process (v10.39.0 => v10.40.0)
- Upgrading illuminate/support (v10.39.0 => v10.40.0) …
=> Composer update with 17 changes 2024-01-10

update/composer.lock
- Upgrading phpunit/phpunit (10.5.5 => 10.5.6)
=> Composer update with 1 changes 2024-01-14

update/composer.lock
- Upgrading phpunit/phpunit (10.5.6 => 10.5.7)
=> Composer update with 1 changes 2024-01-15

update/composer.lock
- Upgrading doctrine/inflector (2.0.8 => 2.0.9)
=> Composer update with 1 changes 2024-01-16

update/composer.lock
- Upgrading illuminate/bus (v10.40.0 => v10.41.0)
- Upgrading illuminate/cache (v10.40.0 => v10.41.0)
- Upgrading illuminate/collections (v10.40.0 => v10.41.0)
- Upgrading illuminate/conditionable (v10.40.0 => v10.41.0)
- Upgrading illuminate/config (v10.40.0 => v10.41.0)
- Upgrading illuminate/console (v10.40.0 => v10.41.0)
- Upgrading illuminate/container (v10.40.0 => v10.41.0)
- Upgrading illuminate/contracts (v10.40.0 => v10.41.0)
- Upgrading illuminate/events (v10.40.0 => v10.41.0)
- Upgrading illuminate/filesystem (v10.40.0 => v10.41.0)
- Upgrading illuminate/macroable (v10.40.0 => v10.41.0)
- Upgrading illuminate/pipeline (v10.40.0 => v10.41.0)
- Upgrading illuminate/process (v10.40.0 => v10.41.0)
- Upgrading illuminate/support (v10.40.0 => v10.41.0) …
=> Composer update with 16 changes 2024-01-17

update/composer.lock
- Upgrading phpunit/phpunit (10.5.7 => 10.5.8)
=> Composer update with 1 changes 2024-01-20

update/composer.lock
- Upgrading phpunit/phpunit (10.5.8 => 10.5.9)
=> Composer update with 1 changes 2024-01-23

update/composer.lock
- Upgrading illuminate/bus (v10.41.0 => v10.42.0)
- Upgrading illuminate/cache (v10.41.0 => v10.42.0)
- Upgrading illuminate/collections (v10.41.0 => v10.42.0)
- Upgrading illuminate/conditionable (v10.41.0 => v10.42.0)
- Upgrading illuminate/config (v10.41.0 => v10.42.0)
- Upgrading illuminate/console (v10.41.0 => v10.42.0)
- Upgrading illuminate/container (v10.41.0 => v10.42.0)
- Upgrading illuminate/contracts (v10.41.0 => v10.42.0)
- Upgrading illuminate/events (v10.41.0 => v10.42.0)
- Upgrading illuminate/filesystem (v10.41.0 => v10.42.0)
- Upgrading illuminate/macroable (v10.41.0 => v10.42.0)
- Upgrading illuminate/pipeline (v10.41.0 => v10.42.0)
- Upgrading illuminate/process (v10.41.0 => v10.42.0)
- Upgrading illuminate/support (v10.41.0 => v10.42.0) …
=> Composer update with 17 changes 2024-01-24

update/composer.lock
- Upgrading league/flysystem (3.23.0 => 3.23.1)
- Upgrading league/flysystem-local (3.23.0 => 3.23.1)
=> Composer update with 2 changes 2024-01-27

update/composer.lock
- Upgrading league/mime-type-detection (1.14.0 => 1.15.0)
=> Composer update with 1 changes 2024-01-29

update/composer.lock
- Upgrading nesbot/carbon (2.72.2 => 2.72.3)
- Upgrading symfony/console (v6.4.2 => v6.4.3)
- Upgrading symfony/error-handler (v6.4.0 => v6.4.3)
- Upgrading symfony/event-dispatcher (v6.4.2 => v6.4.3)
- Upgrading symfony/process (v6.4.2 => v6.4.3)
- Upgrading symfony/string (v7.0.2 => v7.0.3)
- Upgrading symfony/translation (v6.4.2 => v6.4.3)
- Upgrading symfony/var-dumper (v6.4.2 => v6.4.3)
=> Composer update with 8 changes 2024-02-01

update/composer.lock
- Upgrading league/flysystem (3.23.1 => 3.24.0)
- Upgrading phpunit/phpunit (10.5.9 => 10.5.10)
=> Composer update with 2 changes 2024-02-05

update/composer.lock
- Upgrading symfony/polyfill-ctype (v1.28.0 => v1.29.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.28.0 => v1.29.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.28.0 => v1.29.0)
- Upgrading symfony/polyfill-mbstring (v1.28.0 => v1.29.0)
- Upgrading symfony/polyfill-php80 (v1.28.0 => v1.29.0)
=> Composer update with 5 changes 2024-02-06

update/composer.lock
- Upgrading carbonphp/carbon-doctrine-types (3.1.0 => 3.2.0)
=> Composer update with 1 changes 2024-02-10

update/composer.lock
- Upgrading doctrine/inflector (2.0.9 => 2.0.10)
=> Composer update with 1 changes 2024-02-19

update/composer.lock
- Upgrading illuminate/bus (v10.44.0 => v10.45.0)
- Upgrading illuminate/cache (v10.44.0 => v10.45.0)
- Upgrading illuminate/collections (v10.44.0 => v10.45.0)
- Upgrading illuminate/conditionable (v10.44.0 => v10.45.0)
- Upgrading illuminate/config (v10.44.0 => v10.45.0)
- Upgrading illuminate/console (v10.44.0 => v10.45.0)
- Upgrading illuminate/container (v10.44.0 => v10.45.0)
- Upgrading illuminate/contracts (v10.44.0 => v10.45.0)
- Upgrading illuminate/events (v10.44.0 => v10.45.0)
- Upgrading illuminate/filesystem (v10.44.0 => v10.45.0)
- Upgrading illuminate/macroable (v10.44.0 => v10.45.0)
- Upgrading illuminate/pipeline (v10.44.0 => v10.45.0)
- Upgrading illuminate/process (v10.44.0 => v10.45.0)
- Upgrading illuminate/support (v10.44.0 => v10.45.0) …
=> Composer update with 17 changes 2024-02-21

update/composer.lock
- Upgrading illuminate/bus (v10.45.0 => v10.45.1)
- Upgrading illuminate/cache (v10.45.0 => v10.45.1)
- Upgrading illuminate/collections (v10.45.0 => v10.45.1)
- Upgrading illuminate/conditionable (v10.45.0 => v10.45.1)
- Upgrading illuminate/config (v10.45.0 => v10.45.1)
- Upgrading illuminate/console (v10.45.0 => v10.45.1)
- Upgrading illuminate/container (v10.45.0 => v10.45.1)
- Upgrading illuminate/contracts (v10.45.0 => v10.45.1)
- Upgrading illuminate/events (v10.45.0 => v10.45.1)
- Upgrading illuminate/filesystem (v10.45.0 => v10.45.1)
- Upgrading illuminate/macroable (v10.45.0 => v10.45.1)
- Upgrading illuminate/pipeline (v10.45.0 => v10.45.1)
- Upgrading illuminate/process (v10.45.0 => v10.45.1)
- Upgrading illuminate/support (v10.45.0 => v10.45.1) …
=> Composer update with 17 changes 2024-02-22

update/composer.lock
- Upgrading phpunit/phpunit (10.5.10 => 10.5.11)
=> Composer update with 1 changes 2024-02-26

update/composer.lock
- Upgrading illuminate/bus (v10.45.1 => v10.46.0)
- Upgrading illuminate/cache (v10.45.1 => v10.46.0)
- Upgrading illuminate/collections (v10.45.1 => v10.46.0)
- Upgrading illuminate/conditionable (v10.45.1 => v10.46.0)
- Upgrading illuminate/config (v10.45.1 => v10.46.0)
- Upgrading illuminate/console (v10.45.1 => v10.46.0)
- Upgrading illuminate/container (v10.45.1 => v10.46.0)
- Upgrading illuminate/contracts (v10.45.1 => v10.46.0)
- Upgrading illuminate/events (v10.45.1 => v10.46.0)
- Upgrading illuminate/filesystem (v10.45.1 => v10.46.0)
- Upgrading illuminate/macroable (v10.45.1 => v10.46.0)
- Upgrading illuminate/pipeline (v10.45.1 => v10.46.0)
- Upgrading illuminate/process (v10.45.1 => v10.46.0)
- Upgrading illuminate/support (v10.45.1 => v10.46.0) …
=> Composer update with 23 changes 2024-02-28

update/composer.lock
- Upgrading phpunit/php-code-coverage (10.1.11 => 10.1.12)
- Upgrading sebastian/cli-parser (2.0.0 => 2.0.1)
- Upgrading sebastian/diff (5.1.0 => 5.1.1)
- Upgrading sebastian/exporter (5.1.1 => 5.1.2)
- Upgrading sebastian/global-state (6.0.1 => 6.0.2)
=> Composer update with 5 changes 2024-03-03

update/composer.lock
- Upgrading phar-io/manifest (2.0.3 => 2.0.4)
- Upgrading theseer/tokenizer (1.2.2 => 1.2.3)
=> Composer update with 2 changes 2024-03-04

update/composer.lock
- Upgrading illuminate/bus (v10.46.0 => v10.47.0)
- Upgrading illuminate/cache (v10.46.0 => v10.47.0)
- Upgrading illuminate/collections (v10.46.0 => v10.47.0)
- Upgrading illuminate/conditionable (v10.46.0 => v10.47.0)
- Upgrading illuminate/config (v10.46.0 => v10.47.0)
- Upgrading illuminate/console (v10.46.0 => v10.47.0)
- Upgrading illuminate/container (v10.46.0 => v10.47.0)
- Upgrading illuminate/contracts (v10.46.0 => v10.47.0)
- Upgrading illuminate/events (v10.46.0 => v10.47.0)
- Upgrading illuminate/filesystem (v10.46.0 => v10.47.0)
- Upgrading illuminate/macroable (v10.46.0 => v10.47.0)
- Upgrading illuminate/pipeline (v10.46.0 => v10.47.0)
- Upgrading illuminate/process (v10.46.0 => v10.47.0)
- Upgrading illuminate/support (v10.46.0 => v10.47.0) …
=> Composer update with 19 changes 2024-03-06

update/composer.lock
- Upgrading php-http/message (1.16.0 => 1.16.1)
=> Composer update with 1 changes 2024-03-08

update/composer.lock
- Upgrading league/flysystem (3.24.0 => 3.25.0)
- Upgrading phpunit/php-code-coverage (10.1.12 => 10.1.13)
- Upgrading phpunit/phpunit (10.5.11 => 10.5.12)
=> Composer update with 3 changes 2024-03-10

update/composer.lock
- Upgrading league/flysystem (3.25.0 => 3.25.1)
- Upgrading league/flysystem-local (3.23.1 => 3.25.1)
=> Composer update with 2 changes 2024-03-17

update/composer.lock
- Removing php-http/message-factory (1.1.0)
- Upgrading knplabs/github-api (v3.13.0 => v3.14.0)
- Upgrading mockery/mockery (1.6.9 => 1.6.10)
- Upgrading php-http/cache-plugin (1.8.1 => 2.0.0)
=> Composer update with 4 changes 2024-03-20

update/composer.lock
- Upgrading phpunit/phpunit (10.5.14 => 10.5.15)
=> Composer update with 1 changes 2024-03-22

update/composer.lock
- Upgrading sebastian/environment (6.0.1 => 6.1.0)
=> Composer update with 1 changes 2024-03-24

update/composer.lock
- Upgrading knplabs/github-api (v3.14.0 => v3.14.1)
=> Composer update with 1 changes 2024-03-25

update/composer.lock
- Upgrading league/flysystem (3.25.1 => 3.26.0)
=> Composer update with 1 changes 2024-03-26

update/composer.lock
- Upgrading laravel/prompts (v0.1.16 => v0.1.17)
=> Composer update with 1 changes 2024-03-27

update/composer.lock
- Upgrading phpunit/phpunit (10.5.15 => 10.5.16)
=> Composer update with 1 changes 2024-03-29

update/composer.lock
- Upgrading php-http/discovery (1.19.2 => 1.19.4)
=> Composer update with 1 changes 2024-03-30

update/composer.lock
- Upgrading laravel/framework (v11.1.1 => v11.2.0)
- Upgrading laravel/pint (v1.15.0 => v1.15.1)
- Upgrading psy/psysh (v0.12.2 => v0.12.3)
- Upgrading spatie/laravel-ignition (2.5.0 => 2.5.1)
=> Composer update with 4 changes 2024-04-03

update/composer.lock
- Upgrading symfony/console (v7.0.4 => v7.0.6)
- Upgrading symfony/error-handler (v7.0.4 => v7.0.6)
- Upgrading symfony/event-dispatcher-contracts (v3.4.0 => v3.4.2)
- Upgrading symfony/http-foundation (v7.0.4 => v7.0.6)
- Upgrading symfony/http-kernel (v7.0.5 => v7.0.6)
- Upgrading symfony/mailer (v7.0.4 => v7.0.6)
- Upgrading symfony/mime (v7.0.3 => v7.0.6)
- Upgrading symfony/routing (v7.0.5 => v7.0.6)
- Upgrading symfony/service-contracts (v3.4.1 => v3.4.2)
- Upgrading symfony/translation-contracts (v3.4.1 => v3.4.2)
- Upgrading symfony/var-dumper (v7.0.4 => v7.0.6)
=> Composer update with 11 changes 2024-04-04

update/composer.lock
- Upgrading nesbot/carbon (3.2.3 => 3.2.4)
- Upgrading phpunit/phpunit (11.0.9 => 11.1.0)
=> Composer update with 2 changes 2024-04-06

update/composer.lock
- Upgrading phpunit/phpunit (11.1.0 => 11.1.1)
=> Composer update with 1 changes 2024-04-07

update/composer.lock
- Upgrading league/flysystem (3.26.0 => 3.27.0)
=> Composer update with 1 changes 2024-04-08

update/composer.lock
- Upgrading laravel/framework (v11.2.0 => v11.3.0)
- Upgrading laravel/prompts (v0.1.17 => v0.1.18)
=> Composer update with 2 changes 2024-04-10

update/composer.lock
- Upgrading laravel/framework (v11.3.0 => v11.3.1)
=> Composer update with 1 changes 2024-04-11

update/composer.lock
- Upgrading monolog/monolog (3.5.0 => 3.6.0)
=> Composer update with 1 changes 2024-04-13

update/composer.lock
- Upgrading phpunit/phpunit (11.1.1 => 11.1.2)
=> Composer update with 1 changes 2024-04-16

update/composer.lock
- Upgrading laravel/framework (v11.3.1 => v11.4.0)
- Upgrading laravel/prompts (v0.1.18 => v0.1.19)
- Upgrading spatie/ignition (1.13.1 => 1.13.2)
- Upgrading spatie/laravel-ignition (2.5.1 => 2.5.2)
=> Composer update with 4 changes 2024-04-17

update/composer.lock
- Upgrading nesbot/carbon (3.2.4 => 3.3.0)
=> Composer update with 1 changes 2024-04-21

update/composer.lock
- Upgrading laravel/framework (v11.4.0 => v11.5.0)
- Upgrading laravel/pint (v1.15.1 => v1.15.2)
- Upgrading laravel/prompts (v0.1.19 => v0.1.20)
=> Composer update with 3 changes 2024-04-24

update/composer.lock
- Upgrading phpunit/phpunit (11.1.2 => 11.1.3)
- Upgrading spatie/backtrace (1.5.3 => 1.6.1)
=> Composer update with 2 changes 2024-04-25

update/composer.lock
- Upgrading spatie/ignition (1.13.2 => 1.14.0)
=> Composer update with 1 changes 2024-04-27

update/composer.lock
- Upgrading brick/math (0.11.0 => 0.12.1)
- Upgrading ramsey/uuid (4.7.5 => 4.7.6)
=> Composer update with 2 changes 2024-04-28

update/composer.lock
- Upgrading spatie/laravel-ignition (2.5.2 => 2.6.0)
- Upgrading symfony/clock (v7.0.5 => v7.0.7)
- Upgrading symfony/console (v7.0.6 => v7.0.7)
- Upgrading symfony/css-selector (v7.0.3 => v7.0.7)
- Upgrading symfony/error-handler (v7.0.6 => v7.0.7)
- Upgrading symfony/event-dispatcher (v7.0.3 => v7.0.7)
- Upgrading symfony/finder (v7.0.0 => v7.0.7)
- Upgrading symfony/http-foundation (v7.0.6 => v7.0.7)
- Upgrading symfony/http-kernel (v7.0.6 => v7.0.7)
- Upgrading symfony/mailer (v7.0.6 => v7.0.7)
- Upgrading symfony/mime (v7.0.6 => v7.0.7)
- Upgrading symfony/options-resolver (v7.0.0 => v7.0.7)
- Upgrading symfony/process (v7.0.4 => v7.0.7)
- Upgrading symfony/routing (v7.0.6 => v7.0.7)
- Upgrading symfony/string (v7.0.4 => v7.0.7)
- Upgrading symfony/translation (v7.0.4 => v7.0.7)
- …
=> Composer update with 18 changes 2024-04-30

update/composer.lock
- Upgrading laravel/framework (v11.5.0 => v11.6.0)
- Upgrading laravel/pint (v1.15.2 => v1.15.3)
- Upgrading laravel/prompts (v0.1.20 => v0.1.21)
- Upgrading spatie/laravel-ignition (2.6.0 => 2.6.2)
=> Composer update with 4 changes 2024-05-01

update/composer.lock
- Upgrading spatie/flare-client-php (1.4.4 => 1.5.0)
- Upgrading spatie/laravel-ignition (2.6.2 => 2.7.0)
=> Composer update with 2 changes 2024-05-03

update/composer.lock
- Upgrading spatie/flare-client-php (1.5.0 => 1.5.1)
- Upgrading spatie/ignition (1.14.0 => 1.14.1)
- Upgrading symfony/deprecation-contracts (v3.4.0 => v3.5.0)
- Upgrading symfony/event-dispatcher-contracts (v3.4.2 => v3.5.0)
- Upgrading symfony/service-contracts (v3.4.2 => v3.5.0)
- Upgrading symfony/translation-contracts (v3.4.2 => v3.5.0)
=> Composer update with 6 changes 2024-05-04

update/composer.lock
- Upgrading laravel/framework (v11.6.0 => v11.7.0)
=> Composer update with 1 changes 2024-05-08

update/composer.lock
- Upgrading psr/http-factory (1.0.2 => 1.1.0)
=> Composer update with 1 changes 2024-05-11

update/composer.lock
- Upgrading mockery/mockery (1.6.11 => 1.6.12)
=> Composer update with 1 changes 2024-05-16

update/composer.lock
- Upgrading laravel/framework (v11.7.0 => v11.8.0)
- Upgrading laravel/pint (v1.15.3 => v1.16.0)
- Upgrading laravel/prompts (v0.1.21 => v0.1.22)
=> Composer update with 3 changes 2024-05-22

update/composer.lock
- Upgrading league/flysystem (3.27.0 => 3.28.0)
- Upgrading league/flysystem-local (3.25.1 => 3.28.0)
- Upgrading spatie/flare-client-php (1.5.1 => 1.6.0)
=> Composer update with 3 changes 2024-05-23

update/composer.lock
- Upgrading nesbot/carbon (3.3.1 => 3.4.0)
=> Composer update with 1 changes 2024-05-26

update/composer.lock
- Upgrading composer/pcre (3.1.3 => 3.1.4)
=> Composer update with 1 changes 2024-05-28

update/composer.lock
- Upgrading laravel/framework (v11.8.0 => v11.9.1)
- Upgrading laravel/prompts (v0.1.22 => v0.1.23)
=> Composer update with 2 changes 2024-05-29

update/composer.lock
- Upgrading spatie/ignition (1.14.1 => 1.14.2)
=> Composer update with 1 changes 2024-05-30

update/composer.lock
- Upgrading laravel/framework (v11.9.1 => v11.9.2)
=> Composer update with 1 changes 2024-05-31

update/composer.lock
- Upgrading composer/class-map-generator (1.1.1 => 1.3.2)
- Upgrading phpstan/phpdoc-parser (1.29.0 => 1.29.1)
- Upgrading symfony/clock (v7.0.7 => v7.1.0)
- Upgrading symfony/console (v7.0.7 => v7.1.0)
- Upgrading symfony/css-selector (v7.0.7 => v7.1.0)
- Upgrading symfony/error-handler (v7.0.7 => v7.1.0)
- Upgrading symfony/event-dispatcher (v7.0.7 => v7.1.0)
- Upgrading symfony/finder (v7.0.7 => v7.1.0)
- Upgrading symfony/http-foundation (v7.0.7 => v7.1.0)
- Upgrading symfony/http-kernel (v7.0.7 => v7.1.0)
- Upgrading symfony/mailer (v7.0.7 => v7.1.0)
- Upgrading symfony/mime (v7.0.7 => v7.1.0)
- Upgrading symfony/options-resolver (v7.0.7 => v7.1.0)
- Upgrading symfony/process (v7.0.7 => v7.1.0)
- Upgrading symfony/routing (v7.0.7 => v7.1.0)
- Upgrading symfony/string (v7.0.7 => …
=> Composer update with 19 changes 2024-06-01

update/composer.lock
- Upgrading nesbot/carbon (3.4.0 => 3.5.0)
=> Composer update with 1 changes 2024-06-04

update/composer.lock
- Upgrading laravel/framework (v11.9.2 => v11.10.0)
- Upgrading symfony/clock (v7.1.0 => v7.1.1)
- Upgrading symfony/console (v7.1.0 => v7.1.1)
- Upgrading symfony/css-selector (v7.1.0 => v7.1.1)
- Upgrading symfony/error-handler (v7.1.0 => v7.1.1)
- Upgrading symfony/event-dispatcher (v7.1.0 => v7.1.1)
- Upgrading symfony/finder (v7.1.0 => v7.1.1)
- Upgrading symfony/http-foundation (v7.1.0 => v7.1.1)
- Upgrading symfony/http-kernel (v7.1.0 => v7.1.1)
- Upgrading symfony/mailer (v7.1.0 => v7.1.1)
- Upgrading symfony/mime (v7.1.0 => v7.1.1)
- Upgrading symfony/options-resolver (v7.1.0 => v7.1.1)
- Upgrading symfony/process (v7.1.0 => v7.1.1)
- Upgrading symfony/routing (v7.1.0 => v7.1.1)
- Upgrading symfony/string (v7.1.0 => v7.1.1)
- Upgrading symfony/translation (v7.1.0 => v7.1.1)
- …
=> Composer update with 18 changes 2024-06-05

update/composer.lock
- Upgrading phpunit/phpunit (11.1.3 => 11.2.0)
=> Composer update with 1 changes 2024-06-08

update/composer.lock
- Upgrading psy/psysh (v0.12.3 => v0.12.4)
=> Composer update with 1 changes 2024-06-10

update/composer.lock
- Upgrading composer/class-map-generator (1.3.2 => 1.3.3)
- Upgrading php-http/multipart-stream-builder (1.3.0 => 1.3.1)
=> Composer update with 2 changes 2024-06-11

update/composer.lock
- Upgrading phpunit/phpunit (11.2.0 => 11.2.1)
=> Composer update with 1 changes 2024-06-12

update/composer.lock
- Upgrading composer/class-map-generator (1.3.3 => 1.3.4)
- Upgrading myclabs/deep-copy (1.11.1 => 1.12.0)
- Locking spatie/error-solutions (1.0.0)
- Upgrading spatie/flare-client-php (1.6.0 => 1.7.0)
- Upgrading spatie/ignition (1.14.2 => 1.15.0)
- Upgrading spatie/laravel-ignition (2.7.0 => 2.8.0)
=> Composer update with 6 changes 2024-06-13

update/composer.lock
- Upgrading phpunit/phpunit (11.2.1 => 11.2.2)
=> Composer update with 1 changes 2024-06-16

update/composer.lock
- Upgrading sebastian/exporter (6.0.1 => 6.0.3)
- Upgrading sebastian/recursion-context (6.0.0 => 6.0.1)
=> Composer update with 2 changes 2024-06-18

update/composer.lock
- Upgrading laravel/framework (v11.10.0 => v11.11.0)
- Upgrading laravel/pint (v1.16.0 => v1.16.1)
- Upgrading laravel/prompts (v0.1.23 => v0.1.24)
- Upgrading sebastian/exporter (6.0.3 => 6.1.2)
=> Composer update with 4 changes 2024-06-19

update/composer.lock
- Upgrading phpunit/phpunit (11.2.2 => 11.2.3)
=> Composer update with 1 changes 2024-06-19

update/composer.lock
- Upgrading symfony/polyfill-ctype (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-intl-idn (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-mbstring (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-php72 (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-php80 (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-php83 (v1.29.0 => v1.30.0)
- Upgrading symfony/polyfill-uuid (v1.29.0 => v1.30.0)
=> Composer update with 9 changes 2024-06-20

update/composer.lock
- Upgrading laravel/framework (v11.11.0 => v11.11.1)
- Upgrading nesbot/carbon (3.5.0 => 3.6.0)
- Upgrading phpunit/phpunit (11.2.3 => 11.2.5)
=> Composer update with 3 changes 2024-06-21

update/composer.lock
- Upgrading spatie/error-solutions (1.0.0 => 1.0.1)
=> Composer update with 1 changes 2024-06-22

update/composer.lock
- Upgrading laravel/framework (v11.11.1 => v11.12.0)
=> Composer update with 1 changes 2024-06-26

update/composer.lock
- Upgrading spatie/error-solutions (1.0.1 => 1.0.2)
=> Composer update with 1 changes 2024-06-27

update/composer.lock
- Upgrading laravel/framework (v11.12.0 => v11.13.0)
- Upgrading spatie/error-solutions (1.0.2 => 1.0.3)
=> Composer update with 2 changes 2024-06-28

update/composer.lock
- Upgrading monolog/monolog (3.6.0 => 3.7.0)
- Upgrading spatie/error-solutions (1.0.3 => 1.0.4)
- Upgrading symfony/console (v7.1.1 => v7.1.2)
- Upgrading symfony/error-handler (v7.1.1 => v7.1.2)
- Upgrading symfony/http-kernel (v7.1.1 => v7.1.2)
- Upgrading symfony/mailer (v7.1.1 => v7.1.2)
- Upgrading symfony/mime (v7.1.1 => v7.1.2)
- Upgrading symfony/string (v7.1.1 => v7.1.2)
- Upgrading symfony/var-dumper (v7.1.1 => v7.1.2)
=> Composer update with 9 changes 2024-06-29

update/composer.lock
- Upgrading phpunit/php-code-coverage (11.0.3 => 11.0.4)
=> Composer update with 1 changes 2024-06-30

update/composer.lock
- Upgrading nikic/php-parser (v5.0.2 => v5.1.0)
=> Composer update with 1 changes 2024-07-02

update/composer.lock
- Upgrading laravel/framework (v11.13.0 => v11.14.0)
=> Composer update with 1 changes 2024-07-03

update/composer.lock
- Upgrading phpunit/php-code-coverage (11.0.4 => 11.0.5)
- Upgrading phpunit/php-file-iterator (5.0.0 => 5.0.1)
- Upgrading phpunit/php-invoker (5.0.0 => 5.0.1)
- Upgrading phpunit/php-text-template (4.0.0 => 4.0.1)
- Upgrading phpunit/php-timer (7.0.0 => 7.0.1)
- Upgrading phpunit/phpunit (11.2.5 => 11.2.6)
- Upgrading sebastian/cli-parser (3.0.1 => 3.0.2)
- Upgrading sebastian/code-unit (3.0.0 => 3.0.1)
- Upgrading sebastian/code-unit-reverse-lookup (4.0.0 => 4.0.1)
- Upgrading sebastian/comparator (6.0.0 => 6.0.1)
- Upgrading sebastian/complexity (4.0.0 => 4.0.1)
- Upgrading sebastian/diff (6.0.1 => 6.0.2)
- Upgrading sebastian/environment (7.1.0 => 7.2.0)
- Upgrading sebastian/exporter (6.1.2 => 6.1.3)
- Upgrading sebastian/global-state (7.0.1 => 7.0.2)
- Upgrading …
=> Composer update with 21 changes 2024-07-05

update/composer.lock
- Upgrading dflydev/dot-access-data (v3.0.2 => v3.0.3)
=> Composer update with 1 changes 2024-07-09

update/composer.lock
- Upgrading laravel/framework (v11.14.0 => v11.15.0)
- Upgrading laravel/pint (v1.16.1 => v1.16.2)
- Upgrading spatie/error-solutions (1.0.4 => 1.0.5)
=> Composer update with 3 changes 2024-07-10

update/composer.lock
- Upgrading phpunit/phpunit (11.2.6 => 11.2.7)
=> Composer update with 1 changes 2024-07-11

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.0.0 => v3.1.0)
=> Composer update with 1 changes 2024-07-13

update/composer.lock
- Upgrading laravel/framework (v11.15.0 => v11.16.0)
- Upgrading nesbot/carbon (3.6.0 => 3.7.0)
- Upgrading nunomaduro/collision (v8.1.1 => v8.3.0)
=> Composer update with 3 changes 2024-07-17

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.8.1 => 7.9.0)
- Upgrading guzzlehttp/promises (2.0.2 => 2.0.3)
- Upgrading guzzlehttp/psr7 (2.6.2 => 2.7.0)
- Upgrading phpunit/phpunit (11.2.7 => 11.2.8)
=> Composer update with 4 changes 2024-07-19

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.9.0 => 7.9.1)
=> Composer update with 1 changes 2024-07-20

update/composer.lock
- Upgrading graham-campbell/result-type (v1.1.2 => v1.1.3)
- Upgrading phpoption/phpoption (1.9.2 => 1.9.3)
- Upgrading vlucas/phpdotenv (v5.6.0 => v5.6.1)
=> Composer update with 3 changes 2024-07-21

update/composer.lock
- Upgrading league/commonmark (2.4.2 => 2.5.0)
- Upgrading spatie/backtrace (1.6.1 => 1.6.2)
- Upgrading spatie/error-solutions (1.0.5 => 1.1.0)
=> Composer update with 3 changes 2024-07-23

update/composer.lock
- Upgrading laravel/framework (v11.16.0 => v11.17.0)
- Upgrading laravel/pint (v1.16.2 => v1.17.0)
=> Composer update with 2 changes 2024-07-24

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.9.1 => 7.9.2)
- Upgrading league/commonmark (2.5.0 => 2.5.1)
=> Composer update with 2 changes 2024-07-25

update/composer.lock
- Upgrading composer/pcre (3.1.4 => 3.2.0)
- Upgrading spatie/error-solutions (1.1.0 => 1.1.1)
=> Composer update with 2 changes 2024-07-26

update/composer.lock
- Upgrading laravel/framework (v11.17.0 => v11.18.1)
- Upgrading symfony/console (v7.1.2 => v7.1.3)
- Upgrading symfony/error-handler (v7.1.2 => v7.1.3)
- Upgrading symfony/finder (v7.1.1 => v7.1.3)
- Upgrading symfony/http-foundation (v7.1.1 => v7.1.3)
- Upgrading symfony/http-kernel (v7.1.2 => v7.1.3)
- Upgrading symfony/process (v7.1.1 => v7.1.3)
- Upgrading symfony/routing (v7.1.1 => v7.1.3)
- Upgrading symfony/string (v7.1.2 => v7.1.3)
- Upgrading symfony/translation (v7.1.1 => v7.1.3)
- Upgrading symfony/var-dumper (v7.1.2 => v7.1.3)
=> Composer update with 11 changes 2024-07-27

update/composer.lock
- Upgrading laravel/framework (v11.18.1 => v11.19.0)
- Upgrading phpunit/phpunit (11.2.8 => 11.2.9)
=> Composer update with 2 changes 2024-07-31

update/composer.lock
- Upgrading laravel/pint (v1.17.0 => v1.17.1)
- Upgrading phpunit/phpunit (11.2.9 => 11.3.0)
- Upgrading spatie/flare-client-php (1.7.0 => 1.8.0)
=> Composer update with 3 changes 2024-08-02

update/composer.lock
- Upgrading nunomaduro/collision (v8.3.0 => v8.4.0)
=> Composer update with 1 changes 2024-08-04

update/composer.lock
- Upgrading laravel/framework (v11.19.0 => v11.20.0)
- Upgrading laravel/pint (v1.17.1 => v1.17.2)
- Upgrading laravel/serializable-closure (v1.3.3 => v1.3.4)
=> Composer update with 3 changes 2024-08-07

update/composer.lock
- Upgrading czproject/git-php (v4.2.0 => v4.3.0)
- Upgrading nette/utils (v4.0.4 => v4.0.5)
=> Composer update with 2 changes 2024-08-08

update/composer.lock
- Upgrading sebastian/comparator (6.0.1 => 6.0.2)
=> Composer update with 1 changes 2024-08-13

update/composer.lock
- Upgrading phpunit/phpunit (11.3.0 => 11.3.1)
=> Composer update with 1 changes 2024-08-14

update/composer.lock
- Upgrading league/commonmark (2.5.1 => 2.5.2)
=> Composer update with 1 changes 2024-08-15

update/composer.lock
- Upgrading league/commonmark (2.5.2 => 2.5.3)
=> Composer update with 1 changes 2024-08-17

update/composer.lock
- Upgrading composer/pcre (3.2.0 => 3.3.0)
- Upgrading nesbot/carbon (3.7.0 => 3.8.0)
=> Composer update with 2 changes 2024-08-20

update/composer.lock
- Upgrading laravel/framework (v11.20.0 => v11.21.0)
- Upgrading laravel/prompts (v0.1.24 => v0.1.25)
=> Composer update with 2 changes 2024-08-21

update/composer.lock
- Upgrading psr/log (3.0.0 => 3.0.1)
=> Composer update with 1 changes 2024-08-22

update/composer.lock
- Upgrading phpunit/php-file-iterator (5.0.1 => 5.1.0)
=> Composer update with 1 changes 2024-08-28

update/composer.lock
- Upgrading composer/pcre (3.3.0 => 3.3.1)
=> Composer update with 1 changes 2024-08-29

update/composer.lock
- Upgrading phpstan/phpdoc-parser (1.29.1 => 1.30.0)
=> Composer update with 1 changes 2024-08-30

update/composer.lock
- Upgrading symfony/console (v7.1.3 => v7.1.4)
- Upgrading symfony/finder (v7.1.3 => v7.1.4)
- Upgrading symfony/http-kernel (v7.1.3 => v7.1.4)
- Upgrading symfony/mime (v7.1.2 => v7.1.4)
- Upgrading symfony/routing (v7.1.3 => v7.1.4)
- Upgrading symfony/string (v7.1.3 => v7.1.4)
- Upgrading symfony/uid (v7.1.1 => v7.1.4)
- Upgrading symfony/var-dumper (v7.1.3 => v7.1.4)
=> Composer update with 8 changes 2024-08-31

update/composer.lock
- Upgrading php-http/multipart-stream-builder (1.3.1 => 1.4.0)
=> Composer update with 1 changes 2024-09-02

update/composer.lock
- Upgrading laravel/framework (v11.21.0 => v11.22.0)
- Upgrading laravel/pint (v1.17.2 => v1.17.3)
- Upgrading phpunit/phpunit (11.3.1 => 11.3.2)
=> Composer update with 3 changes 2024-09-04

update/composer.lock
- Upgrading nunomaduro/termwind (v2.0.1 => v2.1.0)
- Upgrading php-http/multipart-stream-builder (1.4.0 => 1.4.2)
- Upgrading phpunit/phpunit (11.3.2 => 11.3.3)
=> Composer update with 3 changes 2024-09-06

update/composer.lock
- Upgrading phpstan/phpdoc-parser (1.30.0 => 1.30.1)
=> Composer update with 1 changes 2024-09-08

update/composer.lock
- Removing symfony/polyfill-php72 (v1.30.0)
- Upgrading phpunit/phpunit (11.3.3 => 11.3.4)
- Upgrading symfony/polyfill-ctype (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-intl-idn (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-mbstring (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-php80 (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-php83 (v1.30.0 => v1.31.0)
- Upgrading symfony/polyfill-uuid (v1.30.0 => v1.31.0)
=> Composer update with 10 changes 2024-09-10

update/composer.lock
- Upgrading laravel/framework (v11.22.0 => v11.23.2)
- Upgrading psr/log (3.0.1 => 3.0.2)
- Upgrading sebastian/comparator (6.0.2 => 6.1.0)
=> Composer update with 3 changes 2024-09-12

update/composer.lock
- Upgrading laravel/framework (v11.23.2 => v11.23.4)
=> Composer update with 1 changes 2024-09-13

update/composer.lock
- Upgrading laravel/framework (v11.23.4 => v11.23.5)
- Upgrading phpunit/phpunit (11.3.4 => 11.3.5)
=> Composer update with 2 changes 2024-09-14

update/composer.lock
- Upgrading nikic/php-parser (v5.1.0 => v5.2.0)
=> Composer update with 1 changes 2024-09-16

update/composer.lock
- Upgrading sebastian/type (5.0.1 => 5.1.0)
=> Composer update with 1 changes 2024-09-18

update/composer.lock
- Upgrading phpunit/phpunit (11.3.5 => 11.3.6)
=> Composer update with 1 changes 2024-09-20

update/composer.lock
- Upgrading league/mime-type-detection (1.15.0 => 1.16.0)
- Upgrading symfony/console (v7.1.4 => v7.1.5)
- Upgrading symfony/http-foundation (v7.1.3 => v7.1.5)
- Upgrading symfony/http-kernel (v7.1.4 => v7.1.5)
- Upgrading symfony/mailer (v7.1.2 => v7.1.5)
- Upgrading symfony/mime (v7.1.4 => v7.1.5)
- Upgrading symfony/process (v7.1.3 => v7.1.5)
- Upgrading symfony/string (v7.1.4 => v7.1.5)
- Upgrading symfony/translation (v7.1.3 => v7.1.5)
- Upgrading symfony/uid (v7.1.4 => v7.1.5)
- Upgrading symfony/var-dumper (v7.1.4 => v7.1.5)
=> Composer update with 11 changes 2024-09-22

update/composer.lock
- Upgrading phpstan/phpdoc-parser (1.30.1 => 1.31.0)
=> Composer update with 1 changes 2024-09-23

update/composer.lock
- Upgrading laravel/framework (v11.24.1 => v11.25.0)
- Upgrading phpstan/phpdoc-parser (1.31.0 => 1.32.0)
=> Composer update with 2 changes 2024-09-27

update/composer.lock
- Upgrading league/flysystem (3.28.0 => 3.29.0)
- Upgrading league/flysystem-local (3.28.0 => 3.29.0)
- Upgrading nikic/php-parser (v5.2.0 => v5.3.0)
=> Composer update with 3 changes 2024-09-30

update/composer.lock
- Upgrading laravel/framework (v11.25.0 => v11.26.0)
- Upgrading laravel/prompts (v0.2.1 => v0.3.0)
=> Composer update with 2 changes 2024-10-02

update/composer.lock
- Upgrading php-http/cache-plugin (2.0.0 => 2.0.1)
- Upgrading php-http/discovery (1.19.4 => 1.20.0)
- Upgrading php-http/message (1.16.1 => 1.16.2)
=> Composer update with 3 changes 2024-10-03

update/composer.lock
- Upgrading composer/class-map-generator (1.3.4 => 1.4.0)
=> Composer update with 1 changes 2024-10-04

update/composer.lock
- Upgrading nette/schema (v1.3.0 => v1.3.1)
=> Composer update with 1 changes 2024-10-05

update/composer.lock
- Upgrading phpunit/phpunit (11.3.6 => 11.4.0)
=> Composer update with 1 changes 2024-10-06

update/composer.lock
- Upgrading nette/schema (v1.3.1 => v1.3.2)
=> Composer update with 1 changes 2024-10-07

update/composer.lock
- Upgrading laravel/framework (v11.26.0 => v11.27.1)
- Upgrading league/flysystem (3.29.0 => 3.29.1)
- Upgrading nikic/php-parser (v5.3.0 => v5.3.1)
- Upgrading phpunit/phpunit (11.4.0 => 11.4.1)
=> Composer update with 4 changes 2024-10-09

update/composer.lock
- Upgrading dragonmantank/cron-expression (v3.3.3 => v3.4.0)
- Upgrading laravel/framework (v11.27.1 => v11.27.2)
- Upgrading phpunit/php-code-coverage (11.0.6 => 11.0.7)
- Upgrading sebastian/version (5.0.1 => 5.0.2)
=> Composer update with 4 changes 2024-10-10

update/composer.lock
- Upgrading phpstan/phpdoc-parser (1.32.0 => 1.33.0)
=> Composer update with 1 changes 2024-10-14

update/composer.lock
- Upgrading laravel/framework (v11.27.2 => v11.28.0)
- Upgrading laravel/prompts (v0.3.0 => v0.3.1)
- Upgrading nunomaduro/collision (v8.4.0 => v8.5.0)
- Upgrading nunomaduro/termwind (v2.1.0 => v2.2.0)
=> Composer update with 4 changes 2024-10-16

update/composer.lock
- Upgrading barryvdh/reflection-docblock (v2.1.1 => v2.1.2)
- Upgrading laravel/framework (v11.28.0 => v11.28.1)
=> Composer update with 2 changes 2024-10-17

update/composer.lock
- Upgrading guzzlehttp/promises (2.0.3 => 2.0.4)
=> Composer update with 1 changes 2024-10-18

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.1.0 => v3.2.0)
- Upgrading sebastian/comparator (6.1.0 => 6.1.1)
=> Composer update with 2 changes 2024-10-19

update/composer.lock
- Upgrading phpunit/phpunit (11.4.1 => 11.4.2)
=> Composer update with 1 changes 2024-10-20

update/composer.lock
- Upgrading laravel/framework (v11.28.1 => v11.29.0)
=> Composer update with 1 changes 2024-10-23

update/composer.lock
- Upgrading barryvdh/reflection-docblock (v2.1.2 => v2.1.3)
=> Composer update with 1 changes 2024-10-24

update/composer.lock
- Upgrading symfony/clock (v7.1.1 => v7.1.6)
- Upgrading symfony/console (v7.1.5 => v7.1.6)
- Upgrading symfony/css-selector (v7.1.1 => v7.1.6)
- Upgrading symfony/error-handler (v7.1.3 => v7.1.6)
- Upgrading symfony/event-dispatcher (v7.1.1 => v7.1.6)
- Upgrading symfony/finder (v7.1.4 => v7.1.6)
- Upgrading symfony/http-foundation (v7.1.5 => v7.1.6)
- Upgrading symfony/http-kernel (v7.1.5 => v7.1.6)
- Upgrading symfony/mailer (v7.1.5 => v7.1.6)
- Upgrading symfony/mime (v7.1.5 => v7.1.6)
- Upgrading symfony/options-resolver (v7.1.1 => v7.1.6)
- Upgrading symfony/process (v7.1.5 => v7.1.6)
- Upgrading symfony/routing (v7.1.4 => v7.1.6)
- Upgrading symfony/string (v7.1.5 => v7.1.6)
- Upgrading symfony/translation (v7.1.5 => v7.1.6)
- Upgrading symfony/uid (v7.1.5 => v7.1.6)
- Upgrading …
=> Composer update with 17 changes 2024-10-28

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.2.0 => v3.2.1)
- Upgrading phpunit/phpunit (11.4.2 => 11.4.3)
=> Composer update with 2 changes 2024-10-29

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.2.1 => v3.2.2)
=> Composer update with 1 changes 2024-10-30

update/composer.lock
- Upgrading laravel/framework (v11.29.0 => v11.30.0)
- Upgrading sebastian/comparator (6.1.1 => 6.2.0)
=> Composer update with 2 changes 2024-10-31

update/composer.lock
- Upgrading sebastian/comparator (6.2.0 => 6.2.1)
=> Composer update with 1 changes 2024-11-01

update/composer.lock
- Upgrading nesbot/carbon (3.8.0 => 3.8.1)
- Upgrading phpdocumentor/type-resolver (1.8.2 => 1.9.0)
=> Composer update with 2 changes 2024-11-04

update/composer.lock
- Upgrading symfony/console (v7.1.6 => v7.1.7)
- Upgrading symfony/error-handler (v7.1.6 => v7.1.7)
- Upgrading symfony/http-foundation (v7.1.6 => v7.1.7)
- Upgrading symfony/http-kernel (v7.1.6 => v7.1.7)
- Upgrading symfony/process (v7.1.6 => v7.1.7)
- Upgrading symfony/var-dumper (v7.1.6 => v7.1.7)
=> Composer update with 6 changes 2024-11-07

update/composer.lock
- Upgrading knplabs/github-api (v3.15.0 => v3.16.0)
- Upgrading nesbot/carbon (3.8.1 => 3.8.2)
=> Composer update with 2 changes 2024-11-08

update/composer.lock
- Upgrading myclabs/deep-copy (1.12.0 => 1.12.1)
=> Composer update with 1 changes 2024-11-09

update/composer.lock
- Upgrading fakerphp/faker (v1.23.1 => v1.24.0)
- Upgrading phpdocumentor/type-resolver (1.9.0 => 1.10.0)
- Upgrading phpstan/phpdoc-parser (1.33.0 => 2.0.0)
=> Composer update with 3 changes 2024-11-10

update/composer.lock
- Upgrading composer/pcre (3.3.1 => 3.3.2)
- Upgrading laravel/framework (v11.30.0 => v11.31.0)
- Upgrading laravel/prompts (v0.3.1 => v0.3.2)
- Upgrading laravel/serializable-closure (v1.3.5 => v1.3.6)
- Upgrading monolog/monolog (3.7.0 => 3.8.0)
=> Composer update with 5 changes 2024-11-13

update/composer.lock
- Upgrading symfony/console (v7.1.7 => v7.1.8)
- Upgrading symfony/http-foundation (v7.1.7 => v7.1.8)
- Upgrading symfony/http-kernel (v7.1.7 => v7.1.8)
- Upgrading symfony/process (v7.1.7 => v7.1.8)
- Upgrading symfony/string (v7.1.6 => v7.1.8)
- Upgrading symfony/var-dumper (v7.1.7 => v7.1.8)
=> Composer update with 6 changes 2024-11-14

update/composer.lock
- Upgrading laravel/framework (v11.31.0 => v11.32.0)
=> Composer update with 1 changes 2024-11-16

update/composer.lock
- Upgrading spatie/backtrace (1.6.2 => 1.6.3)
=> Composer update with 1 changes 2024-11-19

update/composer.lock
- Upgrading laravel/framework (v11.32.0 => v11.33.2)
- Upgrading laravel/serializable-closure (v1.3.6 => v2.0.0)
=> Composer update with 2 changes 2024-11-20

update/composer.lock
- Upgrading laravel/pint (v1.18.1 => v1.18.2)
- Upgrading voku/portable-ascii (2.0.1 => 2.0.3)
=> Composer update with 2 changes 2024-11-21

update/composer.lock
- Upgrading fakerphp/faker (v1.24.0 => v1.24.1)
- Upgrading nunomaduro/termwind (v2.2.0 => v2.3.0)
=> Composer update with 2 changes 2024-11-22

update/composer.lock
- Upgrading composer/class-map-generator (1.4.0 => 1.5.0)
=> Composer update with 1 changes 2024-11-26

update/composer.lock
- Upgrading laravel/framework (v11.33.2 => v11.34.1)
- Upgrading laravel/pint (v1.18.2 => v1.18.3)
=> Composer update with 2 changes 2024-11-27

update/composer.lock
- Upgrading laravel/framework (v11.34.1 => v11.34.2)
- Upgrading phpunit/phpunit (11.4.3 => 11.4.4)
- Upgrading symfony/deprecation-contracts (v3.5.0 => v3.5.1)
- Upgrading symfony/event-dispatcher-contracts (v3.5.0 => v3.5.1)
- Upgrading symfony/http-foundation (v7.1.8 => v7.1.9)
- Upgrading symfony/http-kernel (v7.1.8 => v7.1.9)
- Upgrading symfony/options-resolver (v7.1.6 => v7.1.9)
- Upgrading symfony/routing (v7.1.6 => v7.1.9)
- Upgrading symfony/service-contracts (v3.5.0 => v3.5.1)
- Upgrading symfony/translation-contracts (v3.5.0 => v3.5.1)
=> Composer update with 10 changes 2024-11-28

update/composer.lock
- Upgrading psy/psysh (v0.12.4 => v0.12.5)
- Upgrading symfony/clock (v7.1.6 => v7.2.0)
- Upgrading symfony/console (v7.1.8 => v7.2.0)
- Upgrading symfony/css-selector (v7.1.6 => v7.2.0)
- Upgrading symfony/error-handler (v7.1.7 => v7.2.0)
- Upgrading symfony/event-dispatcher (v7.1.6 => v7.2.0)
- Upgrading symfony/finder (v7.1.6 => v7.2.0)
- Upgrading symfony/http-foundation (v7.1.9 => v7.2.0)
- Upgrading symfony/http-kernel (v7.1.9 => v7.2.0)
- Upgrading symfony/mailer (v7.1.6 => v7.2.0)
- Upgrading symfony/mime (v7.1.6 => v7.2.0)
- Upgrading symfony/options-resolver (v7.1.9 => v7.2.0)
- Upgrading symfony/process (v7.1.8 => v7.2.0)
- Upgrading symfony/routing (v7.1.9 => v7.2.0)
- Upgrading symfony/string (v7.1.8 => v7.2.0)
- Upgrading symfony/translation (v7.1.6 => v7.2.0)
- Upgrading …
=> Composer update with 18 changes 2024-11-30

update/composer.lock
- Upgrading spatie/backtrace (1.6.3 => 1.7.1)
- Upgrading spatie/flare-client-php (1.8.0 => 1.10.0)
- Upgrading spatie/laravel-ignition (2.8.0 => 2.9.0)
=> Composer update with 3 changes 2024-12-03

update/composer.lock
- Upgrading monolog/monolog (3.8.0 => 3.8.1)
- Upgrading sebastian/exporter (6.1.3 => 6.3.0)
=> Composer update with 2 changes 2024-12-06

update/composer.lock
- Upgrading phpunit/phpunit (11.4.4 => 11.5.0)
- Locking staabm/side-effects-detector (1.0.5)
=> Composer update with 2 changes 2024-12-07

update/composer.lock
- Upgrading doctrine/deprecations (1.1.3 => 1.1.4)
=> Composer update with 1 changes 2024-12-09

update/composer.lock
- Upgrading psy/psysh (v0.12.6 => v0.12.7)
=> Composer update with 1 changes 2024-12-10

update/composer.lock
- Upgrading laravel/framework (v11.34.2 => v11.35.0)
- Locking league/uri (7.5.1)
- Locking league/uri-interfaces (7.5.0)
=> Composer update with 3 changes 2024-12-11

update/composer.lock
- Upgrading laravel/framework (v11.35.0 => v11.35.1)
- Upgrading phpunit/php-code-coverage (11.0.7 => 11.0.8)
- Upgrading phpunit/phpunit (11.5.0 => 11.5.1)
- Upgrading sebastian/code-unit (3.0.1 => 3.0.2)
- Upgrading spatie/error-solutions (1.1.1 => 1.1.2)
- Upgrading symfony/console (v7.2.0 => v7.2.1)
- Upgrading symfony/error-handler (v7.2.0 => v7.2.1)
- Upgrading symfony/http-kernel (v7.2.0 => v7.2.1)
- Upgrading symfony/mime (v7.2.0 => v7.2.1)
=> Composer update with 9 changes 2024-12-13

update/composer.lock
- Upgrading laravel/framework (v11.35.1 => v11.36.1)
- Upgrading laravel/serializable-closure (v2.0.0 => v2.0.1)
=> Composer update with 2 changes 2024-12-18

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.2.2 => v3.3.0)
=> Composer update with 1 changes 2024-12-19

update/composer.lock
- Upgrading nesbot/carbon (3.8.2 => 3.8.3)
- Upgrading phpunit/phpunit (11.5.1 => 11.5.2)
- Upgrading tijsverkoyen/css-to-inline-styles (v2.2.7 => v2.3.0)
=> Composer update with 3 changes 2024-12-22

update/composer.lock
- Upgrading egulias/email-validator (4.0.2 => 4.0.3)
=> Composer update with 1 changes 2024-12-27

update/composer.lock
- Upgrading nesbot/carbon (3.8.3 => 3.8.4)
=> Composer update with 1 changes 2024-12-28

update/composer.lock
- Upgrading barryvdh/reflection-docblock (v2.1.3 => v2.2.0)
=> Composer update with 1 changes 2024-12-29

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.3.0 => v3.4.0)
- Upgrading league/commonmark (2.6.0 => 2.6.1)
=> Composer update with 2 changes 2024-12-30

update/composer.lock
- Upgrading barryvdh/reflection-docblock (v2.2.0 => v2.3.0)
- Upgrading laravel/pint (v1.18.3 => v1.19.0)
- Upgrading nikic/php-parser (v5.3.1 => v5.4.0)
=> Composer update with 3 changes 2024-12-31

update/composer.lock
- Upgrading symfony/finder (v7.2.0 => v7.2.2)
- Upgrading symfony/http-foundation (v7.2.0 => v7.2.2)
- Upgrading symfony/http-kernel (v7.2.1 => v7.2.2)
- Upgrading symfony/translation (v7.2.0 => v7.2.2)
=> Composer update with 4 changes 2025-01-01

update/composer.lock
- Upgrading laravel/framework (v11.36.1 => v11.37.0)
=> Composer update with 1 changes 2025-01-03

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.5.2 => v3.5.3)
=> Composer update with 1 changes 2025-01-09

update/composer.lock
- Upgrading phpunit/phpunit (11.5.2 => 11.5.3)
=> Composer update with 1 changes 2025-01-14

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.5.3 => v3.5.4)
- Upgrading laravel/framework (v11.37.0 => v11.38.2)
- Upgrading laravel/pint (v1.19.0 => v1.20.0)
- Upgrading laravel/prompts (v0.3.2 => v0.3.3)
=> Composer update with 4 changes 2025-01-15

update/composer.lock
- Upgrading barryvdh/reflection-docblock (v2.3.0 => v2.3.1)
=> Composer update with 1 changes 2025-01-19

update/composer.lock
- Upgrading laravel/framework (v11.38.2 => v11.39.0)
=> Composer update with 1 changes 2025-01-22

update/composer.lock
- Upgrading laravel/framework (v11.39.0 => v11.39.1)
=> Composer update with 1 changes 2025-01-23

update/composer.lock
- Upgrading laravel/framework (v11.39.1 => v11.40.0)
=> Composer update with 1 changes 2025-01-25

update/composer.lock
- Upgrading filp/whoops (2.16.0 => 2.17.0)
=> Composer update with 1 changes 2025-01-26

update/composer.lock
- Upgrading laravel/framework (v11.40.0 => v11.41.0)
- Upgrading laravel/prompts (v0.3.3 => v0.3.4)
- Upgrading laravel/serializable-closure (v2.0.1 => v2.0.2)
- Upgrading laravel/tinker (v2.10.0 => v2.10.1)
- Upgrading phpunit/phpunit (11.5.3 => 11.5.4)
=> Composer update with 5 changes 2025-01-29

update/composer.lock
- Upgrading phpunit/phpunit (11.5.4 => 11.5.5)
- Upgrading symfony/error-handler (v7.2.1 => v7.2.3)
- Upgrading symfony/http-foundation (v7.2.2 => v7.2.3)
- Upgrading symfony/http-kernel (v7.2.2 => v7.2.3)
- Upgrading symfony/mailer (v7.2.0 => v7.2.3)
- Upgrading symfony/mime (v7.2.1 => v7.2.3)
- Upgrading symfony/routing (v7.2.0 => v7.2.3)
- Upgrading symfony/var-dumper (v7.2.0 => v7.2.3)
=> Composer update with 8 changes 2025-01-30

update/composer.lock
- Upgrading laravel/framework (v11.41.0 => v11.41.3)
=> Composer update with 1 changes 2025-01-31

update/composer.lock
- Upgrading phpunit/phpunit (11.5.5 => 11.5.6)
=> Composer update with 1 changes 2025-02-01

update/composer.lock
- Upgrading guzzlehttp/uri-template (v1.0.3 => v1.0.4)
=> Composer update with 1 changes 2025-02-04

update/composer.lock
- Upgrading composer/class-map-generator (1.5.0 => 1.6.0)
=> Composer update with 1 changes 2025-02-06

update/composer.lock
- Upgrading phpunit/phpunit (11.5.6 => 11.5.7)
=> Composer update with 1 changes 2025-02-07

update/composer.lock
- Upgrading laravel/framework (v11.41.3 => v11.42.0)
- Upgrading laravel/prompts (v0.3.4 => v0.3.5)
- Upgrading laravel/serializable-closure (v2.0.2 => v2.0.3)
- Upgrading nesbot/carbon (3.8.4 => 3.8.5)
=> Composer update with 4 changes 2025-02-12

update/composer.lock
- Upgrading laravel/framework (v11.42.0 => v11.42.1)
- Upgrading myclabs/deep-copy (1.12.1 => 1.13.0)
=> Composer update with 2 changes 2025-02-13

update/composer.lock
- Upgrading spatie/error-solutions (1.1.2 => 1.1.3)
- Upgrading spatie/flare-client-php (1.10.0 => 1.10.1)
=> Composer update with 2 changes 2025-02-15

update/composer.lock
- Upgrading laravel/pint (v1.20.0 => v1.21.0)
=> Composer update with 1 changes 2025-02-18

update/composer.lock
- Upgrading laravel/framework (v11.42.1 => v11.43.0)
- Upgrading phpunit/phpunit (11.5.7 => 11.5.8)
=> Composer update with 2 changes 2025-02-19

update/composer.lock
- Upgrading laravel/framework (v11.43.0 => v11.43.2)
=> Composer update with 1 changes 2025-02-20

update/composer.lock
- Upgrading nesbot/carbon (3.8.5 => 3.8.6)
- Upgrading spatie/laravel-ignition (2.9.0 => 2.9.1)
=> Composer update with 2 changes 2025-02-21

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.5.4 => v3.5.5)
- Upgrading phpunit/phpunit (11.5.8 => 11.5.9)
- Upgrading spatie/ignition (1.15.0 => 1.15.1)
=> Composer update with 3 changes 2025-02-22

update/composer.lock
- Upgrading laravel/framework (v11.43.2 => v11.44.0)
=> Composer update with 1 changes 2025-02-25

update/composer.lock
- Upgrading phpunit/php-code-coverage (11.0.8 => 11.0.9)
- Upgrading phpunit/phpunit (11.5.9 => 11.5.10)
=> Composer update with 2 changes 2025-02-26

update/composer.lock
- Upgrading brick/math (0.12.1 => 0.12.2)
- Upgrading symfony/error-handler (v7.2.3 => v7.2.4)
- Upgrading symfony/http-kernel (v7.2.3 => v7.2.4)
- Upgrading symfony/mime (v7.2.3 => v7.2.4)
- Upgrading symfony/process (v7.2.0 => v7.2.4)
- Upgrading symfony/translation (v7.2.2 => v7.2.4)
=> Composer update with 6 changes 2025-02-27

update/composer.lock
- Upgrading brick/math (0.12.2 => 0.12.3)
=> Composer update with 1 changes 2025-03-01

update/composer.lock
- Upgrading ramsey/collection (2.0.0 => 2.1.0)
=> Composer update with 1 changes 2025-03-03

update/composer.lock
- Upgrading laravel/framework (v12.0.1 => v12.1.0)
=> Composer update with 1 changes 2025-03-05

update/composer.lock
- Upgrading laravel/framework (v12.1.0 => v12.1.1)
- Upgrading phpunit/phpunit (11.5.10 => 11.5.11)
=> Composer update with 2 changes 2025-03-06

update/composer.lock
- Upgrading phpunit/phpunit (11.5.11 => 11.5.12)
- Upgrading sebastian/comparator (6.3.0 => 6.3.1)
=> Composer update with 2 changes 2025-03-08

update/composer.lock
- Upgrading laravel/pint (v1.21.0 => v1.21.1)
=> Composer update with 1 changes 2025-03-11

update/composer.lock
- Upgrading laravel/framework (v12.1.1 => v12.2.0)
=> Composer update with 1 changes 2025-03-14

update/composer.lock
- Upgrading filp/whoops (2.17.0 => 2.18.0)
- Upgrading psy/psysh (v0.12.7 => v0.12.8)
=> Composer update with 2 changes 2025-03-16

update/composer.lock
- Upgrading laravel/framework (v12.2.0 => v12.3.0)
- Upgrading phpunit/phpunit (11.5.12 => 11.5.13)
- Upgrading sebastian/type (5.1.0 => 5.1.2)
=> Composer update with 3 changes 2025-03-19

update/composer.lock
- Upgrading phpunit/phpunit (11.5.13 => 11.5.14)
- Upgrading sebastian/code-unit (3.0.2 => 3.0.3)
=> Composer update with 2 changes 2025-03-20

update/composer.lock
- Upgrading egulias/email-validator (4.0.3 => 4.0.4)
=> Composer update with 1 changes 2025-03-21

update/composer.lock
- Upgrading ramsey/collection (2.1.0 => 2.1.1)
=> Composer update with 1 changes 2025-03-23

update/composer.lock
- Upgrading czproject/git-php (v4.3.0 => v4.4.0)
- Upgrading phpunit/phpunit (11.5.14 => 11.5.15)
=> Composer update with 2 changes 2025-03-24

update/composer.lock
- Upgrading composer/class-map-generator (1.6.0 => 1.6.1)
- Upgrading monolog/monolog (3.8.1 => 3.9.0)
=> Composer update with 2 changes 2025-03-25

update/composer.lock
- Upgrading guzzlehttp/guzzle (7.9.2 => 7.9.3)
- Upgrading guzzlehttp/promises (2.0.4 => 2.2.0)
- Upgrading guzzlehttp/psr7 (2.7.0 => 2.7.1)
=> Composer update with 3 changes 2025-03-28

update/composer.lock
- Upgrading laravel/framework (v12.3.0 => v12.4.0)
=> Composer update with 1 changes 2025-03-30

update/composer.lock
- Upgrading laravel/framework (v12.4.0 => v12.4.1)
- Upgrading nette/utils (v4.0.5 => v4.0.6)
=> Composer update with 2 changes 2025-03-31

update/composer.lock
- Upgrading laravel/framework (v12.4.1 => v12.5.0)
=> Composer update with 1 changes 2025-04-02

update/composer.lock
- Upgrading laravel/framework (v12.5.0 => v12.6.0)
- Upgrading nesbot/carbon (3.8.6 => 3.9.0)
=> Composer update with 2 changes 2025-04-03

update/composer.lock
- Upgrading laravel/framework (v12.6.0 => v12.7.2)
- Upgrading nunomaduro/collision (v8.7.0 => v8.8.0)
=> Composer update with 2 changes 2025-04-04

update/composer.lock
- Upgrading laravel/framework (v12.7.2 => v12.8.1)
- Upgrading laravel/pint (v1.21.2 => v1.22.0)
- Upgrading phpunit/phpunit (11.5.15 => 11.5.17)
=> Composer update with 3 changes 2025-04-09

update/composer.lock
- Upgrading laravel/framework (v12.8.1 => v12.9.0)
=> Composer update with 1 changes 2025-04-16

update/composer.lock
- Upgrading laravel/framework (v12.9.0 => v12.9.2)
=> Composer update with 1 changes 2025-04-17

update/composer.lock
- Upgrading league/commonmark (2.6.1 => 2.6.2)
=> Composer update with 1 changes 2025-04-19

update/composer.lock
- Upgrading laravel/framework (v12.9.2 => v12.10.0)
- Upgrading phpunit/phpunit (11.5.17 => 11.5.18)
=> Composer update with 2 changes 2025-04-23

update/composer.lock
- Upgrading laravel/framework (v12.10.0 => v12.10.1)
=> Composer update with 1 changes 2025-04-24

update/composer.lock
- Upgrading laravel/framework (v12.10.1 => v12.10.2)
=> Composer update with 1 changes 2025-04-25

update/composer.lock
- Upgrading hamcrest/hamcrest-php (v2.0.1 => v2.1.0)
- Upgrading laravel/framework (v12.10.2 => v12.11.0)
- Upgrading myclabs/deep-copy (1.13.0 => 1.13.1)
=> Composer update with 3 changes 2025-04-30

update/composer.lock
- Upgrading hamcrest/hamcrest-php (v2.1.0 => v2.1.1)
- Upgrading laravel/framework (v12.11.0 => v12.11.1)
- Upgrading vlucas/phpdotenv (v5.6.1 => v5.6.2)
=> Composer update with 3 changes 2025-05-01

update/composer.lock
- Upgrading laravel/framework (v12.11.1 => v12.12.0)
- Upgrading nesbot/carbon (3.9.0 => 3.9.1)
=> Composer update with 2 changes 2025-05-02

update/composer.lock
- Upgrading phpunit/phpunit (11.5.18 => 11.5.19)
- Upgrading symfony/console (v7.2.5 => v7.2.6)
- Upgrading symfony/http-foundation (v7.2.5 => v7.2.6)
- Upgrading symfony/http-kernel (v7.2.5 => v7.2.6)
- Upgrading symfony/mailer (v7.2.3 => v7.2.6)
- Upgrading symfony/mime (v7.2.4 => v7.2.6)
- Upgrading symfony/polyfill-ctype (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-intl-idn (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-mbstring (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-php80 (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-php83 (v1.31.0 => v1.32.0)
- Upgrading symfony/polyfill-uuid (v1.31.0 => v1.32.0)
- Upgrading symfony/string (v7.2.0 …
=> Composer update with 17 changes 2025-05-03

update/composer.lock
- Upgrading league/commonmark (2.6.2 => 2.7.0)
=> Composer update with 1 changes 2025-05-06

update/composer.lock
- Upgrading laravel/framework (v12.12.0 => v12.13.0)
=> Composer update with 1 changes 2025-05-08

update/composer.lock
- Upgrading laravel/pint (v1.22.0 => v1.22.1)
- Upgrading nunomaduro/termwind (v2.3.0 => v2.3.1)
=> Composer update with 2 changes 2025-05-09

update/composer.lock
- Upgrading phpunit/phpunit (11.5.19 => 11.5.20)
=> Composer update with 1 changes 2025-05-12

update/composer.lock
- Upgrading laravel/framework (v12.14.1 => v12.15.0)
=> Composer update with 1 changes 2025-05-21

update/composer.lock
- Upgrading phpunit/phpunit (11.5.20 => 11.5.21)
- Upgrading sebastian/environment (7.2.0 => 7.2.1)
=> Composer update with 2 changes 2025-05-22

update/composer.lock
- Upgrading laravel/framework (v12.15.0 => v12.16.0)
=> Composer update with 1 changes 2025-05-28

update/composer.lock
- Upgrading symfony/clock (v7.2.0 => v7.3.0)
- Upgrading symfony/console (v7.2.6 => v7.3.0)
- Upgrading symfony/css-selector (v7.2.0 => v7.3.0)
- Upgrading symfony/error-handler (v7.2.5 => v7.3.0)
- Upgrading symfony/event-dispatcher (v7.2.0 => v7.3.0)
- Upgrading symfony/finder (v7.2.2 => v7.3.0)
- Upgrading symfony/http-foundation (v7.2.6 => v7.3.0)
- Upgrading symfony/http-kernel (v7.2.6 => v7.3.0)
- Upgrading symfony/mailer (v7.2.6 => v7.3.0)
- Upgrading symfony/mime (v7.2.6 => v7.3.0)
- Upgrading symfony/options-resolver (v7.2.0 => v7.3.0)
- Upgrading symfony/process (v7.2.5 => v7.3.0)
- Upgrading symfony/routing (v7.2.3 => v7.3.0)
- Upgrading symfony/string (v7.2.6 => v7.3.0)
- Upgrading symfony/translation (v7.2.6 => v7.3.0)
- Upgrading symfony/uid (v7.2.0 => v7.3.0)
- Upgrading …
=> Composer update with 17 changes 2025-05-30

update/composer.lock
- Upgrading czproject/git-php (v4.4.0 => v4.5.0)
- Upgrading laravel/framework (v12.17.0 => v12.18.0)
- Upgrading nunomaduro/collision (v8.8.0 => v8.8.1)
=> Composer update with 3 changes 2025-06-11

update/composer.lock
- Upgrading filp/whoops (2.18.1 => 2.18.2)
=> Composer update with 1 changes 2025-06-12

update/composer.lock
- Upgrading nesbot/carbon (3.9.1 => 3.10.0)
=> Composer update with 1 changes 2025-06-13

update/composer.lock
- Upgrading phpunit/phpunit (11.5.22 => 11.5.23)
=> Composer update with 1 changes 2025-06-14

update/composer.lock
- Upgrading filp/whoops (2.18.2 => 2.18.3)
=> Composer update with 1 changes 2025-06-16

update/composer.lock
- Upgrading laravel/framework (v12.19.2 => v12.19.3)
- Upgrading phpunit/php-code-coverage (11.0.9 => 11.0.10)
=> Composer update with 2 changes 2025-06-19

update/composer.lock
- Upgrading nesbot/carbon (3.10.0 => 3.10.1)
- Upgrading phpunit/phpunit (11.5.23 => 11.5.24)
- Upgrading psy/psysh (v0.12.8 => v0.12.9)
=> Composer update with 3 changes 2025-06-23

update/composer.lock
- Upgrading league/flysystem (3.29.1 => 3.30.0)
- Upgrading league/flysystem-local (3.29.0 => 3.30.0)
- Upgrading ramsey/uuid (4.8.1 => 4.9.0)
=> Composer update with 3 changes 2025-06-26

update/composer.lock
- Upgrading phpunit/phpunit (11.5.24 => 11.5.25)
=> Composer update with 1 changes 2025-06-28

update/composer.lock
- Upgrading symfony/console (v7.3.0 => v7.3.1)
- Upgrading symfony/error-handler (v7.3.0 => v7.3.1)
- Upgrading symfony/http-foundation (v7.3.0 => v7.3.1)
- Upgrading symfony/http-kernel (v7.3.0 => v7.3.1)
- Upgrading symfony/mailer (v7.3.0 => v7.3.1)
- Upgrading symfony/translation (v7.3.0 => v7.3.1)
- Upgrading symfony/uid (v7.3.0 => v7.3.1)
- Upgrading symfony/var-dumper (v7.3.0 => v7.3.1)
=> Composer update with 8 changes 2025-06-29

update/composer.lock
- Upgrading laravel/pint (v1.22.1 => v1.23.0)
=> Composer update with 1 changes 2025-07-04

update/composer.lock
- Upgrading myclabs/deep-copy (1.13.1 => 1.13.2)
- Upgrading phpunit/phpunit (11.5.25 => 11.5.26)
=> Composer update with 2 changes 2025-07-05

update/composer.lock
- Upgrading myclabs/deep-copy (1.13.2 => 1.13.3)
=> Composer update with 1 changes 2025-07-07

update/composer.lock
- Upgrading laravel/framework (v12.19.3 => v12.20.0)
- Upgrading laravel/prompts (v0.3.5 => v0.3.6)
=> Composer update with 2 changes 2025-07-09

update/composer.lock
- Upgrading laravel/pint (v1.23.0 => v1.24.0)
=> Composer update with 1 changes 2025-07-11

update/composer.lock
- Upgrading barryvdh/laravel-ide-helper (v3.5.5 => v3.6.0)
- Upgrading barryvdh/reflection-docblock (v2.3.1 => v2.4.0)
=> Composer update with 2 changes 2025-07-19

update/composer.lock
- Upgrading laravel/framework (v12.20.0 => v12.21.0)
=> Composer update with 1 changes 2025-07-23

update/composer.lock
- Upgrading nikic/php-parser (v5.5.0 => v5.6.0)
=> Composer update with 1 changes 2025-07-28

update/composer.lock
- Upgrading myclabs/deep-copy (1.13.3 => 1.13.4)
=> Composer update with 1 changes 2025-08-02

update/composer.lock
- Upgrading nesbot/carbon (3.10.1 => 3.10.2)
=> Composer update with 1 changes 2025-08-03

update/composer.lock
- Upgrading nette/utils (v4.0.7 => v4.0.8)
=> Composer update with 1 changes 2025-08-07

update/composer.lock
- Upgrading filp/whoops (2.18.3 => 2.18.4)
- Upgrading laravel/framework (v12.22.0 => v12.22.1)
=> Composer update with 2 changes 2025-08-09

update/composer.lock
- Upgrading doctrine/inflector (2.0.10 => 2.1.0)
- Upgrading phpunit/phpunit (11.5.29 => 11.5.30)
- Upgrading sebastian/comparator (6.3.1 => 6.3.2)
=> Composer update with 3 changes 2025-08-11

update/composer.lock
- Upgrading symfony/polyfill-ctype (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-intl-grapheme (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-intl-idn (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-intl-normalizer (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-mbstring (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-php80 (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-php83 (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-php84 (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-php85 (v1.32.0 => v1.33.0)
- Upgrading symfony/polyfill-uuid (v1.32.0 => v1.33.0)
=> Composer update with 10 changes 2025-08-20

update/composer.lock
- Upgrading composer/class-map-generator (1.6.1 => 1.6.2)
- Upgrading phpunit/phpunit (11.5.33 => 11.5.34)
=> Composer update with 2 changes 2025-08-21

update/composer.lock
- Upgrading laravel/framework (v12.25.0 => v12.26.2)
=> Composer update with 1 changes 2025-08-27

update/composer.lock
- Upgrading laravel/framework (v12.26.2 => v12.26.3)
- Upgrading phpunit/php-code-coverage (11.0.10 => 11.0.11)
=> Composer update with 2 changes 2025-08-28

update/composer.lock
- Upgrading laravel/framework (v12.26.3 => v12.26.4)
- Upgrading symfony/console (v7.3.2 => v7.3.3)
- Upgrading symfony/event-dispatcher (v7.3.0 => v7.3.3)
- Upgrading symfony/http-foundation (v7.3.2 => v7.3.3)
- Upgrading symfony/http-kernel (v7.3.2 => v7.3.3)
- Upgrading symfony/mailer (v7.3.2 => v7.3.3)
- Upgrading symfony/options-resolver (v7.3.2 => v7.3.3)
- Upgrading symfony/process (v7.3.0 => v7.3.3)
- Upgrading symfony/string (v7.3.2 => v7.3.3)
- Upgrading symfony/translation (v7.3.2 => v7.3.3)
- Upgrading symfony/var-dumper (v7.3.2 => v7.3.3)
=> Composer update with 11 changes 2025-08-30

update/composer.lock
- Upgrading laravel/framework (v12.27.1 => v12.28.0)
- Upgrading phpunit/phpunit (11.5.35 => 11.5.36)
=> Composer update with 2 changes 2025-09-04

update/composer.lock
- Upgrading nesbot/carbon (3.10.2 => 3.10.3)
=> Composer update with 1 changes 2025-09-07

update/composer.lock
- Upgrading laravel/framework (v12.28.1 => v12.29.0)
- Upgrading laravel/pint (v1.24.0 => v1.25.0)
- Locking phiki/phiki (v2.0.0)
=> Composer update with 3 changes 2025-09-17

update/composer.lock
- Upgrading laravel/framework (v12.29.0 => v12.30.1)
- Upgrading laravel/pint (v1.25.0 => v1.25.1)
- Upgrading phiki/phiki (v2.0.0 => v2.0.2)
=> Composer update with 3 changes 2025-09-19

update/composer.lock
- Upgrading phiki/phiki (v2.0.2 => v2.0.3)
=> Composer update with 1 changes 2025-09-20

update/composer.lock
- Upgrading phpunit/phpunit (11.5.40 => 11.5.41)
- Upgrading sebastian/exporter (6.3.1 => 6.3.2)
=> Composer update with 2 changes 2025-09-25

update/composer.lock
- Upgrading laravel/framework (v12.32.5 => v12.33.0)
=> Composer update with 1 changes 2025-10-08
